import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
  
} from "lucide-react";
"Analytics": {
      sections: [
        {
          title: "Modules",
          icon: <Grid className="w-4 h-4" />,
          items: ["Teamspace Modules", "Module Management", "Custom Modules"]
        },
        {
          title: "Reports",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Reports", "Favorite Reports", "Recent Reports", "Shared Reports", "Create New Report"]
        },
        {
          title: "Dashboards",
          icon: <Monitor className="w-4 h-4" />,
          items: ["All Dashboards", "Favorite Dashboards", "Recent Dashboards", "Shared Dashboards", "Create New Dashboard"]
        },
        {
          title: "Data Sources",
          icon: <Database className="w-4 h-4" />,
          items: ["Connected Sources", "Import Data", "Database Connections", "File Imports", "Zoho App Integrations", "Third-party Connectors"]
        },
        {
          title: "AI & Intelligence",
          icon: <Bot className="w-4 h-4" />,
          items: ["Ask Zia", "Zia Insights", "Predictive Analytics", "Advanced Analytics"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Shared Workspaces", "Comments & Annotations", "User Management", "Activity Logs"]
        },
        {
          title: "New Features 2024",
          icon: <Star className="w-4 h-4" />,
          items: ["Sunburst Charts", "Enhanced JavaScript API", "Distributed Architecture", "Puvi Font Support"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Workspace Settings", "Currency Formatting", "Week/Year Format", "Fiscal Year Settings", "Data Backup", "User Permissions"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Drag-and-drop report builder",
            "Library of chart types",
            "Interactive dashboard filters",
            "Import from CSV/Excel",
            "Scheduled email reports"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Connect to multiple data sources",
            "AI assistant 'Ask Zia'",
            "Advanced data preparation",
            "Secure collaboration features",
            "Embeddable analytics"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Analyzing scattered data",
            "Enabling self-service reporting",
            "Creating insightful, interactive reports",
            "Automating report distribution",
            "Visualizing data to spot trends",
            "Sharing sensitive data securely",
            "Cleaning messy data for analysis",
            "Embedding analytics in other apps",
            "Getting quick answers from data",
            "Analyzing large datasets efficiently"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "Zia: AI natural language querying",
            "Zia Insights: Automated data narratives",
            "Predictive forecasting models",
            "AI-powered 'what-if' analysis",
            "Smart data cleansing",
            "AI chart type suggestions",
            "Automated key driver analysis",
            "AI-based anomaly detection",
            "Natural Language Generation (NLG)",
            "AI-powered data storytelling",
            "Smart data prep suggestions",
            "AI recommendations for data blending",
            "Predictive modeling (churn, sales)",
            "AI pattern recognition",
            "Automated data clustering",
            "AI-powered goal seeking",
            "Smart metric change diagnostics",
            "AI suggestions for new KPIs",
            "Automated data enrichment",
            "Conversational analytics (chat/voice)"
          ]
        }
      ]
    }