import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Apptics": {
      sections: [
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["App Analytics", "User Analytics", "Performance Analytics", "Custom Analytics", "Real-time Analytics", "Event Analytics", "Funnel Analysis", "Cohort Analysis"]
        },
        {
          title: "Users",
          icon: <Users className="w-4 h-4" />,
          items: ["User Behavior", "User Segments", "User Journey", "User Retention", "User Acquisition"]
        },
        {
          title: "Performance",
          icon: <TrendingUp className="w-4 h-4" />,
          items: ["App Performance", "Load Times", "Crash Reports", "Error Tracking", "Performance Optimization", "ANR Reports", "Performance Monitoring", "Memory Usage"]
        },
        {
          title: "Events",
          icon: <Target className="w-4 h-4" />,
          items: ["Custom Events", "Event Tracking", "Conversion Events", "Event Analytics", "Event Funnels"]
        },
        {
          title: "Reports",
          icon: <FileText className="w-4 h-4" />,
          items: ["Standard Reports", "Custom Reports", "Scheduled Reports", "Export Reports", "Report Builder", "Export Data"]
        },
        {
          title: "Integration",
          icon: <Link2 className="w-4 h-4" />,
          items: ["SDK Integration", "API Integration", "Third-party Tools", "Data Export", "Custom Integration"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["App Settings", "Analytics Settings", "Privacy Settings", "Team Settings", "Account Settings"]
        },
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["App Overview", "Key Metrics", "Real-time Data", "Performance Summary"]
        },
        {
          title: "User Behavior",
          icon: <Users className="w-4 h-4" />,
          items: ["User Sessions", "User Journey", "Heatmaps", "User Feedback", "A/B Testing"]
        },
        {
          title: "Custom Events",
          icon: <Tag className="w-4 h-4" />,
          items: ["Event Tracking", "Custom Metrics", "Goal Tracking", "Conversion Events", "Event Funnels"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Real-time user analytics",
            "Crash reporting",
            "Custom event tracking",
            "Audience segmentation",
            "Key metrics dashboard"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Funnel analysis",
            "In-app feedback & surveys",
            "Performance monitoring",
            "Push notification campaigns",
            "A/B testing"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Understanding app usage",
            "Diagnosing app crashes",
            "Tracking user navigation",
            "Pinpointing performance bottlenecks",
            "Getting feedback from users",
            "Announcing new features",
            "Improving key workflows",
            "Identifying popular features",
            "Increasing user retention",
            "Targeting specific user groups"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI root cause analysis for crashes",
            "Predictive user churn analysis",
            "AI suggestions for funnel optimization",
            "Smart performance anomaly alerts",
            "AI-driven behavioral segmentation",
            "Natural language analytics queries",
            "AI recommendations for A/B tests",
            "In-app feedback sentiment analysis",
            "Predictive app usage forecasting",
            "AI insights into power users",
            "Automated performance reports",
            "AI suggestions for push notifications",
            "Smart 'rage click' detection",
            "AI 'what-if' analysis for features",
            "Automated release health correlation",
            "AI-powered user journey mapping",
            "Predictive conversion analysis",
            "Smart industry benchmark comparison",
            "AI recommendations for app store ratings",
            "Automated user feedback tagging"
          ]
        }
      ]
    }
