import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Backstage": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Event Overview", "Registration Stats", "Revenue Summary", "Recent Activities"]
        },
        {
          title: "Events",
          icon: <Calendar className="w-4 h-4" />,
          items: ["All Events", "Upcoming Events", "Past Events", "Event Templates", "Event Series"]
        },
        {
          title: "Registration",
          icon: <UserCheck className="w-4 h-4" />,
          items: ["Registration Forms", "Ticket Types", "Pricing Tiers", "Discount Codes", "Waitlist Management"]
        },
        {
          title: "Attendees",
          icon: <Users className="w-4 h-4" />,
          items: ["Attendee List", "Check-in Management", "Attendee Communication", "Badge Printing", "Networking"]
        },
        {
          title: "Marketing",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Email Campaigns", "Social Promotion", "Landing Pages", "Referral Program", "Analytics"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Registration Reports", "Revenue Reports", "Attendance Reports", "Survey Results"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable registration forms",
            "On-demand badge printing",
            "Simple event website builder",
            "Attendee email templates",
            "Mobile app for attendees"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Comprehensive virtual event platform",
            "Advanced ticket management",
            "Sponsor & exhibitor portals",
            "Advanced event analytics",
            "Marketing & CRM integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Managing chaotic event registrations",
            "Promoting events to the right audience",
            "Keeping virtual attendees engaged",
            "Demonstrating value to sponsors",
            "Handling large event check-ins",
            "Communicating last-minute changes",
            "Facilitating attendee networking",
            "Gathering post-event feedback",
            "Proving event ROI",
            "Managing hybrid events seamlessly"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered attendee matchmaking",
            "Predictive attendance analysis",
            "AI-driven session recommendations",
            "Live sentiment analysis",
            "AI chatbot for attendee FAQs",
            "Automated post-event summaries",
            "AI-based speaker suggestions",
            "Smart agenda scheduling",
            "AI transcription of sessions",
            "Predictive lead scoring for attendees",
            "AI recommendations for ticket pricing",
            "Automated promotional content creation",
            "AI moderation of live Q&A",
            "Natural language event data queries",
            "AI analysis of sponsor ROI",
            "Intelligent identification of top engagers",
            "AI-powered event highlights videos",
            "Predictive session popularity",
            "AI-driven agenda improvement suggestions",
            "Automated session topic tagging"
          ]
        }
      ]
    }
