import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Bookings": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Booking Overview", "Today's Appointments", "Revenue Summary", "Customer Insights"]
        },
        {
          title: "Calendar",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Appointment Calendar", "Availability Settings", "Time Slots", "Recurring Appointments"]
        },
        {
          title: "Services",
          icon: <Package className="w-4 h-4" />,
          items: ["Service Catalog", "Service Pricing", "Service Duration", "Service Categories"]
        },
        {
          title: "Customers",
          icon: <Users className="w-4 h-4" />,
          items: ["Customer Directory", "Customer History", "Customer Communications", "Customer Feedback"]
        },
        {
          title: "Staff",
          icon: <UserCheck className="w-4 h-4" />,
          items: ["Staff Management", "Staff Schedules", "Staff Assignments", "Staff Performance"]
        },
        {
          title: "Payments",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["Payment Processing", "Payment Methods", "Invoicing", "Payment Reports"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Booking Analytics", "Revenue Reports", "Customer Analytics", "Performance Metrics"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable booking page",
            "Set availability",
            "Automated email reminders",
            "Appointment calendar view",
            "Embed on your website"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Two-way calendar sync",
            "Accept online payments",
            "Group & class scheduling",
            "Multi-staff management",
            "Custom intake forms"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Eliminating email back-and-forth",
            "Reducing client no-shows",
            "Preventing double-bookings",
            "Collecting payment upfront",
            "Managing a team's schedule",
            "Scheduling different service types",
            "Gathering info before a meeting",
            "Allowing clients to self-reschedule",
            "Scheduling classes or workshops",
            "Integrating booking into a website"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI suggestions for optimal meeting times",
            "Smart scheduling to minimize calendar gaps",
            "AI analysis of booking patterns",
            "Automated follow-up email suggestions",
            "AI booking chatbot for websites",
            "Predictive no-show analysis",
            "AI recommendations for service pricing",
            "Natural language booking creation",
            "AI-powered 'buffer time' suggestions",
            "Automated timezone detection",
            "AI reminders for appointment preparation",
            "Smart routing of booking requests",
            "AI-generated booking activity summaries",
            "Predictive analysis of busy periods",
            "AI suggestions for new service offerings",
            "Automated analysis of cancellation reasons",
            "AI-driven lead scoring for bookings",
            "Smart duplicate client detection",
            "AI-powered waitlist management",
            "Automated testimonial requests"
          ]
        }
      ]
    }