import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Checkout": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Payment Overview", "Transaction Stats", "Revenue Summary", "Recent Payments"]
        },
        {
          title: "Payment Pages",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["All Pages", "Published Pages", "Draft Pages", "Page Templates", "Mobile Pages"]
        },
        {
          title: "Transactions",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Transactions", "Successful Payments", "Failed Payments", "Refunds", "Chargebacks"]
        },
        {
          title: "Customers",
          icon: <Users className="w-4 h-4" />,
          items: ["Customer Database", "Payment Methods", "Customer Communications", "Purchase History"]
        },
        {
          title: "Products",
          icon: <Package className="w-4 h-4" />,
          items: ["Product Catalog", "Pricing", "Inventory Integration", "Digital Products"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Payment Analytics", "Conversion Rates", "Abandonment Analysis", "Revenue Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Payment Settings", "Gateway Configuration", "Security Settings", "Branding"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable payment templates",
            "One-time & recurring payments",
            "Collect shipping addresses",
            "Embeddable payment buttons",
            "Automatic email receipts"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Multi-currency support",
            "Major payment gateway integration",
            "Handled PCI compliance",
            "Custom domain for payment pages",
            "Dunning management"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Accepting payments without an e-commerce store",
            "Reducing cart abandonment",
            "Handling payment security & PCI compliance",
            "Automating payment receipts",
            "Setting up subscription billing",
            "Accepting international payments",
            "Keeping customers on your site to pay",
            "Recovering failed subscription payments",
            "Collecting 'pay what you want' donations",
            "Tracking sales and payment history"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered transaction fraud detection",
            "Predictive A/B testing for page designs",
            "AI-driven checkout flow optimization",
            "Smart dunning management",
            "AI recommendations for pricing",
            "Automated payment page generation",
            "Natural language sales queries",
            "AI-powered A/B testing for pages",
            "Cancellation reason sentiment analysis",
            "Predictive customer churn analysis",
            "AI-driven currency conversion advice",
            "Smart alerts for unusual activity",
            "AI-powered upsell suggestions",
            "Automated tax calculation suggestions",
            "AI-based page localization",
            "Predictive revenue forecasting",
            "AI-generated LTV insights",
            "Smart bank deposit matching",
            "AI-optimized payment retry schedules",
            "Automated high-value customer identification"
          ]
        }
      ]
    }
  