import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Cliq": {
      sections: [
        {
          title: "Chats",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["All Conversations", "Direct Messages", "Group Chats", "Starred Messages", "Message Search"]
        },
        {
          title: "Channels",
          icon: <Hash className="w-4 h-4" />,
          items: ["All Channels", "Public Channels", "Private Channels", "Channel Discovery", "Channel Settings"]
        },
        {
          title: "Teams",
          icon: <Users className="w-4 h-4" />,
          items: ["My Teams", "Team Directory", "Team Settings", "Team Analytics", "Cross-functional Teams"]
        },
        {
          title: "Calls",
          icon: <Phone className="w-4 h-4" />,
          items: ["Audio Calls", "Video Calls", "Screen Sharing", "Call History", "Conference Calls"]
        },
        {
          title: "Files",
          icon: <FileText className="w-4 h-4" />,
          items: ["Shared Files", "File Library", "Recent Files", "File Search", "Cloud Storage"]
        },
        {
          title: "Integrations",
          icon: <Zap className="w-4 h-4" />,
          items: ["App Integrations", "Bots", "Workflows", "Custom Commands", "API Access"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Emoji reactions and GIFs",
            "Do Not Disturb mode",
            "Threaded conversations",
            "Pin important messages",
            "Global search"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Integrated audio/video calls",
            "Custom bot platform",
            "Guest access for externals",
            "Company-wide announcement channels",
            "Contextual chat integrations"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Reducing internal email chains",
            "Finding past conversations",
            "Eliminating app switching for calls",
            "Making sure announcements are seen",
            "Automating routine notifications",
            "Organizing team discussions",
            "Collaborating securely with clients",
            "Managing notification overload",
            "Remembering decisions made in chat",
            "Sharing code snippets effectively"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI chat channel summarization",
            "Smart reply suggestions",
            "AI meeting scheduler",
            "Team morale sentiment analysis",
            "AI assistant for chat actions",
            "Automated call transcription",
            "AI-driven Do Not Disturb mode",
            "Predictive text for messaging",
            "AI new hire channel recommendations",
            "Smart action item extraction",
            "Natural language search",
            "Real-time multilingual translation",
            "Smart reminders for unanswered questions",
            "AI sensitive data detection",
            "Automated channel activity reports",
            "AI expert finder",
            "Smart notification prioritization",
            "AI suggestions for new channels",
            "Automated in-channel polling",
            "AI-powered 'focus mode'"
          ]
        }
      ]
    }