import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
 "CommunitySpaces": {
      sections: [
        {
          title: "Communities",
          icon: <Users className="w-4 h-4" />,
          items: ["All Communities", "My Communities", "Public Communities", "Private Communities", "Community Templates"]
        },
        {
          title: "Members",
          icon: <User className="w-4 h-4" />,
          items: ["All Members", "Member Profiles", "Member Roles", "Member Analytics", "Member Invitations"]
        },
        {
          title: "Posts & Content",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Posts", "Popular Posts", "Recent Posts", "Content Categories", "Content Moderation"]
        },
        {
          title: "Forums",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["Discussion Forums", "Forum Topics", "Forum Categories", "Forum Moderation", "Forum Analytics"]
        },
        {
          title: "Engagement",
          icon: <Heart className="w-4 h-4" />,
          items: ["Member Engagement", "Community Events", "Gamification", "Rewards System", "Engagement Analytics"]
        },
        {
          title: "Moderation",
          icon: <Shield className="w-4 h-4" />,
          items: ["Content Moderation", "User Management", "Community Guidelines", "Reporting System", "Moderation Tools"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Community Analytics", "Member Analytics", "Content Analytics", "Engagement Metrics", "Growth Analytics"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Community Settings", "Privacy Settings", "Notification Settings", "Integration Settings", "Theme Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Discussion forums",
            "User profiles",
            "Likes and comments",
            "Moderation tools",
            "Event calendar"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Public and private groups",
            "Knowledge base",
            "Gamification system",
            "App integrations",
            "Advanced analytics"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Providing a space for customer Q&A",
            "Building brand loyalty",
            "Keeping community members engaged",
            "Managing spam and bad actors",
            "Understanding trending topics",
            "Creating focused discussion areas",
            "Welcoming new members effectively",
            "Rewarding top contributors",
            "Integrating a community with a product",
            "Sharing important resources"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI suggestions for new topics",
            "Automated content moderation",
            "AI-based member matchmaking",
            "Community sentiment analysis",
            "AI chatbot for community FAQs",
            "Automated discussion summarization",
            "AI identification of community leaders",
            "Predictive member churn analysis",
            "AI content recommendations",
            "Smart duplicate post detection",
            "AI-powered 'icebreaker' questions",
            "Natural language community search",
            "AI insights into community health",
            "Automated post tagging",
            "AI-powered 'expert finder'",
            "Smart alerts for trending topics",
            "AI recommendations for event ideas",
            "Automated 'weekly digest' generation",
            "Predictive content engagement analysis",
            "AI-powered content translation"
          ]
        }
      ]
    }