import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
 "Contacts": {
      sections: [
        {
          title: "Contacts",
          icon: <Users className="w-4 h-4" />,
          items: ["All Contacts", "Add Contact", "My Contacts", "Recent Contacts", "Favorites", "Duplicates"]
        },
        {
          title: "Groups",
          icon: <Users className="w-4 h-4" />,
          items: ["Contact Groups", "Create Group", "Smart Groups", "Group Management"]
        },
        {
          title: "Lists",
          icon: <List className="w-4 h-4" />,
          items: ["Mailing Lists", "Distribution Lists", "Custom Lists", "List Management"]
        },
        {
          title: "Communication",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["Send Email", "Send SMS", "Communication History", "Templates"]
        },
        {
          title: "Import/Export",
          icon: <Upload className="w-4 h-4" />,
          items: ["Import Contacts", "Export Contacts", "Sync Settings", "Data Sources"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["General Settings", "Custom Fields", "Privacy Settings", "Sync Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Central address book",
            "Custom fields",
            "Notes on profiles",
            "Search and filter",
            "Import from CSV/Google"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Find and merge duplicates",
            "360-degree view integration",
            "Mailing list creation",
            "Team contact sharing",
            "Business card scanner"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Centralizing scattered contacts",
            "Fixing duplicate contact records",
            "Remembering details about contacts",
            "Reducing manual data entry",
            "Emailing specific groups",
            "Sharing contacts with a team",
            "Keeping contact info updated",
            "Finding a specific contact easily",
            "Migrating contacts from other systems",
            "Storing extra, non-standard info"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered data enrichment",
            "Automated duplicate detection",
            "AI follow-up suggestions",
            "Smart contact grouping",
            "AI parsing of email signatures",
            "Predictive contact value analysis",
            "AI 'relationship health' score",
            "Natural language contact search",
            "AI data standardization",
            "Automated activity logging",
            "AI identification of decision-makers",
            "Smart alerts for job changes",
            "AI-powered photo recognition",
            "Automated contact tagging",
            "AI social connection suggestions",
            "Predictive lead scoring",
            "AI chatbot for contact lookups",
            "Smart 'keep in touch' reminders",
            "AI insights into your network",
            "Automated profile creation"
          ]
        }
      ]
    }