import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
    "Contracts": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Contract Overview", "Recent Activity", "Pending Actions", "Contract Analytics", "Quick Stats", "Contract Metrics"]
        },
        {
          title: "Contracts",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Contracts", "Active Contracts", "Draft Contracts", "Expired Contracts", "Archived Contracts", "Executed Contracts", "Templates", "My Contracts", "Recently Created", "Recently Modified"]
        },
        {
          title: "Templates",
          icon: <Bookmark className="w-4 h-4" />,
          items: ["Contract Templates", "Clause Library", "Standard Terms", "Custom Templates", "Template Categories", "Template Builder"]
        },
        {
          title: "Workflow",
          icon: <Zap className="w-4 h-4" />,
          items: ["Approval Workflows", "Review Process", "Signature Workflows", "Automated Actions", "Workflow Builder"]
        },
        {
          title: "Compliance",
          icon: <Shield className="w-4 h-4" />,
          items: ["Compliance Tracking", "Regulatory Requirements", "Audit Trail", "Risk Assessment", "Compliance Reports"]
        },
        {
          title: "Reporting",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Contract Reports", "Performance Analytics", "Renewal Reports", "Compliance Reports", "Custom Reports", "Performance Reports", "Risk Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Contract Settings", "Workflow Settings", "User Management", "Integration Settings", "Security Settings"]
        },
        {
          title: "Approval",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Approval Workflows", "Pending Approvals", "Approved Contracts", "Rejected Contracts", "Approval History"]
        },
        {
          title: "Legal Review",
          icon: <Scale className="w-4 h-4" />,
          items: ["Legal Review Queue", "Review Comments", "Legal Approved", "Legal Rejected", "Review History"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Central contract repository",
            "Contract templates",
            "Version control",
            "Status dashboard",
            "Full-text search"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated approval workflows",
            "E-signature integration",
            "Automated key date reminders",
            "Pre-approved clause library",
            "Advanced risk analytics"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Finding contracts easily",
            "Speeding up contract approvals",
            "Never missing a renewal date",
            "Using correct legal language",
            "Understanding contract risks",
            "Automating contract creation",
            "Collaborating on drafts",
            "Getting signatures efficiently",
            "Ensuring policy compliance",
            "Onboarding new team members"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered contract review",
            "Automated key term extraction",
            "AI suggestions for clauses",
            "Predictive negotiation time analysis",
            "Natural language contract search",
            "AI-powered document summarization",
            "Smart compliance alerts",
            "AI-driven draft comparison",
            "Automated approval routing",
            "AI chatbot for contract status",
            "Predictive renewal likelihood analysis",
            "AI recommendations for negotiation",
            "Smart detection of ambiguous language",
            "Automated renewal document generation",
            "AI-powered contract 'risk score'",
            "Negotiation comment sentiment analysis",
            "AI suggestions for language improvement",
            "Automated obligation-to-task mapping",
            "AI 'what-if' analysis for terms",
            "Smart discovery of related contracts"
          ]
        }
      ]
    }