import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"DataPrep": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Data Overview", "Processing Stats", "Recent Datasets", "Quick Actions"]
        },
        {
          title: "Datasets",
          icon: <Database className="w-4 h-4" />,
          items: ["My Datasets", "Shared Datasets", "Data Sources", "Import Data"]
        },
        {
          title: "Preparation",
          icon: <Filter className="w-4 h-4" />,
          items: ["Data Cleaning", "Transform Data", "Merge Datasets", "Data Validation"]
        },
        {
          title: "Recipes",
          icon: <Code className="w-4 h-4" />,
          items: ["Transformation Recipes", "Recipe Templates", "Custom Functions", "Recipe History"]
        },
        {
          title: "Export",
          icon: <Download className="w-4 h-4" />,
          items: ["Export Data", "Schedule Exports", "Export Formats", "Data Publishing"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["General Settings", "Data Sources", "Performance Settings", "Security"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Import data from various sources",
            "Visual data transformation",
            "Library of transform functions",
            "Data quality monitoring",
            "Export cleaned data"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated data pipelines",
            "Smart data blending",
            "Data catalog for governance",
            "Advanced data quality rules",
            "Team collaboration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Cleaning messy and inconsistent data",
            "Automating data prep for BI tools",
            "Combining data from different systems",
            "Enabling self-service data prep",
            "Ensuring ongoing data quality",
            "Understanding new datasets quickly",
            "Finding and trusting the right data",
            "Transforming data without code",
            "Migrating data between systems",
            "Collaborating on data prep tasks"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered data cleaning suggestions",
            "Automated data type detection",
            "AI recommendations for joining data",
            "Smart duplicate record detection",
            "AI-powered data enrichment",
            "Natural language data transformation",
            "AI-driven data quality scoring",
            "Predictive data pipeline analytics",
            "AI-based anomaly detection in data",
            "Smart parsing of unstructured data",
            "AI suggestions for validation rules",
            "Automated data catalog generation",
            "AI recommendations for data security",
            "Smart pattern recognition",
            "AI-assisted expression writing",
            "Predictive data quality alerts",
            "AI 'what-if' analysis for transforms",
            "Automated schema mapping",
            "AI-driven data lineage analysis",
            "Smart suggestions for pipeline optimization"
          ]
        }
      ]
    }