import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Desk": {
      sections: [
        {
          title: "Home",
          icon: <Home className="w-4 h-4" />,
          items: ["The HQ", "My Dashboard", "Team Dashboard", "Getting Started", "Recent Activity"]
        },
        {
          title: "Tickets",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["My Tickets", "All Tickets", "Ticket Views", "Blueprints", "Assignment Rules", "Escalation Rules", "Time Tracking"]
        },
        {
          title: "Contacts",
          icon: <Users className="w-4 h-4" />,
          items: ["Contacts", "Accounts", "Contact Views", "Account Views"]
        },
        {
          title: "Knowledge Base",
          icon: <BookOpen className="w-4 h-4" />,
          items: ["Articles", "Categories", "Community Forums", "Help Center", "ASAP", "Multilingual Support"]
        },
        {
          title: "Channels",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["Email Integration", "Live Chat", "Phone Integration", "Social Media", "WhatsApp Business", "Web Forms"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["The HQ Dashboard", "Ticket Status Dashboard", "Agent Performance", "Customer Satisfaction", "Custom Dashboards"]
        },
        {
          title: "Reports",
          icon: <FileText className="w-4 h-4" />,
          items: ["Standard Reports", "Custom Reports", "Scheduled Reports", "Performance Metrics", "Trend Analysis"]
        },
        {
          title: "AI & Automation",
          icon: <Bot className="w-4 h-4" />,
          items: ["Zia AI Assistant", "Sentiment Analysis", "Answer Bot", "Workflows", "Macros", "Custom Functions"]
        },
        {
          title: "Setup",
          icon: <Settings className="w-4 h-4" />,
          items: ["Users & Roles", "Departments", "Products", "Custom Fields", "Layouts", "Email Templates", "Integrations", "Extensions"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Canned responses",
            "Customizable ticket status",
            "Agent collision detection",
            "Merge duplicate tickets",
            "Internal notes on tickets"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Multi-channel support inbox",
            "Advanced workflow automation",
            "Customizable self-service portal",
            "SLA management & reporting",
            "Integrated telephony"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Deflecting tickets with a knowledge base",
            "Ensuring consistent answers",
            "Automating ticket assignment",
            "Managing urgent issues with SLAs",
            "Tracking team performance",
            "Providing 24/7 support with chatbots",
            "Viewing unified customer history",
            "Measuring customer satisfaction",
            "Integrating with CRM & bug trackers",
            "Onboarding new agents quickly"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI assistant for agents (Zia)",
            "Ticket sentiment analysis",
            "AI-powered auto-tagging",
            "Answer Bot for instant responses",
            "Predictive ticket volume forecasting",
            "AI suggestions for new articles",
            "Intelligent ticket summarization",
            "AI identification of trending issues",
            "Automated language translation",
            "AI-powered agent coaching",
            "Smart routing to best-skilled agent",
            "Predictive customer churn risk",
            "AI-generated response suggestions",
            "Voice-to-text call transcription",
            "AI analysis of CSAT scores",
            "Automated spam/threat detection",
            "AI-driven upsell recommendations",
            "Natural language help desk search",
            "AI anomaly detection for SLA breaches",
            "Automated ticket categorization"
          ]
        }
      ]
    }