import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Domains": {
      sections: [
        {
          title: "Domains",
          icon: <Globe className="w-4 h-4" />,
          items: ["All Domains", "Active Domains", "Expired Domains", "Pending Domains", "Domain Search", "Domain Transfer"]
        },
        {
          title: "DNS Management",
          icon: <Server className="w-4 h-4" />,
          items: ["DNS Records", "A Records", "CNAME Records", "MX Records", "TXT Records", "DNS Analytics"]
        },
        {
          title: "SSL Certificates",
          icon: <Lock className="w-4 h-4" />,
          items: ["SSL Certificates", "Certificate Installation", "Certificate Renewal", "Wildcard SSL", "SSL Analytics"]
        },
        {
          title: "Website Builder",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Build Website", "Website Templates", "Landing Pages", "Website Analytics", "Mobile Optimization"]
        },
        {
          title: "Email Setup",
          icon: <Mail className="w-4 h-4" />,
          items: ["Email Accounts", "Email Forwarding", "Email Hosting", "Email Security", "Email Analytics"]
        },
        {
          title: "WHOIS & Privacy",
          icon: <Eye className="w-4 h-4" />,
          items: ["WHOIS Information", "Domain Privacy", "Contact Information", "Privacy Protection", "Domain Lock"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Domain Settings", "DNS Settings", "Security Settings", "Billing Settings", "Renewal Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Domain name search",
            "DNS record management",
            "Domain forwarding",
            "WHOIS privacy",
            "Domain dashboard"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Domain transfers",
            "Bulk domain management",
            "Integrated email setup",
            "Integrated website builder",
            "SSL certificate management"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Getting a custom domain name",
            "Pointing a domain to a host",
            "Getting a professional email address",
            "Protecting personal info",
            "Avoiding domain expiration",
            "Managing many domains",
            "Securing a website with SSL",
            "Connecting a domain to any platform",
            "Moving a domain from another provider",
            "Creating subdomains"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered domain name suggestions",
            "Predictive domain value analysis",
            "AI trademark infringement detection",
            "Smart domain extension suggestions",
            "AI-powered DNS configuration checker",
            "Automated DNS record generation",
            "AI monitoring for domain spoofing",
            "Natural language DNS management",
            "AI recommendations for portfolio buys",
            "Smart expiration alerts",
            "AI-powered brand protection",
            "Automated email forwarding suggestions",
            "AI insights into domain traffic",
            "Smart DNS misconfiguration detection",
            "AI 'domain portfolio' health score",
            "Automated email deliverability suggestions",
            "AI negotiation assistant",
            "Predictive domain popularity analysis",
            "AI chatbot for domain support",
            "Smart alerts for desired domains"
          ]
        }
      ]
    }