import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"eProtect": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Security Overview", "Threat Dashboard", "Email Analytics", "Protection Status", "Recent Activity", "Threat Summary", "Email Statistics", "Quick Actions"]
        },
        {
          title: "Security",
          icon: <Shield className="w-4 h-4" />,
          items: ["Threat Protection", "Anti-spam", "Anti-virus", "Email Encryption", "Security Policies", "Spam Filter", "Phishing Protection", "Malware Detection"]
        },
        {
          title:. "Archive",
          icon: <Archive className="w-4 h-4" />,
          items: ["Email Archive", "Archived Messages", "Search Archive", "Archive Policies", "Data Retention", "Legal Hold"]
        },
        {
          title: "Policies",
          icon: <FileText className="w-4 h-4" />,
          items: ["Security Policies", "Compliance Policies", "Content Filtering", "Data Loss Prevention", "Policy Management"]
        },
        {
          title: "Compliance",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Compliance Reports", "Audit Logs", "Regulatory Compliance", "Legal Hold", "eDiscovery"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Security Reports", "Archive Reports", "Compliance Reports", "Threat Reports", "Custom Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Security Settings", "Archive Settings", "Policy Settings", "User Management", "Integration Settings", "Filter Settings", "Admin Settings"]
        },
        {
          title: "Quarantine",
          icon: <XCircle className="w-4 h-4" />,
          items: ["Quarantined Emails", "Spam Quarantine", "Virus Quarantine", "Release Queue", "False Positives"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Anti-spam & anti-virus",
            "Email quarantine",
            "Allow/block lists",
            "Email traffic dashboard",
            "Content filtering"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Advanced Threat Protection",
            "Searchable email archive",
            "Data Loss Prevention (DLP)",
            "Email encryption",
            "eDiscovery"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Stopping spam from flooding inboxes",
            "Preventing employees from clicking phishing links",
            "Retaining all emails for compliance",
            "Finding specific emails for legal cases",
            "Preventing sensitive data leaks",
            "Handling legitimate emails marked as spam",
            "Sending sensitive information securely",
            "Understanding email-based threats",
            "Stopping business email compromise attacks",
            "Recovering deleted emails for audits"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered phishing detection",
            "Behavioral analysis for account compromise",
            "AI-based malicious image detection",
            "Predictive email threat analytics",
            "AI security policy recommendations",
            "Natural language eDiscovery search",
            "AI-powered email classification",
            "Smart alerts for unusual email activity",
            "AI sentiment analysis for threat detection",
            "Automated sensitive data redaction",
            "AI-powered impersonation detection",
            "Smart suggestions for DLP rules",
            "AI-driven email header analysis",
            "Automated security incident reports",
            "AI-powered user risk scoring",
            "Admin support chatbot for incidents",
            "Predictive analysis of phishing targets",
            "AI-based quarantine management",
            "Smart grouping of related threat events",
            "AI-powered threat intelligence"
          ]
        }
      ]
    }