import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

    "Finances": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Financial Dashboard", "Cash Flow", "P&L Overview", "Key Metrics", "Budget vs Actual"]
        },
        {
          title: "Transactions",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["All Transactions", "Income", "Expenses", "Transfers", "Recurring Transactions"]
        },
        {
          title: "Accounts",
          icon: <Building2 className="w-4 h-4" />,
          items: ["Chart of Accounts", "Bank Accounts", "Credit Cards", "Assets", "Liabilities"]
        },
        {
          title: "Budgeting",
          icon: <Target className="w-4 h-4" />,
          items: ["Budget Planning", "Budget vs Actual", "Variance Analysis", "Budget Categories", "Forecasting"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Financial Reports", "P&L Statement", "Balance Sheet", "Cash Flow Statement", "Custom Reports"]
        },
        {
          title: "Reconciliation",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Bank Reconciliation", "Credit Card Reconciliation", "Account Matching", "Reconciliation History"]
        },
        {
          title: "Tax Management",
          icon: <Calculator className="w-4 h-4" />,
          items: ["Tax Categories", "Tax Reports", "Tax Filing", "Deductions", "Tax Planning"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["General Settings", "Account Setup", "Currency Settings", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Unified financial dashboard",
            "Create and send invoices",
            "Track expenses & receipts",
            "Connect bank accounts",
            "Simple chart of accounts"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Double-entry accounting",
            "Automated bank reconciliation",
            "Sales & purchase orders",
            "Integrated inventory tracking",
            "Comprehensive financial reporting"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Getting a clear view of financial health",
            "Automating bank transaction entry",
            "Getting paid by clients on time",
            "Managing inventory and COGS",
            "Preparing statements for tax time",
            "Tracking employee expenses",
            "Creating and tracking budgets",
            "Managing the full quote-to-cash process",
            "Complying with sales tax laws",
            "Collaborating with an accountant"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered cash flow forecasting",
            "Automated expense categorization",
            "AI transaction anomaly detection",
            "Smart reconciliation suggestions",
            "AI recommendations for financial health",
            "Predictive customer payment analysis",
            "AI chatbot for financial questions",
            "Automated vendor bill data extraction",
            "AI-driven spending pattern insights",
            "Natural language report generation",
            "AI-powered audit assistance",
            "Smart alerts for low balances",
            "AI inventory reorder point suggestions",
            "Predictive budgeting and forecasting",
            "AI analysis of profitability",
            "Automated duplicate bill detection",
            "AI chart of accounts optimization",
            "Smart payment-to-invoice matching",
            "AI-generated financial summaries",
            "Predictive analysis of late payments"
          ]
        }
      ]
    }