import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Flow": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Automation Overview", "Active Workflows", "Execution Stats", "Recent Activities"]
        },
        {
          title: "Workflows",
          icon: <GitBranch className="w-4 h-4" />,
          items: ["My Workflows", "Shared Workflows", "Workflow Templates", "Draft Workflows"]
        },
        {
          title: "Builder",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Visual Builder", "Triggers", "Actions", "Conditions", "Functions"]
        },
        {
          title: "Executions",
          icon: <PlayCircle className="w-4 h-4" />,
          items: ["Execution History", "Failed Executions", "Scheduled Executions", "Real-time Monitoring"]
        },
        {
          title: "Connections",
          icon: <Link2 className="w-4 h-4" />,
          items: ["App Connections", "API Integrations", "Webhooks", "Custom Connections"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Account Settings", "Team Management", "Usage Limits", "Security Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Visual workflow builder",
            "Pre-built app connectors",
            "Simple triggers and actions",
            "Workflow execution history",
            "On/off toggle for flows"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Multi-step flows with logic",
            "Custom scripting with Deluge",
            "Webhook support",
            "Scheduled flows",
            "Team collaboration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Automating data syncing between apps",
            "Consolidating important notifications",
            "Automating multi-app processes",
            "Eliminating repetitive data entry",
            "Connecting apps that don't integrate",
            "Automating manual business processes",
            "Handling complex business logic",
            "Creating a central activity log",
            "Automating onboarding workflows",
            "Distributing form data to multiple apps"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered workflow suggestions",
            "AI-based field mapping",
            "Natural language flow creation",
            "AI-driven error handling",
            "Predictive workflow success analysis",
            "AI-powered data transformation",
            "Smart infinite loop detection",
            "AI recommendations for optimization",
            "Automated flow documentation",
            "AI-powered webhook data parsing",
            "Sentiment analysis for workflow triggers",
            "AI content summarization for notifications",
            "Smart flow scheduling",
            "AI pattern recognition for new automations",
            "Automated flow testing",
            "AI-powered flow debugger",
            "Smart data validation in flows",
            "AI-generated Deluge scripts",
            "Predictive API cost analysis",
            "AI 'what-if' analysis for logic"
          ]
        }
      ]
    }