import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Inventory": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Inventory Overview", "Stock Levels", "Low Stock Alerts", "Recent Transactions"]
        },
        {
          title: "Items",
          icon: <Package className="w-4 h-4" />,
          items: ["All Items", "Item Groups", "Composite Items", "Serial Numbers", "Item Images"]
        },
        {
          title: "Stock",
          icon: <Storage className="w-4 h-4" />,
          items: ["Stock Summary", "Stock Adjustments", "Stock Transfers", "Physical Count", "Reorder Points"]
        },
        {
          title: "Orders",
          icon: <FileText className="w-4 h-4" />,
          items: ["Sales Orders", "Purchase Orders", "Order Fulfillment", "Backorders", "Order History"]
        },
        {
          title: "Warehouses",
          icon: <Building2 className="w-4 h-4" />,
          items: ["Warehouse Management", "Locations", "Bin Management", "Warehouse Transfers"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Inventory Reports", "Valuation Reports", "Movement Reports", "Aging Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["General Settings", "Units of Measure", "Categories", "Preferences"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Low Stock Alerts",
            "Barcode/QR Code Generation",
            "Quick Stock Adjustment",
            "Item Image Upload",
            "Basic Stock Count Sheet"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Multi-Warehouse Management",
            "Serial/Batch Number Tracking",
            "Automated Reordering",
            "Landed Cost Tracking",
            "Kitting & Bundling"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Automated Reorder Points",
            "Inventory Turnover Reports",
            "Cycle Counting & Barcode Scanning",
            "Real-time Multi-channel Sync",
            "Expiration Date Management",
            "Picklists & Packing Slips",
            "Streamlined Returns Workflow",
            "Detailed Inventory Audit Trail",
            "Landed Cost Valuation",
            "Warehouse Bin Location Management"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-Powered Demand Forecasting",
            "Supplier Performance Scorecards",
            "Dynamic Reorder Point Suggestions",
            "Automated Dead Stock Identification",
            "Smart Replenishment Recommendations",
            "Warehouse Layout Optimization",
            "Image Recognition for Item ID",
            "Automated Quality Control Analysis",
            "Natural Language Inventory Queries",
            "Predictive Inbound Shipping Alerts",
            "AI-Powered Stock Level Optimization",
            "Automated Purchase Order Creation",
            "Predictive Sales Forecasting",
            "Intelligent Supplier Selection",
            "AI-driven Warehouse Slotting",
            "Automated Stock Transfer Suggestions",
            "Smart Barcode Scanning",
            "AI-powered Quality Control",
            "Personalized Product Recommendations",
            "Automated Returns Processing"
          ]
        }
      ]
    },