import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Mail": {
      sections: [
        {
          title: "Compose",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["New Email", "Templates", "Signatures", "Scheduled Send", "Rich Text Editor"]
        },
        {
          title: "Inbox",
          icon: <Inbox className="w-4 h-4" />,
          items: ["All Mail", "Unread", "Important", "Starred", "With Attachments"]
        },
        {
          title: "Drafts",
          icon: <FileText className="w-4 h-4" />,
          items: ["Draft Emails", "Auto-saved Drafts", "Scheduled Emails"]
        },
        {
          title: "Outbox",
          icon: <Send className="w-4 h-4" />,
          items: ["Pending Send", "Scheduled Emails", "Failed Sends"]
        },
        {
          title: "Sent",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Sent Mail", "Delivery Reports", "Read Receipts"]
        },
        {
          title: "Spam",
          icon: <Shield className="w-4 h-4" />,
          items: ["Spam Emails", "Blocked Senders", "Spam Settings"]
        },
        {
          title: "Trash",
          icon: <Archive className="w-4 h-4" />,
          items: ["Deleted Emails", "Empty Trash", "Recover Emails"]
        },
        {
          title: "Folders",
          icon: <Folder className="w-4 h-4" />,
          items: ["Custom Folders", "Shared Folders", "System Folders", "Folder Settings"]
        },
        {
          title: "Tags",
          icon: <Tag className="w-4 h-4" />,
          items: ["Color Tags", "Custom Tags", "Tag Management"]
        },
        {
          title: "Views",
          icon: <Eye className="w-4 h-4" />,
          items: ["Unread View", "Archived View", "Attachment View", "Conversation View"]
        },
        {
          title: "Streams",
          icon: <Users className="w-4 h-4" />,
          items: ["Team Streams", "Group Collaboration", "Stream Settings"]
        },
        {
          title: "Zoho Apps",
          icon: <Grid className="w-4 h-4" />,
          items: ["Calendar", "Contacts", "Tasks", "Notes", "Bookmarks", "Resources", "eArchive"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Undo send",
            "Email templates",
            "Snooze emails",
            "Customizable swipe actions",
            "Out of Office auto-responder"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "End-to-end email encryption",
            "Integrated productivity suite",
            "eDiscovery and email archiving",
            "Team collaboration via Streams",
            "Full offline mode access"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Managing an overflowing inbox",
            "Remembering to follow up",
            "Scheduling meetings efficiently",
            "Fighting spam and phishing",
            "Collaborating on documents",
            "Finding old emails and attachments",
            "Managing multiple email accounts",
            "Sending large file attachments",
            "Migrating from other providers",
            "Getting a custom domain email"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered email prioritization",
            "Smart reply suggestions",
            "AI-based email summarization",
            "Nudge reminders for follow-ups",
            "AI-driven smart folders",
            "Email sentiment analysis",
            "Natural language email search",
            "Automated task/event extraction",
            "AI grammar and tone checker",
            "Predictive text composition",
            "Self-learning spam filter",
            "Smart notification management",
            "AI-driven contact suggestions",
            "Automated email translation",
            "AI-powered phishing detection",
            "Voice commands for email",
            "AI scheduling assistant",
            "Automated follow-up suggestions",
            "AI insights into email habits",
            "Smart attachment management"
          ]
        }
      ]
    },