import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

    "MarketingHub": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Marketing Dashboard", "Campaign Performance", "Lead Overview", "ROI Analytics"]
        },
        {
          title: "Campaigns",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["All Campaigns", "Email Campaigns", "SMS Campaigns", "Social Campaigns", "Multi-channel Campaigns"]
        },
        {
          title: "Lead Management",
          icon: <Users className="w-4 h-4" />,
          items: ["All Leads", "Lead Scoring", "Lead Nurturing", "Lead Qualification", "Lead Distribution"]
        },
        {
          title: "Content",
          icon: <FileText className="w-4 h-4" />,
          items: ["Content Library", "Email Templates", "Landing Pages", "Forms", "Social Content"]
        },
        {
          title: "Automation",
          icon: <Zap className="w-4 h-4" />,
          items: ["Marketing Workflows", "Lead Nurturing", "Drip Campaigns", "Behavioral Triggers", "A/B Testing"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Campaign Analytics", "Lead Analytics", "Revenue Analytics", "Attribution Analysis", "Custom Reports"]
        },
        {
          title: "Integration",
          icon: <Link2 className="w-4 h-4" />,
          items: ["CRM Integration", "Social Media", "Web Analytics", "Email Services", "Third-party Apps"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Account Settings", "Team Management", "Brand Settings", "API Configuration"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Drag-and-drop builders",
            "Website lead capture forms",
            "Email A/B testing",
            "Basic lead scoring",
            "Website visitor tracking"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Visual journey builder",
            "Multi-channel communication",
            "Advanced lead nurturing",
            "Behavior-triggered campaigns",
            "Revenue attribution reporting"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Automating lead follow-up",
            "Sending targeted messages",
            "Identifying sales-ready leads",
            "Proving marketing ROI",
            "Creating a consistent multi-channel experience",
            "Converting website visitors",
            "Aligning marketing and sales",
            "Improving email engagement",
            "Generating high-quality leads",
            "Understanding the customer journey"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered predictive segmentation",
            "AI 'next best action' recommendations",
            "AI-generated email copy",
            "Predictive lead scoring",
            "AI-powered send time optimization",
            "Automated journey optimization",
            "AI-driven content recommendations",
            "Predictive churn analysis",
            "AI-assisted campaign creation",
            "Natural language analytics queries",
            "AI anomaly detection in campaigns",
            "Automated A/B test winner selection",
            "AI-driven website personalization",
            "Smart channel recommendations",
            "AI analysis of competitor campaigns",
            "Predictive lead generation forecasting",
            "AI-powered 'lookalike' audiences",
            "Automated asset suggestions",
            "AI insights into customer behavior",
            "Smart marketing budget allocation"
          ]
        }
      ]
    },