import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"MDM": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Device Overview", "Enrollment Stats", "Compliance Status", "Recent Activities"]
        },
        {
          title: "Devices",
          icon: <Smartphone className="w-4 h-4" />,
          items: ["All Devices", "iOS Devices", "Android Devices", "Windows Devices", "Device Groups"]
        },
        {
          title: "Enrollment",npm run dev
          icon: <UserCheck className="w-4 h-4" />,
          items: ["Device Enrollment", "Enrollment Policies", "Enrollment Templates", "Bulk Enrollment"]
        },
        {
          title: "Policies",
          icon: <FileText className="w-4 h-4" />,
          items: ["Device Policies", "App Policies", "Security Policies", "Compliance Policies"]
        },
        {
          title: "Applications",
          icon: <Package className="w-4 h-4" />,
          items: ["App Management", "App Distribution", "App Store", "Enterprise Apps"]
        },
        {
          title: "Security",
          icon: <Shield className="w-4 h-4" />,
          items: ["Device Security", "Remote Actions", "Location Tracking", "Threat Protection"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Device Reports", "Compliance Reports", "Security Reports", "Usage Reports"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Device inventory view",
            "Enforce passcode policy",
            "Distribute Wi-Fi profiles",
            "View device info",
            "Remotely lock a device"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Remote device wipe",
            "Enterprise app store",
            "Kiosk mode",
            "Automated device enrollment",
            "Compliance rule enforcement"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Securing lost or stolen phones",
            "Managing 'Bring Your Own Device' (BYOD)",
            "Setting up new company phones in bulk",
            "Distributing required apps to devices",
            "Securing Wi-Fi connections",
            "Preventing malicious app installs",
            "Tracking company-owned devices",
            "Locking down single-purpose devices",
            "Proving device security compliance",
            "Retiring a device securely"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered malware detection",
            "Predictive battery health analysis",
            "AI security policy recommendations",
            "Behavioral analytics for threat detection",
            "Smart compliance alerts",
            "AI-powered geofencing suggestions",
            "Automated app risk classification",
            "Natural language admin search",
            "AI optimization of app updates",
            "Predictive data usage analysis",
            "AI-powered device troubleshooting",
            "Smart device grouping",
            "AI analysis of app permissions",
            "Automated enrollment workflow suggestions",
            "AI-powered 'lost device' mode",
            "Predictive device failure analysis",
            "AI recommendations for app blacklists",
            "Automated executive security reports",
            "AI chatbot for employee self-service",
            "Smart SIM card change detection"
          ]
        }
      ]
    }