import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Meeting": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Meeting Overview", "Upcoming Meetings", "Recent Recordings", "Usage Analytics"]
        },
        {
          title: "Meetings",
          icon: <Video className="w-4 h-4" />,
          items: ["Start Meeting", "Schedule Meeting", "Join Meeting", "Meeting History", "Recurring Meetings"]
        },
        {
          title: "Webinars",
          icon: <Users className="w-4 h-4" />,
          items: ["Host Webinar", "Webinar Registration", "Attendee Management", "Webinar Analytics"]
        },
        {
          title: "Recordings",
          icon: <PlayCircle className="w-4 h-4" />,
          items: ["All Recordings", "Cloud Recordings", "Local Recordings", "Recording Settings"]
        },
        {
          title: "Room Management",
          icon: <Monitor className="w-4 h-4" />,
          items: ["Meeting Rooms", "Room Booking", "Room Equipment", "Room Analytics"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Meeting Settings", "Security Settings", "Integration Settings", "User Management"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable meeting URLs",
            "Virtual backgrounds",
            "In-meeting chat",
            "Raise hand feature",
            "Password protection"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "HD video conferencing",
            "Screen sharing with annotation",
            "Cloud recording & transcripts",
            "Webinar capabilities",
            "Calendar integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Avoiding software installation",
            "Remembering what was discussed",
            "Preventing meeting interruptions",
            "Collaborating on documents live",
            "Securing confidential meetings",
            "Scheduling across time zones",
            "Hiding distracting backgrounds",
            "Presenting to large audiences",
            "Joining meetings on the go",
            "Following up with attendees"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI meeting summarization",
            "Real-time transcription",
            "AI noise cancellation",
            "Smart camera framing",
            "AI attendee engagement analysis",
            "Zia virtual meeting assistant",
            "AI-powered chat translation",
            "Meeting sentiment analysis",
            "AI-generated meeting agendas",
            "Predictive attendance analytics",
            "Smart 'overtime' alerts",
            "AI meeting productivity suggestions",
            "Automated recording chapters",
            "AI key moment highlighting",
            "Natural language voice commands",
            "AI bandwidth optimization",
            "Smart speaker identification",
            "AI 'catch me up' feature",
            "Automated recurring meeting scheduling",
            "AI virtual background generation"
          ]
        }
      ]
    }