import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Motivator": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Performance Overview", "Team Standings", "Achievement Gallery", "Recent Activities"]
        },
        {
          title: "Games",
          icon: <Target className="w-4 h-4" />,
          items: ["Active Games", "Game Templates", "Custom Games", "Game History", "Game Settings"]
        },
        {
          title: "Leaderboards",
          icon: <TrendingUp className="w-4 h-4" />,
          items: ["Top Performers", "Team Rankings", "Individual Scores", "Period Comparisons"]
        },
        {
          title: "Achievements",
          icon: <Star className="w-4 h-4" />,
          items: ["Badges", "Rewards", "Milestones", "Recognition Wall", "Achievement History"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Performance Metrics", "Engagement Reports", "ROI Analysis", "Behavioral Insights"]
        },
        {
          title: "Setup",
          icon: <Settings className="w-4 h-4" />,
          items: ["KPI Configuration", "Team Setup", "Reward System", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable leaderboard themes",
            "Achievement sound effects",
            "Peer recognition 'kudos' feature",
            "Personal best notifications",
            "Mobile goal-tracking widget"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Integrate with any CRM data point",
            "TV channel for office screens",
            "Complex contest builder",
            "Fantasy sports-style competitions",
            "Rewards fulfillment system"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Boosting low team morale",
            "Focusing reps on key metrics",
            "Preventing negative competition",
            "Visualizing real-time performance",
            "Making sales meetings engaging",
            "Motivating through long sales cycles",
            "Recognizing non-sales contributions",
            "Speeding up new rep onboarding",
            "Simplifying complex sales data",
            "Automating reward fulfillment"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered personalized goals",
            "Predictive motivation analysis",
            "AI-driven contest recommendations",
            "Smart milestone alerts",
            "AI sales coach for reps",
            "Automated balanced team generation",
            "Team morale sentiment analysis",
            "AI recognition of 'unsung heroes'",
            "Predictive KPI forecasting",
            "AI-generated contest summaries",
            "Natural language ranking queries",
            "AI recommendations for rewards",
            "Automated performance anomaly detection",
            "AI skill gap analysis",
            "Personalized 'power-up' suggestions",
            "AI dynamic difficulty adjustment",
            "Predictive contest effectiveness modeling",
            "Automated peer recognition suggestions",
            "AI-generated contest 'hype' messages",
            "Smart matchmaking for sales challenges"
          ]
        }
      ]
    },