import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Office Integrator": {
      sections: [
        {
          title: "Documents",
          icon: <FileText className="w-4 h-4" />,
          items: ["Recent Documents", "All Documents", "Shared Documents", "Favorites", "Document Templates"]
        },
        {
          title: "Editor",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Word Processor", "Spreadsheet Editor", "Presentation Editor", "Form Builder", "Document Viewer"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Real-time Editing", "Comments & Reviews", "Version History", "Share Settings", "Team Workspaces"]
        },
        {
          title: "Templates",
          icon: <Bookmark className="w-4 h-4" />,
          items: ["Document Templates", "Form Templates", "Report Templates", "Letter Templates", "Custom Templates"]
        },
        {
          title: "Integration",
          icon: <Link2 className="w-4 h-4" />,
          items: ["API Integration", "Embed Options", "Third-party Apps", "Webhooks", "Developer Tools"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Editor Preferences", "Format Settings", "Security Options", "Export Options", "Admin Panel"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Embeddable document viewer",
            "Document creation API",
            "Real-time collaboration API",
            "Import/Export APIs",
            "Formatting APIs"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "White-labeled embedded editor",
            "Co-branding options",
            "Custom authentication integration",
            "Document merge API",
            "Secure, isolated customer environments"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Adding document editing to your app",
            "Keeping users within your application",
            "Generating bulk documents",
            "Enabling real-time collaboration",
            "Handling multiple document formats",
            "Maintaining a consistent brand experience",
            "Managing user access to documents",
            "Providing a 'view-only' mode",
            "Automating report creation",
            "Using your own file storage"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI writing assistant API",
            "AI document summarization API",
            "AI grammar check API",
            "Smart template filling API",
            "AI document comparison API",
            "Automated document classification API",
            "AI-powered data extraction API",
            "Document sentiment analysis API",
            "AI readability analysis API",
            "Sensitive data (PII) detection API",
            "AI document translation API",
            "Automated presentation generation API",
            "AI chart generation API",
            "Smart form autofill API",
            "AI-powered document search API",
            "Predictive text API",
            "AI template recommendation API",
            "Automated keyword extraction API",
            "AI spreadsheet anomaly detection API",
            "Smart document Q&A API"
          ]
        }
      ]
    },