import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"PageSense": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Optimization Overview", "Active Experiments", "Conversion Insights", "Performance Summary", "Quick Stats"]
        },
        {
          title: "A/B Testing",
          icon: <Target className="w-4 h-4" />,
          items: ["Create A/B Test", "Running Tests", "Test Results", "Statistical Significance", "Winner Selection", "Test Templates", "Multivariate Testing"]
        },
        {
          title: "Heatmaps",
          icon: <MousePointer className="w-4 h-4" />,
          items: ["Click Heatmaps", "Scroll Heatmaps", "Move Heatmaps", "Attention Heatmaps", "Mobile Heatmaps", "Page Comparison", "Element Analysis"]
        },
        {
          title: "Session Recordings",
          icon: <PlayCircle className="w-4 h-4" />,
          items: ["User Sessions", "Visitor Recordings", "Funnel Analysis", "Error Tracking", "Form Analytics", "Conversion Paths", "Drop-off Analysis"]
        },
        {
          title: "Funnels",
          icon: <TrendingDown className="w-4 h-4" />,
          items: ["Funnel Builder", "Conversion Funnel", "Drop-off Points", "Funnel Optimization", "Goal Tracking"]
        },
        {
          title: "Polls & Surveys",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["On-page Polls", "Exit-Intent Surveys", "Feedback Widgets", "NPS Surveys", "User Voice", "Custom Questions"]
        },
        {
          title: "Form Analytics",
          icon: <FileText className="w-4 h-4" />,
          items: ["Form Analysis", "Field Analytics", "Form Drop-offs", "Completion Rates", "Form Optimization"]
        },
        {
          title: "Goals & Events",
          icon: <Flag className="w-4 h-4" />,
          items: ["Goal Setup", "Conversion Goals", "Custom Events", "Revenue Tracking", "Goal Analytics"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Conversion Reports", "Experiment Reports", "Revenue Impact", "Visitor Behavior", "Performance Analytics"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "On-page poll creator",
            "Click heatmaps",
            "Visual A/B test editor",
            "Scroll heatmaps",
            "One-click Zoho Sites integration"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Session recordings",
            "Funnel analysis",
            "Advanced A/B testing",
            "Form analytics",
            "Website personalization"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Understanding why visitors don't convert",
            "Making data-driven design changes",
            "Fixing high bounce rates",
            "Optimizing long forms",
            "Seeing which page elements are ignored",
            "Getting direct user feedback",
            "Safely testing website changes",
            "Tailoring content for different users",
            "Tracking micro-conversions and goals",
            "Visualizing the complete user journey"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI recommendations for A/B tests",
            "Predictive uplift forecasting",
            "Automated user frustration analysis",
            "AI insights from heatmap data",
            "Smart behavioral segmentation",
            "AI form field reordering suggestions",
            "Natural language report queries",
            "AI-generated A/B test summaries",
            "Predictive content personalization",
            "AI anomaly detection in funnels",
            "Automated A/B test hypothesis generation",
            "Sentiment analysis of survey responses",
            "AI identification of valuable segments",
            "Smart alerts for significant results",
            "AI page speed improvement recommendations",
            "Automated user journey mapping",
            "AI design suggestions for conversions",
            "Predictive user friction analysis",
            "AI 'opportunity score' for pages",
            "Automated content personalization ideas"
          ]
        }
      ]
    },