import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Payroll": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Payroll Dashboard", "Monthly Overview", "Employee Summary", "Compliance Status"]
        },
        {
          title: "Employees",
          icon: <Users className="w-4 h-4" />,
          items: ["Employee Directory", "Add Employee", "Employee Profiles", "Salary Details", "Employment History"]
        },
        {
          title: "Payroll Processing",
          icon: <Calculator className="w-4 h-4" />,
          items: ["Run Payroll", "Payroll History", "Draft Payrolls", "Payroll Calendar", "Bulk Updates"]
        },
        {
          title: "Salary Components",
          icon: <DollarSign className="w-4 h-4" />,
          items: ["Basic Salary", "Allowances", "Deductions", "Benefits", "Bonuses", "Overtime"]
        },
        {
          title: "Time & Attendance",
          icon: <Clock className="w-4 h-4" />,
          items: ["Time Tracking", "Attendance Reports", "Leave Management", "Overtime Tracking", "Shift Management"]
        },
        {
          title: "Tax & Compliance",
          icon: <Shield className="w-4 h-4" />,
          items: ["Tax Settings", "Statutory Compliance", "Tax Reports", "Form Generation", "Audit Trail"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Payroll Reports", "Employee Reports", "Tax Reports", "Compliance Reports", "Custom Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Organization Settings", "Payroll Settings", "Tax Configuration", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Employee self-service portal",
            "Direct deposit",
            "Calculate salaries & overtime",
            "Central employee directory",
            "Run payroll in a few clicks"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated payroll tax filing",
            "Benefits administration",
            "Accounting software integration",
            "Time tracking integration",
            "Labor law compliance"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Calculating payroll taxes correctly",
            "Reducing time spent running payroll",
            "Staying compliant with labor laws",
            "Fielding employee pay stub requests",
            "Managing benefit deductions",
            "Tracking employee hours accurately",
            "Automating accounting journal entries",
            "Generating year-end W-2s",
            "Handling different pay schedules",
            "Paying both employees and contractors"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI payroll anomaly detection",
            "Predictive future payroll costs",
            "AI tax withholding optimization",
            "Payroll question chatbot",
            "Automated worker classification",
            "AI-driven compliance alerts",
            "Natural language reporting",
            "AI-powered timesheet validation",
            "Smart payroll deadline reminders",
            "AI salary benchmarking",
            "Automated journal entry generation",
            "AI 'what-if' salary analysis",
            "Predictive turnover analysis",
            "Smart out-of-state work detection",
            "AI insights into labor costs",
            "Automated benefits document parsing",
            "AI assistance for tax setup",
            "Smart alerts for expiring documents",
            "AI payroll process optimization",
            "Automated wage garnishment responses"
          ]
        }
      ]
    },