import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
 "PDF Editor": {
      sections: [
        {
          title: "Editor",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Edit PDF", "Text Editing", "Image Editing", "Page Management", "Annotation Tools"]
        },
        {
          title: "Forms",
          icon: <FileText className="w-4 h-4" />,
          items: ["Create Forms", "Fill Forms", "Form Templates", "Interactive Forms", "Form Fields"]
        },
        {
          title: "Convert",
          icon: <RefreshCw className="w-4 h-4" />,
          items: ["PDF to Word", "PDF to Excel", "PDF to Image", "Word to PDF", "HTML to PDF"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Share Documents", "Comments & Reviews", "Version Control", "Team Collaboration", "Document History"]
        },
        {
          title: "Security",
          icon: <Lock className="w-4 h-4" />,
          items: ["Password Protection", "Digital Signatures", "Encryption", "Watermarks", "Permission Settings"]
        },
        {
          title: "Templates",
          icon: <Bookmark className="w-4 h-4" />,
          items: ["Document Templates", "Form Templates", "Letter Templates", "Report Templates", "Custom Templates"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Editor Preferences", "Export Settings", "Security Options", "Integration Settings", "Account Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Edit text and images",
            "Add comments & annotations",
            "Highlight & underline text",
            "Draw shapes",
            "Fill out PDF forms"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Convert PDF to Office formats",
            "Merge multiple PDFs",
            "Split a PDF",
            "Compress PDF file size",
            "Add password protection"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Fixing a typo in a PDF",
            "Collaborating on a PDF review",
            "Reducing a large PDF file size",
            "Reusing PDF content in Word",
            "Combining PDFs into one file",
            "Securing a sensitive document",
            "Filling out non-interactive forms",
            "Signing a PDF digitally",
            "Reordering pages in a PDF",
            "Making a scanned PDF searchable"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered OCR",
            "AI suggestions for layout improvement",
            "Automated sensitive data redaction",
            "AI-powered document summarization",
            "Smart form field creation",
            "AI 'readability score' analysis",
            "Automated table extraction to Excel",
            "AI 'ask your document' feature",
            "Natural language editing commands",
            "AI recommendations for compression",
            "Smart broken link detection",
            "AI-powered document translation",
            "Automated table of contents generation",
            "AI-based document comparison",
            "Smart accessibility suggestions",
            "AI-powered mobile reflow",
            "Automated document categorization",
            "AI suggestions for splitting documents",
            "Predictive text for form filling",
            "AI-powered format conversion"
          ]
        }
      ]
    }