import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
 "Publish": {
      sections: [
        {
          title: "Listings",
          icon: <MapPin className="w-4 h-4" />,
          items: ["All Listings", "Google My Business", "Bing Places", "Apple Maps", "Local Directories", "Industry Listings"]
        },
        {
          title: "Reviews",
          icon: <Star className="w-4 h-4" />,
          items: ["All Reviews", "Google Reviews", "Facebook Reviews", "Yelp Reviews", "Review Monitoring", "Review Responses"]
        },
        {
          title: "Local SEO",
          icon: <Search className="w-4 h-4" />,
          items: ["SEO Performance", "Keyword Tracking", "Local Rankings", "Citation Building", "SEO Analytics"]
        },
        {
          title: "Social Posts",
          icon: <Share2 className="w-4 h-4" />,
          items: ["Social Media Posts", "Google Posts", "Facebook Posts", "Post Scheduling", "Social Analytics"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Listing Analytics", "Review Analytics", "SEO Analytics", "Social Analytics", "Performance Reports"]
        },
        {
          title: "Reputation Management",
          icon: <ThumbsUp className="w-4 h-4" />,
          items: ["Reputation Monitoring", "Review Management", "Response Templates", "Sentiment Analysis", "Reputation Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Business Information", "Listing Settings", "Review Settings", "Notification Settings", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Update business information",
            "Monitor online reviews",
            "Review response templates",
            "Post to Google Business Profile",
            "Track local keyword rankings"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Sync listings across directories",
            "Centralized review response inbox",
            "Brand reputation monitoring",
            "Local SEO analytics",
            "Social media scheduling"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Fixing inconsistent business info",
            "Managing negative online reviews",
            "Updating dozens of listings",
            "Monitoring brand mentions",
            "Improving local search rankings",
            "Responding to reviews quickly",
            "Generating more positive reviews",
            "Keeping a Google profile active",
            "Understanding local SEO ROI",
            "Managing multiple business locations"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-generated review responses",
            "Review sentiment analysis",
            "AI suggestions for local SEO",
            "Automated duplicate listing detection",
            "AI recommendations for directories",
            "Predictive ranking change analysis",
            "AI-generated Google Post content",
            "Smart alerts for negative mentions",
            "AI analysis of competitor reviews",
            "Natural language analytics queries",
            "AI insights from review data",
            "Automated review topic tagging",
            "AI recommendations for keywords",
            "Smart social posting time suggestions",
            "AI-powered 'reputation score'",
            "Automated performance report generation",
            "AI-based image suggestions for posts",
            "Predictive analysis of review impact",
            "AI-powered response chatbot",
            "Smart detection of review spam"
          ]
        }
      ]
    },