import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Recruit": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Recruitment Overview", "Pipeline Analytics", "Team Performance", "Recent Activities"]
        },
        {
          title: "Jobs",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Jobs", "Published Jobs", "Draft Jobs", "Job Templates", "Job Boards"]
        },
        {
          title: "Candidates",
          icon: <Users className="w-4 h-4" />,
          items: ["All Candidates", "Resume Database", "Candidate Profiles", "Source Tracking", "Candidate Pool"]
        },
        {
          title: "Applications",
          icon: <Inbox className="w-4 h-4" />,
          items: ["All Applications", "Interview Scheduling", "Application Status", "Candidate Pipeline"]
        },
        {
          title: "Interviews",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Schedule Interview", "Interview Calendar", "Interview Feedback", "Panel Management"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Recruitment Reports", "Source Analytics", "Time-to-Hire", "Cost-per-Hire"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Recruitment Settings", "User Management", "Workflow Configuration", "Integrations"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable hiring pipelines",
            "Candidate email templates",
            "Centralized candidate database",
            "Post to multiple job boards",
            "Direct interview scheduling"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated resume parsing",
            "Hiring manager review portal",
            "Advanced recruitment analytics",
            "Premium job board integrations",
            "Workflow automation"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Managing high application volumes",
            "Posting jobs on multiple sites",
            "Ensuring consistent communication",
            "Collaborating with hiring managers",
            "Rediscovering past candidates",
            "Reducing time spent screening resumes",
            "Measuring recruitment effectiveness",
            "Simplifying interview scheduling",
            "Improving the candidate experience",
            "Creating a branded career page"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered candidate sourcing",
            "Zia: AI candidate matching",
            "Predictive candidate success analysis",
            "AI resume screening and ranking",
            "Screening chatbot for candidates",
            "Interview feedback sentiment analysis",
            "AI job description improvement",
            "Automated interview scheduling",
            "AI video interview analysis",
            "Predictive time-to-hire analysis",
            "Smart talent pool rediscovery",
            "AI compensation benchmarking",
            "Automated background checks",
            "AI diversity & inclusion analytics",
            "Natural language candidate search",
            "AI onboarding workflow suggestions",
            "Predictive job board performance",
            "Automated interview question generation",
            "AI ideal candidate profile building",
            "Smart alerts for top-tier candidates"
          ]
        }
      ]
    }