import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Reports": {
      sections: [
        {
          title: "Folders",
          icon: <Folder className="w-4 h-4" />,
          items: ["All Reports", "My Reports", "Favorites", "Recently Viewed", "Scheduled Reports", "Recently Deleted"]
        },
        {
          title: "Account and Contact Reports",
          icon: <Users className="w-4 h-4" />,
          items: ["Account Reports", "Contact Reports", "Account Contact Relationships", "Contact Activity Reports"]
        },
        {
          title: "Deal Reports",
          icon: <TrendingUp className="w-4 h-4" />,
          items: ["Deal Performance", "Deal Pipeline", "Deal Conversion", "Deal Activity", "Deal Forecast"]
        },
        {
          title: "Lead Reports",
          icon: <ArrowRight className="w-4 h-4" />,
          items: ["Lead Generation", "Lead Conversion", "Lead Source Analysis", "Lead Activity", "Lead Performance"]
        },
        {
          title: "Campaign Reports",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Campaign Performance", "Campaign ROI", "Campaign Analytics", "Email Campaign Reports"]
        },
        {
          title: "Case and Solution Reports",
          icon: <AlertCircle className="w-4 h-4" />,
          items: ["Case Reports", "Solution Reports", "Case Resolution", "Support Analytics"]
        },
        {
          title: "Product Reports",
          icon: <Package className="w-4 h-4" />,
          items: ["Product Performance", "Product Analytics", "Inventory Reports", "Product Catalog"]
        },
        {
          title: "Vendor Reports",
          icon: <Building2 className="w-4 h-4" />,
          items: ["Vendor Performance", "Vendor Analysis", "Purchase Reports", "Vendor Analytics"]
        },
        {
          title: "Quote Reports",
          icon: <FileText className="w-4 h-4" />,
          items: ["Quote Performance", "Quote Analysis", "Quote Conversion", "Quote Activity"]
        },
        {
          title: "Sales Order Reports",
          icon: <Truck className="w-4 h-4" />,
          items: ["Sales Order Performance", "Order Analysis", "Delivery Reports", "Order Tracking"]
        },
        {
          title: "Purchase Order Reports",
          icon: <Truck className="w-4 h-4" />,
          items: ["Purchase Order Performance", "Purchase Analysis", "Procurement Reports", "Purchase Tracking"]
        },
        {
          title: "Invoice Reports",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["Invoice Performance", "Invoice Analysis", "Payment Reports", "Revenue Reports"]
        },
        {
          title: "Sales Metrics Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Sales Performance", "Sales Analytics", "Revenue Analytics", "Sales Forecasting"]
        },
        {
          title: "Email Reports",
          icon: <Mail className="w-4 h-4" />,
          items: ["Email Performance", "Email Analytics", "Email Campaign Reports", "Email Tracking"]
        },
        {
          title: "Meeting Reports",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Meeting Performance", "Meeting Analytics", "Meeting Activity", "Meeting Scheduling"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Pre-built report templates",
            "Create tabular reports",
            "Export to CSV/PDF",
            "Basic charts",
            "Scheduled email reports"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Drag-and-drop report builder",
            "Custom dashboards",
            "Advanced filtering",
            "Calculated fields & formulas",
            "Secure report sharing"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Building a custom report",
            "Automating weekly reporting",
            "Getting insights from raw data",
            "Sharing data with management",
            "Analyzing specific data segments",
            "Calculating custom metrics",
            "Getting a business health overview",
            "Analyzing data in Excel",
            "Creating different views of data",
            "Presenting data effectively"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered report generation",
            "AI-driven data insights",
            "Automated anomaly detection",
            "AI chart type suggestions",
            "Predictive forecasting in reports",
            "AI-generated report summaries",
            "Smart metric threshold alerts",
            "AI-powered root cause analysis",
            "Automated data clustering",
            "AI recommendations for new reports",
            "Smart data cleansing suggestions",
            "AI-powered 'what-if' analysis",
            "Automated metric correlation detection",
            "AI-based filter suggestions",
            "Smart data blending",
            "AI-powered 'goal seek' analysis",
            "Automated KPI dashboard generation",
            "AI dashboard design suggestions",
            "Predictive lead scoring in reports",
            "AI-powered trend analysis"
          ]
        }
      ]
    },