import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"RouteIQ": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Route Overview", "Sales Performance", "Territory Analytics", "Team Status"]
        },
        {
          title: "Routes",
          icon: <Navigation className="w-4 h-4" />,
          items: ["Route Planning", "Optimized Routes", "Route History", "Multi-day Routes"]
        },
        {
          title: "Territories",
          icon: <Map className="w-4 h-4" />,
          items: ["Territory Management", "Territory Assignment", "Coverage Analysis", "Boundary Settings"]
        },
        {
          title: "Maps",
          icon: <MapPin className="w-4 h-4" />,
          items: ["Interactive Maps", "Location Tracking", "Geofencing", "Map Layers"]
        },
        {
          title: "Check-ins",
          icon: <Clock className="w-4 h-4" />,
          items: ["Visit Tracking", "Check-in History", "Location Verification", "Time Tracking"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Route Reports", "Territory Reports", "Performance Analytics", "Distance Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Route Settings", "Map Configuration", "Team Management", "Integration"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Visualize CRM data on a map",
            "Create optimized daily routes",
            "Mobile app for navigation",
            "View nearby prospects",
            "Log meeting notes"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated territory management",
            "Multi-day route planning",
            "Real-time rep location tracking",
            "Detailed travel reports",
            "Automatic CRM record updates"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Reducing drive time for sales reps",
            "Creating balanced sales territories",
            "Knowing where field reps are",
            "Finding nearby opportunities",
            "Automating CRM data entry after visits",
            "Planning multi-day sales trips",
            "Understanding field team efficiency",
            "Ensuring high-priority clients are visited",
            "Guiding new reps in their territory",
            "Visualizing sales data geographically"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered route optimization",
            "Predictive 'best time to visit' analysis",
            "AI-based territory suggestions",
            "Smart route deviation alerts",
            "AI 'fill my day' scheduling",
            "Automated route profitability analysis",
            "AI-based territory balancing",
            "Natural language route planning",
            "AI-powered check-in analysis",
            "Predictive fuel cost analysis",
            "Smart client clustering",
            "AI recommendations for next visits",
            "Automated daily performance summaries",
            "AI-based appointment scheduling",
            "Meeting note sentiment analysis",
            "AI 'what-if' territory analysis",
            "Smart route overlap detection",
            "AI recommendations for rep assignments",
            "Predictive geographic lead generation",
            "Automated voice-to-text note logging"
          ]
        }
      ]
    },