import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Shifts": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Today's Schedule", "Team Overview", "Shift Statistics", "Quick Actions", "Recent Activity", "Shifts Overview", "Staff Status"]
        },
        {
          title: "Schedule",
          icon: <Calendar className="w-4 h-4" />,
          items: ["View Schedule", "Create Schedule", "Shift Templates", "Recurring Shifts", "Schedule Conflicts", "Weekly Schedule", "Monthly Schedule", "Daily Schedule", "Schedule Planning", "Shift Swaps"]
        },
        {
          title: "Employees",
          icon: <Users className="w-4 h-4" />,
          items: ["All Employees", "Shift Assignments", "Employee Availability", "Skill Sets", "Employee Profiles"]
        },
        {
          title: "Time Tracking",
          icon: <Clock className="w-4 h-4" />,
          items: ["Clock In/Out", "Time Logs", "Break Management", "Overtime Tracking", "Time Corrections", "Timesheet", "Attendance", "Overtime"]
        },
        {
          title: "Attendance",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Attendance Reports", "Absence Management", "Late Arrivals", "Early Departures", "Attendance Policies"]
        },
        {
          title: "Requests",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Shift Requests", "Time Off Requests", "Swap Requests", "Overtime Requests", "Request Approvals"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Schedule Reports", "Attendance Reports", "Labor Cost Reports", "Productivity Reports", "Custom Reports", "Time Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Shift Settings", "Employee Settings", "Notification Settings", "Integration Settings", "Company Settings"]
        },
        {
          title: "Staff",
          icon: <Users className="w-4 h-4" />,
          items: ["All Staff", "Available Staff", "Staff Schedules", "Staff Performance", "Time Off Requests"]
        },
        {
          title: "Locations",
          icon: <MapPin className="w-4 h-4" />,
          items: ["All Locations", "Location Schedules", "Location Staff", "Geofencing", "Location Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Publish employee schedules",
            "Employee mobile app",
            "Mobile clock-in/out",
            "Set employee availability",
            "Today's schedule view"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Shift swapping",
            "Automated scheduling",
            "Geofenced time tracking",
            "Labor cost forecasting",
            "Payroll integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Time-consuming manual scheduling",
            "Handling last-minute shift changes",
            "Fielding 'what's my schedule?' calls",
            "Covering sick leave easily",
            "Preventing inaccurate time tracking",
            "Staying within a labor budget",
            "Ensuring adequate staff coverage",
            "Automating payroll data entry",
            "Accommodating availability requests",
            "Communicating schedule updates"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered auto-scheduling",
            "Predictive staffing forecasts",
            "AI suggestions for shift coverage",
            "Smart overtime alerts",
            "AI analysis of shift patterns",
            "Automated shift swap approvals",
            "AI-based time clock fraud detection",
            "Natural language schedule queries",
            "AI recommendations for fair schedules",
            "Predictive burnout/flight risk analysis",
            "Smart shift reminders",
            "AI chatbot for scheduling questions",
            "Automated labor law compliance",
            "AI suggestions for shift templates",
            "Schedule communication sentiment analysis",
            "Predictive analysis of shift acceptance",
            "AI 'what-if' staffing scenarios",
            "Smart skill-to-shift matching",
            "AI insights into attendance patterns",
            "Automated voice-to-text notes for managers"
          ]
        }
      ]
    }