import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Sign": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Document Overview", "Pending Signatures", "Completed Documents", "Recent Activity"]
        },
        {
          title: "Documents",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Documents", "Draft Documents", "In Progress", "Completed", "Templates"]
        },
        {
          title: "Send for Signature",
          icon: <Send className="w-4 h-4" />,
          items: ["Upload Document", "Add Recipients", "Set Signature Fields", "Customize Message"]
        },
        {
          title: "Sign Documents",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Pending Signatures", "Digital Signature", "Initial & Date", "Fill Forms"]
        },
        {
          title: "Templates",
          icon: <Copy className="w-4 h-4" />,
          items: ["Document Templates", "Signature Templates", "Reusable Fields", "Template Library"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Signature Analytics", "Document Status", "Audit Trail", "Compliance Reports"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Upload any document",
            "Drag & drop signature fields",
            "Send to multiple recipients",
            "Email status notifications",
            "Mobile signing app"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Legally binding e-signatures",
            "Complete document audit trail",
            "CRM & HR system integration",
            "Bulk sending to many people",
            "Reusable document templates"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Replacing print-sign-scan workflows",
            "Getting signatures from remote parties",
            "Ensuring legal validity of documents",
            "Tracking document status",
            "Standardizing frequently used contracts",
            "Following up on unsigned documents",
            "Signing documents on a phone",
            "Collecting data on forms",
            "Integrating signing into business processes",
            "Storing signed documents securely"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI document scanning & field detection",
            "Smart signature field suggestions",
            "AI analysis of document risk",
            "Predictive 'time-to-sign' analysis",
            "AI-driven identity verification",
            "Automated document summarization",
            "Natural language document search",
            "AI-powered smart reminders",
            "Automated data extraction from forms",
            "AI fraudulent signature detection",
            "Smart template recommendations",
            "AI 'readability score' for contracts",
            "Automated contract version comparison",
            "AI chatbot for signer guidance",
            "Predictive workflow bottleneck analysis",
            "AI suggestions for template improvement",
            "Automated document categorization",
            "AI-powered signature verification",
            "Smart expiration alerts",
            "AI-based clause localization"
          ]
        }
      ]
    }