import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Sprints": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Sprint Overview", "Team Velocity", "Burndown Charts", "Sprint Progress"]
        },
        {
          title: "Backlog",
          icon: <List className="w-4 h-4" />,
          items: ["Product Backlog", "Sprint Backlog", "Epic Management", "Story Mapping"]
        },
        {
          title: "Sprints",
          icon: <Timer className="w-4 h-4" />,
          items: ["Active Sprints", "Sprint Planning", "Sprint Review", "Sprint Retrospective"]
        },
        {
          title: "Scrum Board",
          icon: <Grid className="w-4 h-4" />,
          items: ["Kanban Board", "Task Management", "Workflow Stages", "Custom Workflows"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Velocity Reports", "Burndown Reports", "Sprint Reports", "Team Performance"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Project Settings", "Team Configuration", "Workflow Settings", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Product backlog",
            "Sprint planning board",
            "Scrum board",
            "Burndown chart",
            "Story point estimation"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Epic management",
            "Release planner",
            "Team velocity charts",
            "Code repository integration",
            "Stakeholder portal"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Managing feature requests",
            "Avoiding sprint overcommitment",
            "Gaining visibility into team's work",
            "Knowing if a sprint is on track",
            "Estimating tasks accurately",
            "Connecting work to business goals",
            "Reducing context switching for devs",
            "Planning future releases",
            "Improving team performance",
            "Keeping stakeholders informed"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered user story splitting",
            "Predictive sprint completion analysis",
            "AI-based story point estimation",
            "Smart alerts for blocked tasks",
            "AI-driven sprint planning recommendations",
            "Automated scope creep detection",
            "AI analysis of retrospective feedback",
            "Natural language user story creation",
            "AI suggestions for workflow improvement",
            "Predictive risk and dependency analysis",
            "Automated sprint review generation",
            "AI-powered 'sprint health' score",
            "Smart task allocation",
            "AI recommendations for backlog grooming",
            "Automated commit-to-story linking",
            "Comment sentiment analysis",
            "AI-powered release date forecasting",
            "Smart technical debt suggestions",
            "AI 'what-if' analysis for planning",
            "Automated identification of related bugs"
          ]
        }
      ]
    },