import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Survey": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Survey Overview", "Response Analytics", "Active Surveys", "Performance Summary"]
        },
        {
          title: "Surveys",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["All Surveys", "Published Surveys", "Draft Surveys", "Survey Templates", "Question Bank"]
        },
        {
          title: "Builder",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Survey Builder", "Question Types", "Logic & Branching", "Survey Themes", "Advanced Settings"]
        },
        {
          title: "Distribution",
          icon: <Share2 className="w-4 h-4" />,
          items: ["Email Invitations", "Social Sharing", "Website Embedding", "QR Codes", "Mobile App"]
        },
        {
          title: "Responses",
          icon: <Database className="w-4 h-4" />,
          items: ["All Responses", "Response Details", "Export Responses", "Real-time Results", "Data Filtering"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Response Analytics", "Cross Tabulation", "Sentiment Analysis", "Text Analytics", "Reports"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Pre-built survey templates",
            "Multiple question types",
            "Customizable 'Thank You' page",
            "Real-time response tracking",
            "Simple web link sharing"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Skip logic and question branching",
            "Multi-channel distribution",
            "Offline survey collection",
            "Advanced reporting & cross-tabulation",
            "Integration to trigger surveys"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Solving low survey response rates",
            "Avoiding irrelevant questions",
            "Getting feedback at the right time",
            "Analyzing open-ended feedback",
            "Ensuring respondent anonymity",
            "Matching surveys to company branding",
            "Conducting field research offline",
            "Preventing duplicate survey submissions",
            "Collaborating on survey creation",
            "Turning data into actionable insights"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered survey generation",
            "AI suggestions to reduce bias",
            "Predictive completion rate analysis",
            "Automated sentiment analysis",
            "AI identification of feedback themes",
            "Smart logic suggestions",
            "AI recommendations for survey length",
            "Predictive respondent fatigue detection",
            "AI-powered data cleaning",
            "Natural language results analysis",
            "AI-generated findings summaries",
            "Automated survey translation",
            "AI-based A/B testing for questions",
            "Smart distribution channel advice",
            "AI anomaly detection in responses",
            "Predictive analysis of respondent value",
            "AI-generated action plans",
            "Smart reminders for participants",
            "AI comparison to industry benchmarks",
            "Automated 'Other' response categorization"
          ]
        }
      ]
    },