import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Tables": {
      sections: [
        {
          title: "Tables",
          icon: <Table className="w-4 h-4" />,
          items: ["All Tables", "Recent Tables", "Shared Tables", "Templates", "Archived Tables"]
        },
        {
          title: "Forms",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Forms", "Form Builder", "Form Responses", "Published Forms", "Form Analytics"]
        },
        {
          title: "Workflows",
          icon: <Zap className="w-4 h-4" />,
          items: ["All Workflows", "Workflow Builder", "Automation Rules", "Triggered Actions", "Workflow History"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Data Reports", "Visual Reports", "Custom Reports", "Scheduled Reports", "Report Builder"]
        },
        {
          title: "Data Management",
          icon: <Database className="w-4 h-4" />,
          items: ["Import Data", "Export Data", "Data Validation", "Bulk Operations", "Data Backup"]
        },
        {
          title: "Team Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Team Members", "Permissions", "Comments", "Activity Log", "Notifications"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Table Settings", "Access Control", "Integrations", "API Settings", "Account Preferences"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Spreadsheet-like interface",
            "Multiple data views",
            "Link records between tables",
            "Form view for data collection",
            "Pre-built templates"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "No-code custom applications",
            "Workflow automation",
            "Role-based permissions",
            "API & webhook integrations",
            "Customizable dashboards"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Replacing complex spreadsheets",
            "Creating simple project trackers",
            "Managing simple inventories",
            "Building a simple CRM",
            "Automating simple approval processes",
            "Collecting structured data from a team",
            "Collaborating on a dataset",
            "Visualizing a workflow",
            "Building a quick, custom app",
            "Connecting data to other services"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI app generation from spreadsheets",
            "AI suggestions for table relationships",
            "Automated data cleansing",
            "AI suggestions for new data views",
            "Natural language data querying",
            "AI-driven workflow suggestions",
            "Smart data validation rules",
            "AI-powered data summarization",
            "Predictive analytics on your data",
            "AI pattern recognition for new fields",
            "Automated data entry from email",
            "AI image recognition for attachments",
            "Smart alerts for data changes",
            "AI suggestions for base design",
            "Automated dashboard generation",
            "Sentiment analysis of text fields",
            "AI-powered 'what-if' analysis",
            "Smart data import & mapping",
            "AI-based formula assistance",
            "Predictive sorting and filtering"
          ]
        }
      ]
    },