import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"ToDo": {
      sections: [
        {
          title: "Tasks",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["All Tasks", "My Tasks", "Today's Tasks", "Overdue Tasks", "Completed Tasks", "Recurring Tasks"]
        },
        {
          title: "Projects",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Projects", "Active Projects", "My Projects", "Shared Projects", "Project Templates", "Archived Projects"]
        },
        {
          title: "Teams",
          icon: <Users className="w-4 h-4" />,
          items: ["Team Tasks", "Team Projects", "Team Members", "Task Assignment", "Team Activity", "Permissions"]
        },
        {
          title: "Calendar",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Task Calendar", "Due Dates", "Schedule View", "Calendar Integration", "Timeline View"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Task Reports", "Project Reports", "Team Performance", "Time Tracking", "Productivity Analytics"]
        },
        {
          title: "Labels & Filters",
          icon: <Tag className="w-4 h-4" />,
          items: ["Task Labels", "Custom Filters", "Smart Lists", "Saved Searches", "Priority Levels"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Task Preferences", "Notification Settings", "Integration Settings", "Team Settings", "Account Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Create to-do lists",
            "Set due dates & reminders",
            "Add sub-tasks",
            "Prioritize tasks",
            "\"My Day\" view"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Share lists & assign tasks",
            "Recurring tasks",
            "Cross-device sync",
            "Add notes & attachments",
            "Calendar integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Forgetting daily tasks",
            "Losing paper to-do lists",
            "Breaking down big tasks",
            "Collaborating on simple lists",
            "Remembering to do chores",
            "Focusing on what to do today",
            "Adding context to a task",
            "Juggling tasks and events",
            "Capturing ideas on the go",
            "Organizing different life areas"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI suggestions for task scheduling",
            "Natural language task input",
            "AI-based adaptive reminders",
            "Smart sub-task suggestions",
            "AI daily planning assistant",
            "Automated task prioritization",
            "AI suggestions for recurring tasks",
            "Predictive 'at-risk' task alerts",
            "AI-powered 'focus mode'",
            "Smart grouping of similar tasks",
            "AI-driven celebration messages",
            "Automated task import from email",
            "AI suggestions for task delegation",
            "Smart task duration estimation",
            "AI-powered weekly review",
            "Automated task creation from photos",
            "AI suggestions for task labels",
            "Predictive productivity analysis",
            "AI suggestions for calendar-related tasks",
            "Smart 'undo' for completed tasks"
          ]
        }
      ]
    },