import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Webinar": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Webinar Overview", "Analytics Dashboard", "Upcoming Events", "Performance Metrics"]
        },
        {
          title: "Webinars",
          icon: <Video className="w-4 h-4" />,
          items: ["All Webinars", "Live Webinars", "Scheduled Events", "Recurring Webinars", "Practice Sessions"]
        },
        {
          title: "Registrations",
          icon: <Users className="w-4 h-4" />,
          items: ["Attendee Management", "Registration Forms", "Approval Workflows", "Bulk Registration"]
        },
        {
          title: "Recordings",
          icon: <PlayCircle className="w-4 h-4" />,
          items: ["All Recordings", "Cloud Storage", "Download Center", "Sharing Settings"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Attendance Reports", "Engagement Analytics", "Registration Analytics", "Performance Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Webinar Settings", "Branding", "Email Templates", "Integration"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable registration pages",
            "Automated reminder emails",
            "In-webinar polls & Q&A",
            "Screen sharing",
            "Basic attendance analytics"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Live video broadcasting",
            "On-demand webinars",
            "Marketing & CRM integration",
            "Co-organizers and panelists",
            "Lead source tracking"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Presenting to a large audience",
            "Generating leads from webinars",
            "Keeping the audience engaged",
            "Increasing show-up rates",
            "Making content available on-demand",
            "Understanding webinar performance",
            "Following up with attendees",
            "Managing audience questions",
            "Handling multiple speakers",
            "Getting people to register"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI suggestions for best webinar time",
            "AI-generated promotional copy",
            "Predictive attendance rate analysis",
            "AI topic suggestions",
            "Automated webinar transcription",
            "AI-powered content summarization",
            "Live chat sentiment analysis",
            "AI recommendations for slide improvement",
            "Smart 'engagement drop' alerts",
            "AI chatbot for technical support",
            "Automated 'key moments' highlighting",
            "AI analysis of Q&A themes",
            "Predictive lead scoring of attendees",
            "AI-generated poll questions",
            "Natural language transcript search",
            "AI 'practice mode' with feedback",
            "Smart background noise cancellation",
            "AI recommendations for related content",
            "Automated social media clip creation",
            "AI analysis of success factors"
          ]
        }
      ]
    },