import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Workerly": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Workforce Overview", "Assignment Status", "Performance Metrics", "Recent Activities"]
        },
        {
          title: "Workers",
          icon: <Users className="w-4 h-4" />,
          items: ["All Workers", "Worker Profiles", "Skills & Qualifications", "Availability"]
        },
        {
          title: "Assignments",
          icon: <FileText className="w-4 h-4" />,
          items: ["Current Assignments", "Assignment History", "Assignment Matching", "Client Requests"]
        },
        {
          title: "Scheduling",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Shift Scheduling", "Calendar View", "Time Tracking", "Attendance Management"]
        },
        {
          title: "Payroll",
          icon: <DollarSign className="w-4 h-4" />,
          items: ["Payroll Processing", "Timesheets", "Payment Records", "Tax Management"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Workforce Analytics", "Performance Reports", "Financial Reports", "Compliance Reports"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Central temp database",
            "Worker availability calendar",
            "Bulk email/SMS to temps",
            "Temp mobile app",
            "Client contact management"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated job-to-temp matching",
            "Client portal",
            "Digital timesheet workflows",
            "Automated invoice generation",
            "GPS-verified clock-ins"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Filling last-minute jobs",
            "Manually creating schedules",
            "Handling inaccurate timesheets",
            "Reducing client communication overhead",
            "Matching the right skills to jobs",
            "Speeding up payroll and invoicing",
            "Broadcasting jobs to many temps",
            "Preventing no-shows and forgotten shifts",
            "Tracking job profitability",
            "Ensuring temps are paid accurately"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered temp-to-job matching",
            "Predictive temp demand forecasting",
            "AI resume skill validation",
            "Smart travel time optimization",
            "AI chatbot for temp queries",
            "Automated timesheet anomaly detection",
            "AI-driven rating and feedback system",
            "Predictive job acceptance analysis",
            "AI suggestions for shift coverage",
            "Natural language temp search",
            "AI-generated job descriptions",
            "Client feedback sentiment analysis",
            "AI dynamic pricing suggestions",
            "Automated labor law compliance checks",
            "Predictive temp reliability analysis",
            "AI recommendations for upskilling",
            "Smart alerts for expiring certifications",
            "AI-powered payroll auditing",
            "Automated temp performance reports",
            "AI client-to-temp matching"
          ]
        }
      ]
    }