import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"WorkDrive": {
      sections: [
        {
          title: "My Files",
          icon: <Folder className="w-4 h-4" />,
          items: ["All Files", "Recent Files", "Starred Files", "Trash", "Offline Files"]
        },
        {
          title: "Shared",
          icon: <Share2 className="w-4 h-4" />,
          items: ["Shared with Me", "Shared by Me", "Team Folders", "Public Links", "External Sharing"]
        },
        {
          title: "Team Folders",
          icon: <Users className="w-4 h-4" />,
          items: ["All Team Folders", "My Teams", "Folder Permissions", "Team Analytics"]
        },
        {
          title: "Sync",
          icon: <RefreshCw className="w-4 h-4" />,
          items: ["Desktop Sync", "Mobile Sync", "Sync Status", "Sync Settings", "Version History"]
        },
        {
          title: "Security",
          icon: <Shield className="w-4 h-4" />,
          items: ["Access Permissions", "Data Encryption", "Audit Logs", "Compliance Reports"]
        },
        {
          title: "Administration",
          icon: <Settings className="w-4 h-4" />,
          items: ["User Management", "Storage Management", "Security Settings", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Recent Files view",
            "File version history",
            "Starred files and folders",
            "Desktop sync client",
            "Trash for file recovery"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Centralized Team Folders",
            "Granular role-based permissions",
            "Integrated office suite",
            "Advanced admin security controls",
            "Secure external sharing"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Solving scattered file storage",
            "Eliminating document version chaos",
            "Controlling access to sensitive data",
            "Sharing large files securely",
            "Finding files with content search",
            "Simplifying team access to files",
            "Recovering accidentally deleted files",
            "Accessing files while offline",
            "Ensuring data security and compliance",
            "Preventing data loss when employees leave"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered contextual search",
            "Automated file organization suggestions",
            "AI sensitive data (PII) detection",
            "Predictive file access suggestions",
            "AI-powered OCR for images/PDFs",
            "Smart sharing recommendations",
            "AI-driven duplicate file detection",
            "Automated document summarization",
            "AI malware and virus scanning",
            "Natural language file search",
            "AI-powered workflow automation",
            "Smart alerts for unusual file activity",
            "AI recommendations for archiving",
            "Automated content-based tagging",
            "AI-powered virtual data room creation",
            "Document comment sentiment analysis",
            "AI insights into content usage",
            "Smart 'what's changed' version comparison",
            "AI-powered knowledge discovery",
            "Automated on-demand file conversion"
          ]
        }
      ]
    }