import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

    "ZeptoMail": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Email Analytics", "Delivery Dashboard", "Bounce Analytics", "Performance Overview", "Recent Activity"]
        },
        {
          title: "Email Management",
          icon: <Mail className="w-4 h-4" />,
          items: ["Compose Email", "Email Templates", "Scheduled Emails", "Draft Emails", "Sent Emails", "Bounced Emails"]
        },
        {
          title: "Templates",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Templates", "Email Templates", "Custom Templates", "Template Categories", "Shared Templates"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Email Performance", "Delivery Reports", "Open Rates", "Click Rates", "Bounce Reports", "Spam Reports"]
        },
        {
          title: "Domain Management",
          icon: <Globe className="w-4 h-4" />,
          items: ["Verified Domains", "Domain Authentication", "SPF Records", "DKIM Settings", "Domain Reputation"]
        },
        {
          title: "API Integration",
          icon: <Code className="w-4 h-4" />,
          items: ["API Documentation", "API Keys", "Webhooks", "Integration Guide", "SDK Downloads"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Account Settings", "Email Configuration", "Security Settings", "Team Management", "Billing"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Send via API or SMTP",
            "Email activity dashboard",
            "Transactional email templates",
            "Real-time delivery tracking",
            "Bounce & complaint handling"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "High email deliverability",
            "Domain authentication guides",
            "Open & click rate analytics",
            "Real-time event webhooks",
            "Email archiving & search"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Emails going to spam",
            "Knowing if emails are delivered",
            "Setting up SPF & DKIM",
            "Avoiding hard-coded email content",
            "Handling bounced emails",
            "Triggering actions from email events",
            "Sending high-volume emails",
            "Troubleshooting delivery failures",
            "Protecting sender reputation",
            "Searching for a specific sent email"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI content optimization for deliverability",
            "Predictive email engagement analytics",
            "AI potential spam detection",
            "Smart template design suggestions",
            "AI analysis of bounce messages",
            "Automated A/B testing for content",
            "AI-powered IP reputation management",
            "Predictive spam complaint analysis",
            "AI recommendations for send times",
            "Natural language log search",
            "AI-generated subject lines",
            "Smart alerts for delivery anomalies",
            "AI-powered inbound email parsing",
            "Automated email categorization",
            "AI insights into sending patterns",
            "Predictive deliverability forecasting",
            "AI-based domain setup assistance",
            "Smart sending-rate throttling",
            "AI-powered inbox placement testing",
            "Automated weekly deliverability reports"
          ]
        }
      ]
    },