import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Assist": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Support Overview", "Active Sessions", "Performance Metrics", "Recent Activities"]
        },
        {
          title: "Remote Support",
          icon: <Monitor className="w-4 h-4" />,
          items: ["Screen Sharing", "Remote Control", "File Transfer", "Multi-monitor Support"]
        },
        {
          title: "Sessions",
          icon: <Users className="w-4 h-4" />,
          items: ["Current Sessions", "Scheduled Sessions", "Session History", "Session Recording"]
        },
        {
          title: "Chat Support",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["Live Chat", "Chat History", "File Sharing", "Screen Annotation"]
        },
        {
          title: "Tools",
          icon: <Settings className="w-4 h-4" />,
          items: ["System Information", "Diagnostic Tools", "Performance Monitor", "Registry Editor"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Session Reports", "Performance Reports", "Usage Analytics", "Customer Satisfaction"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "On-demand remote support",
            "File transfer",
            "In-session chat",
            "Reboot and reconnect",
            "Multi-monitor support"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Unattended remote access",
            "Screen sharing for demos",
            "Session recording",
            "Cross-platform support",
            "Mass deployment of agents"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Troubleshooting remote computers",
            "Guiding non-technical users",
            "Managing fleets of computers",
            "Getting files from a remote PC",
            "Training customers on software",
            "Ensuring remote access is secure",
            "Supporting different operating systems",
            "Keeping a record of support sessions",
            "Diagnosing issues without interruption",
            "Integrating support with a help desk"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered screen OCR",
            "Smart diagnostic suggestions",
            "AI analysis of session recordings",
            "Automated session summaries",
            "AI-driven AR remote assistance",
            "Predictive device support needs",
            "AI troubleshooting chatbot",
            "Natural language technician commands",
            "AI performance anomaly detection",
            "Automated screen redaction",
            "AI-powered chat translation",
            "Smart technician scheduling",
            "AI knowledge base recommendations",
            "Predictive session duration analysis",
            "AI-powered 'show me' guidance",
            "Automated session categorization",
            "AI-based voice-to-text for notes",
            "Smart security risk alerts",
            "AI-optimized screen quality",
            "Automated post-session surveys"
          ]
        }
      ]
    }
    