import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";


    "Bigin": {
      sections: [
        {
          title: "Pipelines",
          icon: <GitBranch className="w-4 h-4" />,
          items: ["Team Pipelines", "Sub-Pipelines", "Sales Pipeline", "Customer Support Pipelines", "Stage Automation", "Collapsible Stages"]
        },
        {
          title: "Contacts",
          icon: <Users className="w-4 h-4" />,
          items: ["Customer Data", "Prospect Management", "Contact Details", "Associated Deals", "Lead Conversion", "Custom Contact Fields", "Activities History"]
        },
        {
          title: "Companies",
          icon: <Building2 className="w-4 h-4" />,
          items: ["Business Partners", "Company Profiles", "Associated Contacts", "Business Relationships", "Company Pipelines"]
        },
        {
          title: "Products",
          icon: <Package className="w-4 h-4" />,
          items: ["Product Catalog", "Services Management", "Product Lifecycle", "Pricing & Inventory", "Product Records", "Custom Product Fields"]
        },
        {
          title: "Activities",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Tasks & Events", "Calls Scheduling", "Calendar Integration", "Follow-up Reminders", "Activity Notifications", "Call Logging", "Meeting Scheduling"]
        },
        {
          title: "Dashboards",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Goal Setting", "Goal Tracking", "Business Insights", "Performance Metrics", "Custom Reporting", "Data Visualization", "Progress Monitoring"]
        },
        {
          title: "Messages",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["Lead Capture", "Customer Communication", "Chat History", "Multi-channel Messaging", "WhatsApp Integration", "Communication Logs"]
        },
        {
          title: "Automation",
          icon: <Zap className="w-4 h-4" />,
          items: ["Email Workflows", "Stage Automation", "Booking Pages", "LeadChain Integration", "Marketing Automation", "Workflow Builder"]
        },
        {
          title: "Integrations",
          icon: <Link2 className="w-4 h-4" />,
          items: ["Zoho SalesIQ", "Instagram Integration", "Facebook Integration", "LinkedIn Integration", "TikTok Integration", "Enhanced Forms"]
        },
        {
          title: "Mobile Features",
          icon: <Smartphone className="w-4 h-4" />,
          items: ["Business Card Scanner", "Offline Access", "Push Notifications", "Touch ID Security", "Dark Mode", "Calendar View"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Simplified Contact Import",
            "One-Click 'Call' Button",
            "Basic Email Templates",
            "Meeting Scheduler Link",
            "Pipeline Stage Color-Coding"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated Lead Assignment",
            "Telephony Integration",
            "Team Performance Dashboards",
            "Product/Service Management",
            "Custom Workflow Automation"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Automated Follow-up Reminders",
            "Visual Drag-and-Drop Pipeline",
            "Unified Contact Timeline",
            "Shareable Booking Links",
            "Business Card Scanner",
            "Simple Performance Dashboards",
            "Offline Mobile Access",
            "Distinct Process Pipelines",
            "Repetitive Task Automation",
            "Key App Integrations"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI 'Next Best Action' Suggester",
            "Predictive Lead Scoring",
            "Email Sentiment Analysis",
            "Automated Data Enrichment",
            "Best Time to Contact AI",
            "AI-Generated Follow-up Emails",
            "Voice-to-Text Note Logging",
            "Pipeline Anomaly Detection",
            "AI Sales Assistant Q&A",
            "Automated Contact Tagging",
            "AI-Powered Deal Insights",
            "Automated Meeting Summaries",
            "Predictive Pipeline Forecasting",
            "Intelligent Task Recommendations",
            "AI-driven Competitor Alerts",
            "Automated Data Deduplication",
            "AI-based Lead Source Analysis",
            "Smart Email Scheduling",
            "AI-powered Sales Playbooks",
            "Automated Voicemail Transcription"
          ]
        }
      ]
    }