import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Billing": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Billing Overview", "Revenue Metrics", "Subscription Analytics", "Payment Status", "MRR Tracking"]
        },
        {
          title: "Subscriptions",
          icon: <RefreshCw className="w-4 h-4" />,
          items: ["All Subscriptions", "Active Subscriptions", "Trials", "Cancelled", "Subscription Plans", "Upgrades & Downgrades"]
        },
        {
          title: "Invoices",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Invoices", "Draft Invoices", "Pending Invoices", "Paid Invoices", "Overdue Invoices", "Credit Notes"]
        },
        {
          title: "Customers",
          icon: <Users className="w-4 h-4" />,
          items: ["Customer Management", "Billing Contacts", "Payment Methods", "Customer Portal", "Dunning Management"]
        },
        {
          title: "Payments",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["Payment History", "Failed Payments", "Refunds", "Payment Gateways", "Payment Links"]
        },
        {
          title: "Revenue Recognition",
          icon: <TrendingUp className="w-4 h-4" />,
          items: ["Revenue Schedules", "Deferred Revenue", "Revenue Reports", "ASC 606 Compliance"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Revenue Analytics", "Churn Analysis", "Cohort Analysis", "Subscription Metrics", "Custom Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Billing Settings", "Tax Settings", "Payment Settings", "Dunning Settings", "Integration"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Create subscription plans",
            "Automated recurring invoicing",
            "Prorated billing",
            "Self-service customer portal",
            "Multiple payment gateways"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Dunning management",
            "Usage-based billing",
            "Revenue recognition compliance",
            "Advanced subscription analytics",
            "Consolidated invoicing"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Automating monthly invoicing",
            "Reducing churn from failed payments",
            "Handling plan changes correctly",
            "Letting customers manage their own accounts",
            "Recognizing revenue properly",
            "Tracking key metrics like MRR & churn",
            "Billing based on customer usage",
            "Managing sales tax for subscriptions",
            "Allowing customers to pause service",
            "Communicating billing events to customers"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered churn prediction",
            "AI-driven pricing recommendations",
            "Smart, adaptive dunning management",
            "Predictive customer LTV analysis",
            "AI-based upsell suggestions",
            "Automated revenue forecasting",
            "AI analysis of cancellation reasons",
            "Natural language billing analytics",
            "AI-driven retention offers",
            "Smart payment-to-invoice matching",
            "AI-powered revenue recovery insights",
            "Automated fraudulent sign-up detection",
            "AI suggestions for payment retry timing",
            "Billing support sentiment analysis",
            "AI 'what-if' analysis for pricing",
            "Smart alerts for metric changes",
            "AI-generated customer billing summaries",
            "Automated cohort analysis with insights",
            "AI recommendations for new plans",
            "Predictive analysis of customer upgrades"
          ]
        }
      ]
    },