import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Books": {
      sections: [
        {
          title: "Home",
          icon: <Home className="w-4 h-4" />,
          items: ["Dashboard", "Getting Started", "Announcements", "Recent Updates", "Custom Dashboards"]
        },
        {
          title: "Sales",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["Customers", "Invoices", "Sales Orders", "Quotes", "Delivery Challans", "Sales Receipts", "Credit Notes", "Payments Received", "Retainer Invoices"]
        },
        {
          title: "Purchases",
          icon: <Package className="w-4 h-4" />,
          items: ["Vendors", "Bills", "Purchase Orders", "Purchase Receives", "Vendor Credits", "Payments Made", "Expenses"]
        },
        {
          title: "Items",
          icon: <Package className="w-4 h-4" />,
          items: ["Items", "Price Lists", "Inventory Adjustments", "Composite Items", "Item Groups"]
        },
        {
          title: "Banking",
          icon: <Building2 className="w-4 h-4" />,
          items: ["Bank Accounts", "Deposits", "Withdrawals", "Bank Reconciliation", "Rules"]
        },
        {
          title: "Accountant",
          icon: <Calculator className="w-4 h-4" />,
          items: ["Chart of Accounts", "Manual Journals", "Bulk Updates", "Currencies", "Opening Balances"]
        },
        {
          title: "Projects",
          icon: <FileText className="w-4 h-4" />,
          items: ["Projects", "Time Tracking", "Project Expenses"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Financial Reports", "Sales Reports", "Purchase Reports", "Tax Reports", "Inventory Reports", "Account Reports", "Project Reports", "Custom Reports"]
        },
        {
          title: "More",
          icon: <MoreHorizontal className="w-4 h-4" />,
          items: ["Custom Modules", "Retainer Invoices", "Documents"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Organization Profile", "Users & Roles", "General Preferences", "Taxes", "Templates", "Online Payments", "Email Settings", "Import/Export", "Extensions", "Backup"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "One-click invoice aging report",
            "Customizable dashboard widgets",
            "\"Mark as Paid\" in invoice list view",
            "Bulk import for vendor contacts",
            "Toggle for automatic late fees"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Multi-currency cash flow forecasting",
            "Advanced project-based accounting",
            "Automated 1099 e-filing",
            "Direct payroll provider integration",
            "Comprehensive budgeting tool"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Solving poor cash flow visibility",
            "Simplifying multi-state sales tax",
            "Automating bank feed categorization",
            "Streamlining client payment reminders",
            "Managing project profitability",
            "Automating recurring subscription billing",
            "Providing reports for loan applications",
            "Simplifying retail inventory tracking",
            "Ensuring all project hours are billed",
            "Managing vendor bills efficiently"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered fraud detection",
            "Predictive cash flow forecasting",
            "Intelligent invoice data extraction",
            "AI-driven expense categorization",
            "Smart bank reconciliation suggestions",
            "AI financial health score",
            "Automated compliance audit trails",
            "AI chart of accounts recommendations",
            "Predictive customer payment behavior",
            "AI accounting question chatbot",
            "AI-driven expense reduction advice",
            "Automated duplicate record detection",
            "AI-powered sales tax rate suggestions",
            "Natural language report generation",
            "AI inventory reorder point suggestions",
            "Automated vendor risk assessment",
            "Predictive revenue forecasting",
            "AI-powered invoice-to-payment matching",
            "Smart alerts for spending anomalies",
            "AI-generated financial summaries"
          ]
        }
      ]
    },