import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"BugTracker": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Project Overview", "My Dashboard", "Team Dashboard", "Bug Statistics", "Recent Activity"]
        },
        {
          title: "Bugs",
          icon: <AlertCircle className="w-4 h-4" />,
          items: ["All Bugs", "Open Bugs", "Assigned to Me", "Recently Added", "Critical Bugs", "Resolved Bugs", "Closed Bugs"]
        },
        {
          title: "Projects",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Projects", "Active Projects", "My Projects", "Project Templates", "Archived Projects"]
        },
        {
          title: "Categories",
          icon: <Tag className="w-4 h-4" />,
          items: ["Bug Categories", "Severity Levels", "Priority Levels", "Custom Categories"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Bug Reports", "Project Reports", "User Activity Reports", "Custom Reports", "Analytics"]
        },
        {
          title: "Users",
          icon: <Users className="w-4 h-4" />,
          items: ["All Users", "User Groups", "User Roles", "User Activity", "Permissions"]
        },
        {
          title: "Forums",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["Discussion Forums", "Topics", "My Posts", "Popular Discussions"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["General Settings", "Email Settings", "Custom Fields", "Workflow Settings", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Simple bug submission form",
            "Customizable fields",
            "Assign bugs to team members",
            "Attach screenshots and files",
            "Email notifications"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable workflows",
            "Advanced bug reporting",
            "Code repository integration",
            "Help desk integration",
            "Time tracking on bugs"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Centralizing scattered bug reports",
            "Getting enough info to fix bugs",
            "Defining a clear bug-fixing process",
            "Prioritizing the most important bugs",
            "Preventing releases with critical bugs",
            "Linking customer tickets to bugs",
            "Understanding project health",
            "Syncing developers and QA",
            "Finding old bug reports",
            "Estimating time spent on bug fixes"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered duplicate bug detection",
            "Automated bug assignment",
            "AI suggestions for severity/priority",
            "Predictive time-to-fix analysis",
            "AI root cause analysis",
            "Smart suggestions for related bugs",
            "Automated bug categorization",
            "Natural language bug reporting",
            "AI analysis of code commits",
            "Sentiment analysis of bug reports",
            "AI 'reproducibility score'",
            "Automated bug report summaries",
            "Predictive analysis of buggy code areas",
            "AI recommendations for release planning",
            "Smart alerts for aging bugs",
            "AI chatbot for bug reporting guidance",
            "Automated translation of bug reports",
            "AI suggestions for test cases",
            "Predictive re-open analysis",
            "AI analysis of linked session recordings"
          ]
        }
      ]
    },