import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

    "Calendar": {
      sections: [
        {
          title: "Calendar Views",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Month View", "Week View", "Day View", "Agenda View", "Year View"]
        },
        {
          title: "Events",
          icon: <Clock className="w-4 h-4" />,
          items: ["All Events", "Create Event", "Recurring Events", "My Events", "Upcoming Events", "Past Events"]
        },
        {
          title: "Calendars",
          icon: <Grid className="w-4 h-4" />,
          items: ["My Calendars", "Shared Calendars", "Public Calendars", "Subscribed Calendars", "Calendar Settings"]
        },
        {
          title: "Tasks",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["All Tasks", "Today's Tasks", "Overdue Tasks", "Completed Tasks", "Task Lists"]
        },
        {
          title: "Meetings",
          icon: <Users className="w-4 h-4" />,
          items: ["Schedule Meeting", "Meeting Rooms", "Video Conferences", "Meeting History"]
        },
        {
          title: "Reminders",
          icon: <Bell className="w-4 h-4" />,
          items: ["All Reminders", "Email Reminders", "SMS Reminders", "Desktop Notifications"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["General Settings", "Notification Settings", "Sharing Settings", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Create & manage events",
            "Multiple calendar views",
            "Invite attendees",
            "Event reminders",
            "Recurring events"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Shared team calendars",
            "Group calendars",
            "Video conferencing integration",
            "Resource (meeting room) booking",
            "Two-way sync with other calendars"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Finding a meeting time for a group",
            "Managing work and personal schedules",
            "Forgetting appointments",
            "Booking an available meeting room",
            "Keeping a team aware of deadlines",
            "Scheduling with external parties",
            "Adding video call links to invites",
            "Accessing your schedule on mobile",
            "Syncing multiple calendar services",
            "Simplifying RSVP responses"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered smart scheduling",
            "Natural language event creation",
            "AI suggestions for attendees",
            "Automated meeting agenda creation",
            "AI 'time to leave' traffic alerts",
            "Smart event categorization",
            "AI analysis of your time usage",
            "Predictive meeting acceptance rates",
            "AI resolution of scheduling conflicts",
            "Smart recurring event suggestions",
            "AI recommendations for meeting rooms",
            "Automated action item follow-ups",
            "AI-powered 'focus time' blocking",
            "Smart alerts for back-to-back meetings",
            "AI insights into meeting habits",
            "Automated room booking",
            "AI suggestions for invitees",
            "Smart parsing of event details from email",
            "AI 'best time' suggestions for teams",
            "Automated rescheduling assistant"
          ]
        }
      ]
    }