import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Campaigns": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Campaign Analytics", "Performance Overview", "Customized Dashboard", "Recent Activity"]
        },
        {
          title: "Campaigns",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Email Campaigns", "SMS Campaigns", "A/B Testing", "Event Platform Integration", "Send Immediately", "Schedule Campaigns", "Batch Sending"]
        },
        {
          title: "Contacts",
          icon: <Users className="w-4 h-4" />,
          items: ["List Management", "Dynamic Segments", "Exclusion Lists", "Zoho CRM Sync", "Custom Fields", "Signup Forms", "Permission-based Marketing"]
        },
        {
          title: "Automation",
          icon: <Zap className="w-4 h-4" />,
          items: ["Drip Campaigns", "Workflow Builder", "Lead Scoring", "Triggered Actions", "Behavior-based Sequences"]
        },
        {
          title: "Templates",
          icon: <Palette className="w-4 h-4" />,
          items: ["Mobile-responsive Templates", "Custom HTML", "Drag-and-drop Builder", "Image Editing", "Merge Tags", "Template Library"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Real-time Analytics", "A/B Test Results", "Litmus Integration", "Campaign Performance", "Version History"]
        },
        {
          title: "Social Integration",
          icon: <Share2 className="w-4 h-4" />,
          items: ["Facebook Promotion", "Twitter Integration", "LinkedIn Sharing", "Social Media Analytics"]
        },
        {
          title: "Integrations",
          icon: <Link2 className="w-4 h-4" />,
          items: ["Zoho Ecosystem", "WooCommerce", "Shopify", "Zapier Integration", "50+ App Integrations"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Dashboard Customization", "Sender Authentication", "Data Management", "Team Collaboration", "Template Management"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Emoji support in subject lines",
            "One-click \"resend to unopens\"",
            "A/B testing for sender name",
            "Pre-built holiday templates",
            "Dark mode for campaign editor"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Integrated SMS marketing",
            "Advanced visual workflow builder",
            "Predictive sending optimization",
            "Built-in landing page creator",
            "Native e-commerce integrations"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Improving email deliverability",
            "Advanced contact list segmentation",
            "Automating welcome email series",
            "Measuring campaign ROI",
            "Creating mobile-responsive emails",
            "Managing list growth & unsubscribes",
            "Personalizing content at scale",
            "Re-engaging inactive subscribers",
            "Ensuring GDPR/CAN-SPAM compliance",
            "A/B testing to improve engagement"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered subject line generator",
            "AI-driven content personalization",
            "Predictive campaign success scoring",
            "Smart behavioral segmentation",
            "AI-powered send time optimization",
            "Automated A/B test winner selection",
            "AI-based template recommendations",
            "Predictive subscriber churn analysis",
            "AI-powered newsletter content summarization",
            "Automated image selection for emails",
            "Sentiment analysis of email replies",
            "AI-generated email copy variations",
            "Predictive lead scoring integration",
            "AI-driven follow-up campaign recommendations",
            "Automated list hygiene suggestions",
            "AI-powered pre-send spam score checker",
            "Natural language campaign setup",
            "AI-based CTA text suggestions",
            "Predictive content type performance",
            "Automated reports with actionable insights"
          ]
        }
      ]
    },