import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Catalyst": {
      sections: [
        {
          title: "Functions",
          icon: <Code className="w-4 h-4" />,
          items: ["All Functions", "HTTP Functions", "Cron Functions", "Event Functions", "Function Templates", "Function Logs", "Cloud Functions", "Function Metrics", "Event Triggers", "Cron Jobs"]
        },
        {
          title: "Database",
          icon: <Database className="w-4 h-4" />,
          items: ["Tables", "Data Browser", "Query Builder", "Database Backup", "Migrations", "Database Analytics", "Data Store", "File Store", "Cache", "Search"]
        },
        {
          title: "Deployments",
          icon: <Upload className="w-4 h-4" />,
          items: ["Project Deployments", "Version History", "Build Logs", "Environment Variables", "Custom Domains"]
        },
        {
          title: "File Storage",
          icon: <Folder className="w-4 h-4" />,
          items: ["File Manager", "Upload Files", "Download Files", "File Permissions", "Storage Analytics"]
        },
        {
          title: "Authentication",
          icon: <Lock className="w-4 h-4" />,
          items: ["User Management", "Auth Settings", "Social Login", "Custom Authentication", "Security Rules", "Authentication Methods", "User Roles", "Security Settings"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Function Analytics", "Database Analytics", "Performance Metrics", "Error Tracking", "Usage Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Project Settings", "Environment Settings", "API Settings", "Team Settings", "Billing"]
        },
        {
          title: "Projects",
          icon: <Folder className="w-4 h-4" />,
          items: ["All Projects", "Web Apps", "Mobile Apps", "Microservices", "Project Templates"]
        },
        {
          title: "API Management",
          icon: <Code className="w-4 h-4" />,
          items: ["API Gateway", "API Documentation", "Rate Limiting", "API Analytics", "Webhooks"]
        },
        {
          title: "DevOps",
          icon: <GitBranch className="w-4 h-4" />,
          items: ["CI/CD Pipeline", "Git Integration", "Environment Management", "Build Logs", "Deployment History"]
        },
        {
          title: "Monitoring",
          icon: <Monitor className="w-4 h-4" />,
          items: ["Application Logs", "Performance Monitoring", "Error Tracking", "Uptime Monitoring", "Alerts"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Deploy serverless functions",
            "Simple key-value data store",
            "Host static web assets",
            "CLI for local development",
            "Function & API logs"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Fully managed infrastructure",
            "Built-in user authentication",
            "Scheduled cron jobs",
            "API gateway",
            "User file storage"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Avoiding server management",
            "Building a scalable backend",
            "Implementing user authentication",
            "Storing data without a DB admin",
            "Running scheduled background tasks",
            "Building and securing APIs",
            "Matching dev and prod environments",
            "Storing user-uploaded files",
            "Monitoring a serverless app",
            "Getting an app to market quickly"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered code suggestions",
            "Smart performance bottleneck detection",
            "AI security vulnerability scanning",
            "Predictive cost analysis",
            "Natural language deployment commands",
            "AI optimization of function settings",
            "Automated API documentation",
            "AI-powered log analysis",
            "Smart data modeling suggestions",
            "AI architecture recommendations",
            "Automated code refactoring",
            "AI 'what-if' cost analysis",
            "Smart alerts for unusual activity",
            "AI-assisted platform migration",
            "Predictive autoscaling advice",
            "AI developer support chatbot",
            "Automated unit test generation",
            "Smart infinite loop detection",
            "AI insights into API usage",
            "Automated security policy generation"
          ]
        }
      ]
    },