import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Commerce": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Store Overview", "Sales Dashboard", "Analytics Dashboard", "Performance Metrics", "Quick Actions"]
        },
        {
          title: "Products",
          icon: <Package className="w-4 h-4" />,
          items: ["All Products", "Add Product", "Categories", "Brands", "Variants", "Bulk Import", "Product Reviews", "Digital Products"]
        },
        {
          title: "Orders",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["All Orders", "Pending Orders", "Processing Orders", "Shipped Orders", "Delivered Orders", "Cancelled Orders", "Returns", "Refunds"]
        },
        {
          title: "Customers",
          icon: <Users className="w-4 h-4" />,
          items: ["All Customers", "Customer Groups", "Customer Reviews", "Wishlist", "Customer Analytics", "Loyalty Program"]
        },
        {
          title: "Inventory",
          icon: <Database className="w-4 h-4" />,
          items: ["Stock Management", "Low Stock Alerts", "Inventory Reports", "Stock Adjustments", "Warehouses", "Transfers"]
        },
        {
          title: "Marketing",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Campaigns", "Coupons & Discounts", "Email Marketing", "SEO Tools", "Social Media", "Abandoned Cart Recovery"]
        },
        {
          title: "Payments",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["Payment Methods", "Transaction History", "Payment Reports", "Gateway Settings", "Refund Management"]
        },
        {
          title: "Shipping",
          icon: <Truck className="w-4 h-4" />,
          items: ["Shipping Methods", "Shipping Zones", "Shipping Labels", "Tracking", "Shipping Reports", "Carriers"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Sales Reports", "Product Reports", "Customer Reports", "Inventory Reports", "Financial Reports", "Custom Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Store Settings", "Payment Settings", "Shipping Settings", "Tax Settings", "Theme Customization", "Integrations"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "E-commerce website builder",
            "Product management",
            "Built-in shopping cart",
            "Order management dashboard",
            "Discount code creation"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Multiple payment gateways",
            "Real-time shipping calculation",
            "Multi-warehouse inventory",
            "Abandoned cart recovery",
            "Back-office app integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Building an online store easily",
            "Managing inventory automatically",
            "Calculating accurate shipping rates",
            "Recovering abandoned carts",
            "Marketing an online store",
            "Handling e-commerce accounting",
            "Providing customer support",
            "Processing orders efficiently",
            "Accepting various payment types",
            "Analyzing store performance"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI product recommendations",
            "AI-generated product descriptions",
            "Dynamic pricing optimization",
            "AI-powered store search",
            "Predictive customer LTV analysis",
            "AI-driven order fraud detection",
            "Smart customer churn prediction",
            "AI personalization of shopping",
            "Automated marketing copy generation",
            "AI demand forecasting",
            "Product review sentiment analysis",
            "AI customer service chatbot",
            "Smart upsell/cross-sell suggestions",
            "AI-driven audience segmentation",
            "Automated product image tagging",
            "AI-powered 'visual search'",
            "Predictive return rate analysis",
            "AI optimization of store layout",
            "Smart sales trend alerts",
            "AI-generated insights from analytics"
          ]
        }
      ]
    },