import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Connect": {
      sections: [
        {
          title: "Home",
          icon: <Home className="w-4 h-4" />,
          items: ["Activity Feed", "News & Updates", "Trending Topics", "Company Announcements"]
        },
        {
          title: "Groups",
          icon: <Users className="w-4 h-4" />,
          items: ["My Groups", "All Groups", "Create Group", "Group Directory", "Group Analytics"]
        },
        {
          title: "Forums",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Discussion Forums", "Q&A Forums", "Knowledge Sharing", "Expert Networks"]
        },
        {
          title: "Events",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Upcoming Events", "Create Event", "Event Calendar", "Event Registration", "Virtual Events"]
        },
        {
          title: "Knowledge Base",
          icon: <BookOpen className="w-4 h-4" />,
          items: ["Articles", "Wikis", "Best Practices", "Training Materials", "Resource Library"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Engagement Metrics", "User Activity", "Content Performance", "Network Analysis"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Central activity feed",
            "Employee profiles",
            "Team/interest groups",
            "Quick polls",
            "Likes and comments"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Shared knowledge base",
            "Discussion forums",
            "Company-wide calendar",
            "Automated update integrations",
            "Custom approval workflows"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Reducing internal email noise",
            "Breaking down team silos",
            "Improving new hire onboarding",
            "Preventing knowledge loss",
            "Building company culture remotely",
            "Finding the right expert",
            "Encouraging employee feedback",
            "Organizing company events",
            "Consolidating communication tools",
            "Getting feedback on new ideas"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI feed summarization",
            "Smart group suggestions",
            "AI-based expert finding",
            "Employee morale sentiment analysis",
            "AI-powered content moderation",
            "Automated post topic tagging",
            "AI knowledge base recommendations",
            "Predictive employee engagement analytics",
            "AI chatbot for policy questions",
            "Natural language user search",
            "AI 'icebreaker' question generation",
            "Smart identification of emerging leaders",
            "AI-powered post translation",
            "Automated weekly 'digest' generation",
            "AI-based skill gap analysis",
            "Predictive disengagement analysis",
            "Smart content sharing recommendations",
            "AI-powered event suggestions",
            "Automated duplicate KB article detection",
            "AI insights into informal networks"
          ]
        }
      ]
    }