import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Creator": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["App Overview", "Usage Analytics", "Performance Stats", "Recent Activities"]
        },
        {
          title: "Applications",
          icon: <Code className="w-4 h-4" />,
          items: ["My Apps", "Published Apps", "Draft Apps", "App Templates", "Shared Apps"]
        },
        {
          title: "Builder",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Form Builder", "Report Builder", "Workflow Builder", "Page Builder", "Script Editor"]
        },
        {
          title: "Data",
          icon: <Database className="w-4 h-4" />,
          items: ["Data Management", "Import/Export", "Data Validation", "Relationships", "Lookup Fields"]
        },
        {
          title: "Automation",
          icon: <Zap className="w-4 h-4" />,
          items: ["Workflows", "Triggers", "Scheduled Actions", "Email Notifications", "Webhooks"]
        },
        {
          title: "Integration",
          icon: <Link2 className="w-4 h-4" />,
          items: ["API Access", "Third-party Integrations", "Zapier", "Custom Connections"]
        },
        {
          title: "Publishing",
          icon: <Upload className="w-4 h-4" />,
          items: ["App Deployment", "User Management", "Access Control", "Mobile Apps"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Drag-and-drop app builder",
            "Data collection forms",
            "Reports and dashboards",
            "Pre-built app templates",
            "Automatic mobile apps"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Deluge scripting language",
            "Integration with other apps",
            "Advanced user management",
            "Cross-platform deployment",
            "Scalable cloud hosting"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Building apps for unique processes",
            "Replacing spreadsheet-based systems",
            "Empowering business users to build tools",
            "Digitizing manual, paper processes",
            "Creating mobile apps for field staff",
            "Integrating disparate cloud services",
            "Controlling access to sensitive data",
            "Accelerating app development",
            "Visualizing business data",
            "Managing app hosting and maintenance"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI app generation from text/sheets",
            "Zia: AI data assistant",
            "AI suggestions for app improvement",
            "Smart data cleansing on import",
            "AI-powered OCR for form creation",
            "Predictive analytics in reports",
            "AI code completion for Deluge",
            "Automated dashboard generation",
            "AI app performance monitoring",
            "Natural language form building",
            "AI security vulnerability scanning",
            "Smart relationship suggestions",
            "AI user behavior analytics",
            "Automated app translation",
            "AI template recommendations",
            "Sentiment analysis of user feedback",
            "AI-powered 'what-if' analysis",
            "Automated redundant workflow detection",
            "AI-assisted platform migration",
            "Embeddable AI chatbot for apps"
          ]
        }
      ]
    }