import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Directory" {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Organization Overview", "User Activity", "Device Status", "Security Summary"]
        },
        {
          title: "Users",
          icon: <Users className="w-4 h-4" />,
          items: ["All Users", "User Profiles", "User Groups", "Organizational Units", "User Import"]
        },
        {
          title: "Devices",
          icon: <Smartphone className="w-4 h-4" />,
          items: ["All Devices", "Device Groups", "Device Policies", "Device Compliance"]
        },
        {
          title: "Applications",
          icon: <Grid className="w-4 h-4" />,
          items: ["App Management", "App Deployment", "App Policies", "App Usage Analytics"]
        },
        {
          title: "Security",
          icon: <Shield className="w-4 h-4" />,
          items: ["Access Control", "Security Policies", "Threat Detection", "Compliance Monitoring"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["User Reports", "Device Reports", "Security Reports", "Compliance Reports"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Central user directory",
            "User password self-service",
            "Basic user provisioning",
            "Company app launcher",
            "Login audit logs"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Single Sign-On (SSO)",
            "Multi-Factor Authentication (MFA)",
            "Security policy enforcement",
            "Mobile Device Management (MDM)",
            "Automated HR integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Managing user accounts everywhere",
            "Solving employee password fatigue",
            "Automating new hire account setup",
            "Instantly revoking ex-employee access",
            "Enforcing strong password policies",
            "Securing lost or stolen devices",
            "Granting role-based app access",
            "Auditing 'who has access to what'",
            "Simplifying access to work apps",
            "Syncing users from an HR system"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered risk-based access",
            "Behavioral analytics for security",
            "AI user-to-group recommendations",
            "Smart 'shadow IT' detection",
            "AI analysis of audit logs",
            "Predictive user risk scoring",
            "Automated access review campaigns",
            "AI security policy recommendations",
            "Natural language admin search",
            "AI-powered access request approvals",
            "Smart dormant account identification",
            "AI insights for license optimization",
            "Impossible travel login detection",
            "AI chatbot for user self-service",
            "Predictive access needs modeling",
            "AI 'least privilege' recommendations",
            "Smart user behavior grouping",
            "AI phishing simulation integration",
            "Automated compliance report generation",
            "AI insights on identity lifecycle"
          ]
        }
      ]
    }