import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

    "Embedded BI": {
      sections: [
        {
          title: "Embeds",
          icon: <Code className="w-4 h-4" />,
          items: ["All Embeds", "Dashboard Embeds", "Report Embeds", "Chart Embeds", "Widget Embeds", "Custom Embeds"]
        },
        {
          title: "APIs",
          icon: <Link2 className="w-4 h-4" />,
          items: ["API Documentation", "REST APIs", "JavaScript APIs", "SDK Downloads", "API Testing", "Authentication"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Usage Analytics", "Performance Metrics", "User Analytics", "Embed Analytics", "API Analytics"]
        },
        {
          title: "White-label",
          icon: <Palette className="w-4 h-4" />,
          items: ["Branding Options", "Custom Themes", "Logo Management", "Color Schemes", "UI Customization"]
        },
        {
          title: "Data Sources",
          icon: <Database className="w-4 h-4" />,
          items: ["Connect Data", "Database Connections", "File Uploads", "Cloud Connectors", "Data Refresh"]
        },
        {
          title: "Security",
          icon: <Shield className="w-4 h-4" />,
          items: ["Access Control", "Domain Management", "User Authentication", "Encryption Settings", "Security Policies"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Embed Settings", "API Settings", "Integration Settings", "Account Settings", "Billing"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Embed a single chart",
            "JavaScript API",
            "Embedding management dashboard",
            "Pass filters to dashboards",
            "White-labeling"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Fully re-branded BI portal",
            "Robust API set",
            "Single Sign-On (SSO) integration",
            "Secure multi-tenant framework",
            "Embeddable report creator"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Avoiding building analytics from scratch",
            "Keeping users inside your app",
            "Providing secure analytics to customers",
            "Allowing users to create own reports",
            "Maintaining a consistent brand",
            "Managing users for embedded BI",
            "Controlling dashboards programmatically",
            "Adding value to a SaaS product",
            "Visualizing your application's data",
            "Scaling analytics as you grow"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "Expose 'Ask Zia' via API",
            "AI suggestions for reports to embed",
            "Automated insight narratives via API",
            "AI anomaly detection with webhooks",
            "Embeddable predictive analytics",
            "AI recommendations for end-users",
            "Embedded natural language querying",
            "AI-powered data preparation for users",
            "Smart UI design suggestions",
            "AI-based usage analytics",
            "Automated API code generation",
            "Embeddable 'what-if' analysis",
            "Smart security recommendations",
            "Embeddable forecasting",
            "Automated personalized dashboards",
            "AI-powered embedded support chatbot",
            "Smart performance caching",
            "AI insights into user interaction",
            "Automated broken report detection",
            "AI-based data storytelling"
          ]
        }
      ]
    }
    