import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
 "Expense": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Expense Overview", "Pending Approvals", "Monthly Summary", "Quick Actions"]
        },
        {
          title: "Expenses",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["All Expenses", "My Expenses", "Team Expenses", "Recurring Expenses", "Mileage Tracking"]
        },
        {
          title: "Receipts",
          icon: <Camera className="w-4 h-4" />,
          items: ["Receipt Capture", "Auto-Scan", "Receipt Matching", "Receipt Storage", "Mobile Upload"]
        },
        {
          title: "Approvals",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Pending Approvals", "Approval Workflows", "Rejected Expenses", "Approved Expenses"]
        },
        {
          title: "Reimbursements",
          icon: <DollarSign className="w-4 h-4" />,
          items: ["Pending Reimbursements", "Payment Processing", "Reimbursement History", "Payment Methods"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Expense Reports", "Category Reports", "Employee Reports", "Tax Reports", "Custom Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Expense Policies", "Categories", "Approval Rules", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Mileage Tracker",
            "Quick Expense Entry",
            "Duplicate Expense Detection",
            "Mobile Approvals",
            "Split Personal/Business Expenses"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Corporate Card Reconciliation",
            "ERP/Accounting Integration",
            "Per Diem & Travel Allowance Management",
            "Direct Payroll Integration",
            "Built-in Tax Compliance"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Receipt Auto-Categorization",
            "Expense Policy Reminders",
            "Automated Approval Workflows",
            "Advanced Analytics & Insights",
            "Real-time Receipt Capture",
            "Smart Scan for Reports",
            "Real-time Policy Checks",
            "Project-based Expense Tagging",
            "Centralized Spend Dashboard",
            "Automatic Currency Conversion"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-Powered Anomaly Detection",
            "Predictive Budgeting",
            "Intelligent Policy Advisor",
            "Voice-Powered Expense Creation",
            "Automated Itinerary-Based Reporting",
            "AI Chatbot for Support",
            "Vendor Negotiation Insights",
            "Personalized Spending Insights",
            "Automated Receipt Translation",
            "Gamified Savings Goals",
            "AI-Powered Receipt Data Extraction",
            "Automated Expense Report Generation",
            "Predictive Expense Forecasting",
            "Intelligent Policy Violation Detection",
            "AI-driven Spend Optimization",
            "Automated Expense Categorization",
            "Smart Trip-based Expense Bundling",
            "AI-powered Approval Workflow Suggestions",
            "Personalized Employee Expense Insights",
            "Automated Fraud Detection"
          ]
        }
      ]
    }