import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Forms": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Form Overview", "Submission Stats", "Performance Metrics", "Recent Submissions", "Quick Actions"]
        },
        {
          title: "All Forms",
          icon: <FileText className="w-4 h-4" />,
          items: ["My Forms", "Shared Forms", "Published Forms", "Draft Forms", "Archived Forms", "Deleted Forms"]
        },
        {
          title: "Form Builder",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Drag & Drop Builder", "Field Library", "Design Themes", "Logic & Rules", "Conditional Logic", "Multi-page Forms"]
        },
        {
          title: "Templates",
          icon: <Copy className="w-4 h-4" />,
          items: ["Form Templates", "Industry Templates", "Custom Templates", "Template Gallery", "Template Builder"]
        },
        {
          title: "Submissions",
          icon: <Inbox className="w-4 h-4" />,
          items: ["All Submissions", "Recent Submissions", "Export Data", "Submission Details", "Data Validation", "Duplicate Detection"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Form Analytics", "Submission Reports", "Conversion Rates", "Field Analytics", "Drop-off Analysis", "Time Analytics"]
        },
        {
          title: "Integrations",
          icon: <Link2 className="w-4 h-4" />,
          items: ["CRM Integration", "Email Marketing", "Payment Gateways", "Webhooks", "API Access", "Third-party Apps"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Account Settings", "Form Settings", "Notification Settings", "Security Settings", "User Management"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Real-time Submission Counter",
            "Customizable \"Thank You\" Pages",
            "Field Validation Rules",
            "Save and Resume Later",
            "Basic Form Templates"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Multi-page Forms with Conditional Logic",
            "Payment Integration (Stripe, PayPal)",
            "Advanced Reporting & Analytics",
            "Offline Form Submission",
            "Document Upload & Attachment"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Low Form Completion Rates",
            "Spam Submissions",
            "Integrating Form Data with Other Apps",
            "Creating Mobile-Responsive Forms",
            "Securely Handling Sensitive Data",
            "Automating Post-Submission Workflows",
            "Analyzing Form Performance",
            "Making Forms Accessible (WCAG)",
            "Collaborating on Form Creation",
            "Collecting Payments through Forms"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-Powered Form Generation from a Description",
            "Predictive Field Validation",
            "Automated Spam Detection",
            "AI-driven Form Layout Optimization",
            "Smart Field Suggestions",
            "AI-assisted Response Analysis",
            "Automated PDF Conversion to Forms",
            "Predictive Conversion Rate Analysis",
            "AI-powered Conditional Logic Builder",
            "Voice-to-Text Form Filling",
            "AI-based A/B testing for form fields",
            "Sentiment analysis of open-text feedback",
            "AI-powered form-to-database schema generation",
            "Predictive analytics on form abandonment",
            "AI-driven recommendations for form templates",
            "Automated translation of form fields and labels",
            "AI-powered image analysis for uploaded files (e.g., OCR)",
            "Smart CAPTCHA alternatives",
            "AI-generated summary reports of form submissions",
            "Natural language form creation"
          ]
        }
      ]
    },