import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"FSM": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Field Service Overview", "Technician Performance", "Job Analytics", "Revenue Metrics"]
        },
        {
          title: "Work Orders",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Work Orders", "Open Orders", "Scheduled Orders", "Completed Orders", "Recurring Orders", "Emergency Orders"]
        },
        {
          title: "Scheduling",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Dispatch Board", "Technician Calendar", "Auto-scheduling", "Route Optimization", "Appointment Booking"]
        },
        {
          title: "Technicians",
          icon: <Users className="w-4 h-4" />,
          items: ["Technician Management", "Skills Matrix", "Availability", "Performance Tracking", "Mobile App"]
        },
        {
          title: "Inventory",
          icon: <Package className="w-4 h-4" />,
          items: ["Parts Management", "Stock Levels", "Purchase Orders", "Supplier Management", "Inventory Tracking"]
        },
        {
          title: "Customers",
          icon: <Users className="w-4 h-4" />,
          items: ["Customer Database", "Service History", "Equipment Records", "Contracts", "Customer Portal"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Service Reports", "Technician Reports", "Revenue Reports", "Inventory Reports", "Custom Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Service Types", "SLA Configuration", "Mobile Settings", "Integration", "Billing Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Create work orders",
            "Technician schedule board",
            "Technician mobile app",
            "Capture customer signatures",
            "Customer database"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Intelligent scheduling & dispatch",
            "Route optimization",
            "Inventory management",
            "Service contract management",
            "Accounting integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Inefficient technician scheduling",
            "Technicians arriving late",
            "Not having the right parts for a job",
            "Losing paper-based work orders",
            "Poor communication with field techs",
            "Providing accurate arrival times",
            "Slow, manual invoicing process",
            "Managing recurring maintenance",
            "Proving a job was completed",
            "Understanding service profitability"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered predictive scheduling",
            "Predictive maintenance alerts",
            "AI-based technician recommendations",
            "Smart problem diagnosis",
            "AI-driven parts recommendations",
            "Natural language work order creation",
            "AI analysis of service reports",
            "Predictive job completion times",
            "AI-based technician safety alerts",
            "Automated customer feedback analysis",
            "AI-powered inventory forecasting",
            "Smart, traffic-adaptive routing",
            "AI-generated customer service reports",
            "Automated parts validation",
            "AI-powered upsell suggestions",
            "Customer communication sentiment analysis",
            "AI-based service request triage",
            "Smart scheduling of filler tasks",
            "AI analysis of technician performance",
            "Automated voice-to-text for updates"
          ]
        }
      ]
    }