import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Invoice": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Sales Overview", "Receivables Summary", "Top Projects", "Business Metrics", "Real-time Sync"]
        },
        {
          title: "Invoices",
          icon: <FileText className="w-4 h-4" />,
          items: ["Create Invoice", "All Invoices", "Draft Invoices", "Sent Invoices", "Paid Invoices", "Overdue Invoices", "Batch Operations", "Advanced Search"]
        },
        {
          title: "Customers",
          icon: <Users className="w-4 h-4" />,
          items: ["All Customers", "Customer Portal", "Customer Statements", "Credit Limit Management", "Payment Information", "Multi-factor Authentication"]
        },
        {
          title: "Items",
          icon: <Package className="w-4 h-4" />,
          items: ["Product Catalog", "Service Items", "Item Categories", "Import Items", "Import Overwrite"]
        },
        {
          title: "Quotes",
          icon: <FileCheck className="w-4 h-4" />,
          items: ["Create Estimate", "All Quotes", "Professional Quotes", "Quote Templates"]
        },
        {
          title: "Recurring Invoices",
          icon: <RefreshCw className="w-4 h-4" />,
          items: ["Automated Billing", "Recurring Templates", "Subscription Management"]
        },
        {
          title: "Credit Notes",
          icon: <FileX className="w-4 h-4" />,
          items: ["Refund Management", "Credit Adjustments", "Credit Note Templates"]
        },
        {
          title: "Expenses",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["Track Expenses", "Expense Categories", "Billable Expenses", "Receipt Management"]
        },
        {
          title: "Timesheets",
          icon: <Clock className="w-4 h-4" />,
          items: ["Time Tracking", "Project Billing", "Timesheet Reports"]
        },
        {
          title: "Projects",
          icon: <Folder className="w-4 h-4" />,
          items: ["Project Management", "Revenue Tracking", "Project Reports"]
        },
        {
          title: "Payment Links",
          icon: <Link2 className="w-4 h-4" />,
          items: ["Standalone Payment Collection", "Payment Link Management"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Financial Reports", "Invoice Analytics", "Payment Reports", "Tax Reports", "Custom Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Organization Profile", "User Management", "Custom Fields", "Templates", "Payment Gateways", "Integrations", "Digital Signatures"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable invoice templates",
            "\"Mark as Sent\" status",
            "Recurring invoice profiles",
            "Simple billable hours timer",
            "Accept online payments"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Multi-currency invoicing",
            "Client payment portal",
            "Automated payment reminders",
            "Advanced sales tax compliance",
            "Integration with accounting software"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Reducing time spent creating invoices",
            "Handling late-paying clients",
            "Creating professional-looking invoices",
            "Tracking paid vs. overdue invoices",
            "Calculating sales tax automatically",
            "Billing clients for expenses",
            "Converting quotes to invoices",
            "Providing clients with payment history",
            "Tracking time for service projects",
            "Managing refunds with credit notes"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI prediction of invoice payment dates",
            "Smart due date suggestions",
            "AI-optimized reminder timing",
            "Automated expense categorization",
            "AI fraud detection for payments",
            "Intelligent data extraction from POs",
            "AI recommendations for early payment discounts",
            "Natural language invoice creation",
            "AI summary of outstanding receivables",
            "Predictive analysis of late payers",
            "AI-assisted dunning management",
            "Smart payment-to-invoice matching",
            "AI-powered cash flow forecasting",
            "Automated 'thank you' notes",
            "AI insights into revenue trends",
            "Intelligent invoice error checking",
            "AI suggestions for item descriptions",
            "Automated real-time currency conversion",
            "AI analysis of client payment patterns",
            "Smart alerts for viewed-but-unpaid invoices"
          ]
        }
      ]
    },