import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"IoT": {
      sections: [
        {
          title: "Devices",
          icon: <Smartphone className="w-4 h-4" />,
          items: ["All Devices", "Device Registry", "Device Status", "Device Groups", "Device Configuration", "Device Logs", "Online Devices", "Offline Devices", "Device Management", "Firmware Updates"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Device Analytics", "Data Visualization", "Performance Metrics", "Usage Analytics", "Predictive Analytics", "Custom Dashboards"]
        },
        {
          title: "Monitoring",
          icon: <Monitor className="w-4 h-4" />,
          items: ["Real-time Monitoring", "Device Health", "Performance Monitoring", "Alert Management", "System Status"]
        },
        {
          title: "Data Management",
          icon: <Database className="w-4 h-4" />,
          items: ["Data Streams", "Data Storage", "Data Processing", "Data Export", "Data Quality", "Live Data", "Historical Data"]
        },
        {
          title: "Alerts & Rules",
          icon: <Bell className="w-4 h-4" />,
          items: ["Alert Rules", "Notifications", "Threshold Settings", "Automated Actions", "Escalation Rules", "Active Alerts", "Alert History"]
        },
        {
          title: "Integration",
          icon: <Link2 className="w-4 h-4" />,
          items: ["API Integration", "Third-party Connectors", "Data Export", "Webhook Configuration", "Custom Integration"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Device Settings", "Data Settings", "Security Settings", "User Management", "Account Settings"]
        },
        {
          title: "Automation",
          icon: <Zap className="w-4 h-4" />,
          items: ["Automation Rules", "Triggers", "Actions", "Workflows", "Scenarios"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Device registry",
            "Device status dashboard",
            "Simple alerts",
            "Send commands to devices",
            "View real-time data streams"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Over-the-air (OTA) firmware updates",
            "Data-driven rules engine",
            "Time-series data storage",
            "IoT data dashboards",
            "API & webhook integrations"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Managing thousands of remote devices",
            "Updating software on devices in the field",
            "Reacting instantly to sensor thresholds",
            "Storing and querying time-series data",
            "Making sense of device data",
            "Securing device communication",
            "Integrating IoT data with business apps",
            "Monitoring device fleet health",
            "Building a custom IoT backend",
            "Remotely controlling devices"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered predictive maintenance",
            "Anomaly detection in sensor data",
            "AI optimization of device battery life",
            "Predictive device failure analysis",
            "AI-driven root cause analysis",
            "Natural language data queries",
            "AI-powered sensor calibration",
            "Smart alerts with reduced false positives",
            "AI suggestions for new IoT use cases",
            "Automated device classification",
            "AI-powered 'digital twin' modeling",
            "Predictive resource consumption forecasting",
            "AI insights into operational efficiency",
            "Self-learning automation rules",
            "AI-powered IoT network security",
            "Automated device performance reports",
            "AI pattern recognition in sensor data",
            "Smart data transmission optimization",
            "AI troubleshooting chatbot",
            "Automated firmware update scheduling"
          ]
        }
      ]
    },