import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"LandingPage": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Page Overview", "Conversion Analytics", "Traffic Stats", "Performance Summary"]
        },
        {
          title: "Pages",
          icon: <Globe className="w-4 h-4" />,
          items: ["All Pages", "Published Pages", "Draft Pages", "Page Templates", "Mobile Pages"]
        },
        {
          title: "Builder",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Page Builder", "Design Elements", "Layout Templates", "Custom Code", "Media Library"]
        },
        {
          title: "Forms",
          icon: <FileText className="w-4 h-4" />,
          items: ["Lead Forms", "Contact Forms", "Subscription Forms", "Custom Forms", "Form Analytics"]
        },
        {
          title: "A/B Testing",
          icon: <Target className="w-4 h-4" />,
          items: ["Create Tests", "Running Tests", "Test Results", "Winner Selection", "Test History"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Conversion Analytics", "Traffic Sources", "Visitor Behavior", "Performance Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Domain Settings", "SEO Settings", "Integration Settings", "Publishing Options"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Landing page templates",
            "Drag-and-drop builder",
            "Built-in lead forms",
            "Stock image gallery",
            "Mobile-responsive designs"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "A/B testing",
            "Analytics integration",
            "Dynamic text replacement",
            "CRM & email integration",
            "Fast page hosting"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Building landing pages without code",
            "Optimizing low conversion rates",
            "Matching ad copy to page content",
            "Automating lead export",
            "Fixing slow page load times",
            "Designing pages from scratch",
            "Ensuring pages are mobile-friendly",
            "Creating campaign pages quickly",
            "Understanding user behavior on page",
            "Reducing form abandonment"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered copy generation",
            "AI design & layout suggestions",
            "Predictive conversion analysis",
            "AI recommendations for A/B tests",
            "Smart A/B test traffic allocation",
            "AI-powered content personalization",
            "Automated image suggestions",
            "AI-generated trust signals",
            "Natural language page building",
            "AI competitor page analysis",
            "Predictive form abandonment analysis",
            "AI suggestions for speed improvement",
            "Automated meta description generation",
            "AI copy 'persuasiveness' score",
            "Embeddable smart chatbot",
            "AI page generation from URL",
            "Predictive lead scoring",
            "AI insights from visitor data",
            "Automated broken element detection",
            "AI recommendations for form length"
          ]
        }
      ]
    }