import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Learn": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Learning Overview", "Progress Tracking", "Course Analytics", "Recent Activities"]
        },
        {
          title: "Courses",
          icon: <GraduationCap className="w-4 h-4" />,
          items: ["All Courses", "My Courses", "Course Catalog", "Course Creation", "Course Library"]
        },
        {
          title: "Learning Paths",
          icon: <Map className="w-4 h-4" />,
          items: ["Learning Paths", "Skill Tracks", "Certification Programs", "Custom Paths"]
        },
        {
          title: "Assessments",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Quizzes", "Assignments", "Exams", "Certifications", "Skill Assessments"]
        },
        {
          title: "Social Learning",
          icon: <Users className="w-4 h-4" />,
          items: ["Discussion Forums", "Study Groups", "Peer Reviews", "Knowledge Sharing"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Learning Analytics", "Progress Reports", "Performance Metrics", "ROI Analysis"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Create courses with lessons",
            "Central course catalog",
            "Track course completion",
            "Course discussion forums",
            "Completion certificates"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Structured learning paths",
            "Blended learning support",
            "Advanced skills reporting",
            "HR system integration",
            "Customizable learning portal"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Organizing scattered training content",
            "Standardizing new hire onboarding",
            "Tracking compliance training",
            "Increasing employee engagement",
            "Measuring training impact",
            "Creating employee development plans",
            "Training a remote workforce",
            "Assessing knowledge retention",
            "Managing online & classroom training",
            "Keeping training content updated"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI course recommendations",
            "AI-driven learning path generation",
            "Automated quiz generation",
            "AI analysis of discussion forums",
            "Predictive 'at-risk' learner analysis",
            "AI chatbot for course discovery",
            "Smart external content curation",
            "AI-based skill gap analysis",
            "Natural language content search",
            "AI video transcription & summarization",
            "Personalized adaptive learning",
            "AI recommendations for course improvement",
            "Automated course-to-competency mapping",
            "AI 'learning coach' for motivation",
            "Predictive analysis of training ROI",
            "Smart plagiarism detection",
            "AI-powered course outline generation",
            "Automated course material translation",
            "AI analysis of assessment results",
            "Smart scheduling for blended learning"
          ]
        }
      ]
    }