  import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Lens": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["AR Overview", "Active Sessions", "Device Status", "Recent Activities"]
        },
        {
          title: "AR Sessions",
          icon: <Eye className="w-4 h-4" />,
          items: ["Start AR Session", "Join Session", "Session Library", "Session Recording"]
        },
        {
          title: "Annotations",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["3D Annotations", "Voice Notes", "Drawing Tools", "Measurement Tools"]
        },
        {
          title: "Knowledge Base",
          icon: <BookOpen className="w-4 h-4" />,
          items: ["AR Guides", "Step-by-step Instructions", "Video Tutorials", "Documentation"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Multi-user Sessions", "Expert Assistance", "Real-time Sharing", "Team Collaboration"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Usage Analytics", "Performance Metrics", "Session Analysis", "ROI Reports"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Live camera streaming",
            "On-screen annotations",
            "In-session chat & audio",
            "Freeze frame",
            "Flashlight control"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "3D object annotation",
            "Smart glass integration",
            "Session recording",
            "Optical Character Recognition (OCR)",
            "Help desk integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Troubleshooting remote machinery",
            "Explaining complex physical repairs",
            "Reducing expert travel costs",
            "Documenting repair processes",
            "Reading serial numbers remotely",
            "Enabling hands-free operation",
            "Providing immediate visual context",
            "Training new technicians",
            "Avoiding miscommunication in repairs",
            "Integrating AR into service workflows"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI object recognition",
            "Automated step-by-step AR guidance",
            "AI analysis of session recordings",
            "Smart annotation suggestions",
            "AI-based language translation",
            "Predictive maintenance alerts",
            "AI-powered digital twin overlays",
            "Automated session summaries",
            "Natural language technician commands",
            "AI noise cancellation",
            "Smart video stabilization",
            "AI-driven OCR parsing",
            "Predictive repair time analysis",
            "AI-powered expert routing",
            "Automated safety warnings",
            "AI tool and parts recommendations",
            "Image-based knowledge search",
            "AI analysis of technician performance",
            "Automated training module creation",
            "AI 'best next step' suggestions"
          ]
        }
      ]
    }