import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"ManageEngine": {
      sections: [
        {
          title: "Assets",
          icon: <Package className="w-4 h-4" />,
          items: ["IT Assets", "Hardware Assets", "Software Assets", "Asset Discovery", "Asset Lifecycle", "Asset Reports"]
        },
        {
          title: "Network",
          icon: <Wifi className="w-4 h-4" />,
          items: ["Network Monitoring", "Device Management", "Network Topology", "Performance Monitoring", "Network Reports"]
        },
        {
          title: "Help Desk",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Tickets", "Incident Management", "Problem Management", "Change Management", "Knowledge Base"]
        },
        {
          title: "Security",
          icon: <Shield className="w-4 h-4" />,
          items: ["Security Monitoring", "Vulnerability Assessment", "Patch Management", "Compliance Management", "Security Reports"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["IT Analytics", "Performance Analytics", "Cost Analytics", "Usage Analytics", "Custom Dashboards"]
        },
        {
          title: "Automation",
          icon: <Zap className="w-4 h-4" />,
          items: ["IT Automation", "Workflow Automation", "Scheduled Tasks", "Policy Automation", "Process Automation"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["System Settings", "User Management", "Integration Settings", "Notification Settings", "License Management"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "IT help desk",
            "IT asset inventory",
            "Network monitoring",
            "IT knowledge base",
            "Status dashboard"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated patch management",
            "Active Directory management",
            "SIEM for threat detection",
            "Application performance monitoring",
            "Mobile Device Management"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Managing employee IT support tickets",
            "Tracking all company hardware/software",
            "Knowing when critical servers are down",
            "Keeping computers patched and secure",
            "Detecting network security threats",
            "Managing Active Directory users",
            "Troubleshooting slow applications",
            "Securing company mobile devices",
            "Answering repetitive IT questions",
            "Proving IT security compliance"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered IT ticket routing",
            "Predictive hardware failure",
            "AI root cause analysis for outages",
            "Smart knowledge base suggestions",
            "AI-driven threat detection",
            "Automated password reset chatbot",
            "AI recommendations for app optimization",
            "Behavioral analytics for security",
            "AI-based patch deployment suggestions",
            "Natural language IT data search",
            "AI-powered asset discovery",
            "Predictive IT ticket volume analysis",
            "Smart event correlation",
            "AI recommendations for security posture",
            "Automated IT performance reports",
            "AI 'what-if' infrastructure analysis",
            "Smart 'shadow IT' detection",
            "AI-based capacity planning",
            "Automated compliance checking",
            "AI insights into IT efficiency"
          ]
        }
      ]
    },