import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Marketing Automation": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Campaign Overview", "Lead Flow Analytics", "Performance Metrics", "Real-time Activities", "ROI Dashboard"]
        },
        {
          title: "Journey Builder",
          icon: <GitBranch className="w-4 h-4" />,
          items: ["Visual Journey Designer", "Customer Journey Mapping", "Multi-channel Journeys", "Trigger Events", "Path Analysis", "Journey Templates"]
        },
        {
          title: "Campaigns",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Email Campaigns", "SMS Campaigns", "Push Notifications", "In-App Messages", "Web Push", "Social Media Campaigns"]
        },
        {
          title: "Lead Management",
          icon: <Users className="w-4 h-4" />,
          items: ["Lead Scoring", "Lead Nurturing", "Behavioral Tracking", "Lead Lifecycle", "Progressive Profiling"]
        },
        {
          title: "Segmentation",
          icon: <Filter className="w-4 h-4" />,
          items: ["Audience Segments", "Dynamic Lists", "Behavioral Triggers", "Custom Attributes", "Smart Segmentation"]
        },
        {
          title: "Automation",
          icon: <Zap className="w-4 h-4" />,
          items: ["Workflow Automation", "Trigger Campaigns", "Auto-responses", "Drip Sequences", "Event-based Actions"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Campaign Performance", "Attribution Reports", "Conversion Tracking", "A/B Test Results", "Revenue Attribution"]
        },
        {
          title: "Integration",
          icon: <Link2 className="w-4 h-4" />,
          items: ["CRM Integration", "Website Tracking", "API Configuration", "Webhooks", "Third-party Apps"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Drag-and-Drop Email Builder",
            "A/B Testing for Subject Lines",
            "Dynamic Content Blocks",
            "Form Pre-fill with Known Data",
            "Lead Source Tracking"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Visual Customer Journey Builder",
            "Advanced Lead Scoring & Grading",
            "Multi-channel Campaign Orchestration",
            "Revenue Attribution Reporting",
            "Website Personalization Engine"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Generating High-Quality Leads",
            "Nurturing Leads Effectively",
            "Aligning Sales and Marketing",
            "Measuring Marketing ROI",
            "Personalizing at Scale",
            "Managing Customer Data",
            "Creating Engaging Content",
            "Automating Repetitive Tasks",
            "Understanding Customer Behavior",
            "Improving Customer Retention"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-Powered Predictive Segmentation",
            "Automated Journey Optimization",
            "AI-Generated Email Copy",
            "Predictive Lead Scoring",
            "Smart Audience Targeting",
            "AI-driven Content Recommendations",
            "Automated Anomaly Detection in Campaigns",
            "Predictive Churn Analysis",
            "AI-assisted Campaign Creation",
            "Voice-activated Campaign Analytics",
            "Predictive A/B Testing",
            "AI-powered Content Personalization",
            "Automated Customer Journey Mapping",
            "AI-driven Lead Nurturing",
            "Predictive Analytics for Campaign Success",
            "AI-powered Social Media Scheduling",
            "Automated Ad Spend Optimization",
            "AI-based Email Subject Line Generator",
            "Customer Lifetime Value Prediction",
            "AI-driven Market Trend Analysis"
          ]
        }
      ]
    },