import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Notebook": {
      sections: [
        {
          title: "Notebooks",
          icon: <BookOpen className="w-4 h-4" />,
          items: ["My Notebooks", "Shared Notebooks", "Recent Notes", "Favorites", "Archived"]
        },
        {
          title: "Notes",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Create Note", "Text Notes", "Audio Notes", "Photo Notes", "Sketch Notes"]
        },
        {
          title: "Organization",
          icon: <Folder className="w-4 h-4" />,
          items: ["Tags", "Categories", "Search", "Filters", "Quick Access"]
        },
        {
          title: "Collaboration",
          icon: <Share2 className="w-4 h-4" />,
          items: ["Share Notebooks", "Team Notes", "Comments", "Real-time Sync"]
        },
        {
          title: "Sync",
          icon: <RefreshCw className="w-4 h-4" />,
          items: ["Cloud Sync", "Offline Access", "Multi-device Sync", "Backup"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Different note types",
            "Notebooks & tags",
            "Web clipper",
            "Note reminders",
            "Cross-device sync"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Search within images/PDFs (OCR)",
            "Note sharing & collaboration",
            "Smart Cards auto-formatting",
            "Password protection",
            "Integration with other Zoho apps"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Capturing ideas on the go",
            "Organizing messy notes",
            "Finding old information",
            "Saving web articles",
            "Combining different content types",
            "Collaborating on research",
            "Remembering to act on a note",
            "Unlocking info from images",
            "Keeping notes secure",
            "Accessing notes offline"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered smart search",
            "Automated note tagging",
            "AI summarization of notes",
            "Zia assistant for related notes",
            "AI audio transcription",
            "Smart notebook suggestions",
            "AI OCR for handwriting",
            "Smart Card for any content",
            "AI 'knowledge graph' of notes",
            "Predictive search suggestions",
            "AI-driven contextual reminders",
            "Automated duplicate note detection",
            "AI-generated flashcards",
            "Smart adaptive templates",
            "AI grammar & spelling correction",
            "Automated content linking",
            "AI mind map generation",
            "Smart action item extraction",
            "AI insights into note habits",
            "Automated web clip categorization"
          ]
        }
      ]
    }