import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

    "Office Suite": {
      sections: [
        {
          title: "Home",
          icon: <Home className="w-4 h-4" />,
          items: ["Dashboard", "Recent Files", "Quick Access", "Team Activity", "Getting Started"]
        },
        {
          title: "Documents",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Documents", "Word Documents", "Text Files", "Document Templates", "Shared Documents"]
        },
        {
          title: "Spreadsheets",
          icon: <Table className="w-4 h-4" />,
          items: ["All Spreadsheets", "Excel Files", "CSV Files", "Data Analysis", "Spreadsheet Templates"]
        },
        {
          title: "Presentations",
          icon: <Monitor className="w-4 h-4" />,
          items: ["All Presentations", "PowerPoint Files", "Slide Templates", "Presentation Themes", "Shared Presentations"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Team Workspaces", "Real-time Editing", "Comments & Reviews", "Version Control", "Share Settings"]
        },
        {
          title: "Storage",
          icon: <Cloud className="w-4 h-4" />,
          items: ["File Manager", "Recent Files", "Shared Files", "Storage Usage", "File Recovery"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Suite Preferences", "Account Settings", "Security Options", "Integration Settings", "Admin Panel"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Create docs, sheets, & slides",
            "Unified recent files dashboard",
            "Templates for all apps",
            "Consistent user interface",
            "Export to MS Office/PDF"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Real-time collaboration suite",
            "Integrated cloud storage",
            "Suite-wide AI assistant",
            "Team workspaces",
            "Deep integration between apps"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Avoiding multiple software subscriptions",
            "Solving compatibility issues",
            "Collaborating on different document types",
            "Finding files in one place",
            "Using spreadsheet data in presentations",
            "Getting intelligent help while working",
            "Managing file permissions consistently",
            "Onboarding users to fewer tools",
            "Editing documents on any device",
            "Creating branded company documents"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "Unified AI assistant (Zia)",
            "AI-powered cross-suite search",
            "Smart content repurposing",
            "AI suggestions for linking documents",
            "Automated cross-app workflows",
            "AI insights from combined files",
            "Natural language suite commands",
            "AI-powered brand kit",
            "Unified predictive text",
            "AI template recommendations",
            "Automated data extraction between apps",
            "Smart project workspace creation",
            "AI 'what-if' analysis across apps",
            "Automated meeting minute generation",
            "AI suggestions for consistent design",
            "Smart file organization suggestions",
            "AI-powered cross-file fact-checking",
            "Automated dashboard creation",
            "AI-driven collaboration suggestions",
            "Predictive file usage analysis"
          ]
        }
      ]
    },