import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

    "OneAuth": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Authentication Overview", "Login Analytics", "Security Alerts", "Recent Activities"]
        },
        {
          title: "Multi-Factor Auth",
          icon: <Shield className="w-4 h-4" />,
          items: ["Authenticator Apps", "SMS Verification", "Email Verification", "Hardware Tokens"]
        },
        {
          title: "Applications",
          icon: <Grid className="w-4 h-4" />,
          items: ["Connected Apps", "SSO Applications", "App Directory", "Custom Apps"]
        },
        {
          title: "Users",
          icon: <Users className="w-4 h-4" />,
          items: ["User Management", "User Groups", "Access Policies", "Login History"]
        },
        {
          title: "Security",
          icon: <Lock className="w-4 h-4" />,
          items: ["Security Policies", "Risk Assessment", "Compliance Reports", "Audit Logs"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Organization Settings", "Authentication Policies", "Integration Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Time-based one-time passwords",
            "One-tap push notifications",
            "QR code account setup",
            "Secure account backup",
            "Support for multiple services"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Single Sign-On (SSO)",
            "Passwordless login",
            "Offline TOTP access",
            "Centralized admin policies",
            "Active Directory integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Strengthening password security",
            "Reducing password fatigue with SSO",
            "Simplifying the login process",
            "Recovering from a lost phone",
            "Getting 2FA codes while offline",
            "Managing employee app access",
            "Protecting against phishing",
            "Eliminating daily login hassles",
            "Streamlining user provisioning",
            "Securing cloud and on-premise apps"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI risk-based authentication",
            "Behavioral biometrics",
            "AI-driven suspicious login alerts",
            "Smart phishing attempt detection",
            "AI security policy recommendations",
            "Automated user provisioning suggestions",
            "Natural language admin queries",
            "AI analysis of auth logs",
            "Predictive user compromise risk",
            "Smart application grouping",
            "AI-powered organization security score",
            "Automated credential stuffing detection",
            "AI guidance for MFA setup",
            "Smart session timeout reminders",
            "AI 'identity guardian' for dark web",
            "Context-aware authentication",
            "AI passwordless adoption analysis",
            "Automated SSO usage analysis",
            "AI chatbot for user support",
            "Smart account recovery options"
          ]
        }
      ]
    }