import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Payments": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Payment Overview", "Transaction Volume", "Success Rates", "Revenue Analytics", "Gateway Performance"]
        },
        {
          title: "Transactions",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["All Transactions", "Successful Payments", "Failed Payments", "Pending Payments", "Refunds"]
        },
        {
          title: "Payment Gateways",
          icon: <Server className="w-4 h-4" />,
          items: ["Gateway Management", "Multi-gateway Setup", "Failover Configuration", "Gateway Analytics"]
        },
        {
          title: "Customers",
          icon: <Users className="w-4 h-4" />,
          items: ["Customer Management", "Payment Methods", "Transaction History", "Customer Insights"]
        },
        {
          title: "Fraud Protection",
          icon: <Shield className="w-4 h-4" />,
          items: ["Fraud Detection", "Risk Rules", "Blocked Transactions", "Whitelist Management"]
        },
        {
          title: "Reconciliation",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Settlement Reports", "Bank Reconciliation", "Dispute Management", "Chargeback Handling"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Payment Analytics", "Revenue Reports", "Gateway Performance", "Customer Analytics"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Payment Configuration", "Security Settings", "Webhook Management", "API Keys"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Accept credit cards",
            "Create simple payment links",
            "Transaction dashboard",
            "Multi-currency support",
            "PCI-compliant processing"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Multi-gateway routing",
            "Fraud & risk management",
            "Automated reconciliation",
            "Recurring billing engine",
            "Unified payments API"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Accepting payments without a store",
            "Reducing high transaction fees",
            "Handling payment gateway outages",
            "Fighting fraudulent transactions",
            "Reconciling payments with deposits",
            "Simplifying payment integrations",
            "Ensuring PCI compliance",
            "Managing subscription payments",
            "Accepting international payments",
            "Getting a clear view of transactions"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered fraud detection",
            "Smart transaction routing",
            "AI recommendations for fee reduction",
            "Predictive payment success analysis",
            "AI-driven chargeback prevention",
            "Automated sales trend analysis",
            "Natural language transaction search",
            "AI-powered 'smart retry' logic",
            "Chargeback reason sentiment analysis",
            "AI-based customer risk scoring",
            "Smart transaction pattern alerts",
            "AI 'what-if' gateway analysis",
            "Automated reconciliation suggestions",
            "AI insights into payment trends",
            "Predictive cash flow forecasting",
            "AI chatbot for transaction support",
            "Smart currency conversion advice",
            "AI checkout conversion recommendations",
            "Automated detection of linked fraud",
            "AI-generated daily activity summaries"
          ]
        }
      ]
    },