import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"People": {
      sections: [
        {
          title: "Employee",
          icon: <Users className="w-4 h-4" />,
          items: ["Employee Directory", "My Space", "Employee Profiles", "Organization Chart"]
        },
        {
          title: "Attendance",
          icon: <Clock className="w-4 h-4" />,
          items: ["Check In/Out", "Attendance Reports", "Attendance Settings", "Regularization", "Shifts", "Working Hours", "Overtime"]
        },
        {
          title: "Leave",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Apply Leave", "Leave Calendar", "Leave Approvals", "Leave Reports", "Leave Settings", "Leave Types", "Holiday Calendar"]
        },
        {
          title: "Performance",
          icon: <Target className="w-4 h-4" />,
          items: ["Performance Management", "Learning Management", "Compensation Module"]
        },
        {
          title: "Communication",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["Announcements", "Feeds", "Files", "Forms"]
        },
        {
          title: "Administration",
          icon: <Settings className="w-4 h-4" />,
          items: ["Settings", "Reports", "Integrations", "Cases"]
        },
        {
          title: "Mobile Features",
          icon: <Smartphone className="w-4 h-4" />,
          items: ["Facial Recognition", "Location Tracking", "Push Notifications", "Offline Capability", "AI Chatbot Zia"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Company directory",
            "Employee self-service portal",
            "Leave request system",
            "Holiday calendar",
            "Company announcements feed"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated employee onboarding",
            "Performance management module",
            "Automated attendance tracking",
            "Comprehensive leave management",
            "Centralized document management"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Digitizing paper-based HR processes",
            "Tracking time and attendance accurately",
            "Managing leave requests and balances",
            "Ensuring fair performance reviews",
            "Keeping employee data secure",
            "Streamlining new hire onboarding",
            "Answering repetitive HR questions",
            "Generating HR reports for management",
            "Tracking company assets",
            "Handling complex shift scheduling"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered resume screening",
            "Predictive employee turnover analysis",
            "AI chatbot for HR queries",
            "Sentiment analysis of employee surveys",
            "AI-driven learning path recommendations",
            "Smart automation of HR workflows",
            "AI-based compensation analysis",
            "Predictive workforce needs forecasting",
            "AI analysis of performance review data",
            "Intelligent attendance anomaly detection",
            "Automated job description generation",
            "AI insights into organizational structure",
            "Personalized employee onboarding",
            "AI suggestions for employee engagement",
            "Smart mentor/mentee matching",
            "Automated HR compliance checks",
            "AI analysis of employee skills gaps",
            "Predictive promotion readiness analysis",
            "AI-generated performance summaries",
            "Voice commands for HR tasks"
          ]
        }
      ]
    },