import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Practice": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Practice Overview", "Client Portfolio", "Revenue Metrics", "Team Performance", "Deadline Tracking"]
        },
        {
          title: "Clients",
          icon: <Users className="w-4 h-4" />,
          items: ["Client Management", "Client Onboarding", "Client Portal", "Client Communications", "Entity Management"]
        },
        {
          title: "Jobs",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Jobs", "Tax Preparation", "Bookkeeping", "Audit & Review", "Advisory Services", "Job Templates"]
        },
        {
          title: "Time Tracking",
          icon: <Clock className="w-4 h-4" />,
          items: ["Time Entry", "Timesheet Approval", "Billable Hours", "Time Reports", "Timer Integration"]
        },
        {
          title: "Documents",
          icon: <Folder className="w-4 h-4" />,
          items: ["Document Management", "Client Documents", "Templates", "E-signatures", "Document Sharing"]
        },
        {
          title: "Billing",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["Invoice Generation", "Fee Management", "Payment Tracking", "Recurring Billing", "Collections"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Financial Reports", "Time Reports", "Productivity Reports", "Client Reports", "Tax Reports"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Practice Settings", "Team Management", "Fee Structure", "Tax Settings", "Integration"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Central client database",
            "Time tracking",
            "Deadline dashboard",
            "Task management",
            "Secure document management"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Workflow automation for jobs",
            "Secure client portal",
            "Integrated billing & invoicing",
            "Accounting software integration",
            "Firm productivity reporting"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Managing client deadlines",
            "Standardizing accounting processes",
            "Sharing documents securely with clients",
            "Ensuring all time is billed",
            "Tracking staff productivity",
            "Centralizing client communication",
            "Automating client onboarding",
            "Ensuring compliance and accuracy",
            "Understanding firm profitability",
            "Getting documents from clients on time"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered bookkeeping automation",
            "Predictive deadline risk analysis",
            "AI suggestions for workflow optimization",
            "Smart job allocation to staff",
            "AI review of financial documents",
            "Automated client communication generation",
            "AI insights into firm profitability",
            "Natural language search for clients/jobs",
            "AI chatbot for client FAQs",
            "Predictive revenue forecasting",
            "AI-based suggestions for service pricing",
            "Automated client document categorization",
            "AI-powered 'practice health' score",
            "Smart alerts for job budget overruns",
            "AI recommendations for upselling services",
            "Client communication sentiment analysis",
            "AI-powered time tracking suggestions",
            "Automated engagement letter generation",
            "AI-based compliance checks",
            "Predictive client churn analysis"
          ]
        }
      ]
    },