import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Projects": {
      sections: [
        {
          title: "Home",
          icon: <Home className="w-4 h-4" />,
          items: ["Homepage", "Dashboard Overview", "Recent Activity", "Quick Access Widgets"]
        },
        {
          title: "Projects",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Projects", "Project Templates", "Project Creation", "Active Projects", "Archived Projects"]
        },
        {
          title: "Tasks",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Task Lists", "All Tasks", "My Tasks", "Task Views", "Task Dependencies", "Subtasks"]
        },
        {
          title: "Gantt & Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Milestone Gantt", "Chronology Gantt", "Dependencies Visualization", "Critical Path", "Baseline Comparisons"]
        },
        {
          title: "Time Tracking",
          icon: <Clock className="w-4 h-4" />,
          items: ["Timesheets", "Manual Time Entry", "Timer-based Logging", "Billable Hours", "Time Reports"]
        },
        {
          title: "Milestones",
          icon: <Flag className="w-4 h-4" />,
          items: ["All Milestones", "Create Milestone", "Milestone Tracking", "Project Phases"]
        },
        {
          title: "Issues",
          icon: <AlertCircle className="w-4 h-4" />,
          items: ["Bug Tracking", "Issue Management", "Bug-Task Associations", "Issue Reports"]
        },
        {
          title: "Documents",
          icon: <Folder className="w-4 h-4" />,
          items: ["File Management", "WorkDrive Integration", "Document Sharing", "Version Control"]
        },
        {
          title: "Reports",
          icon: <TrendingUp className="w-4 h-4" />,
          items: ["Workload Tracking", "Plan vs Actuals", "Resource Utilization", "Project Analytics", "Custom Reports"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Activity Feeds", "Shared Calendars", "Team Chat", "Comments & Mentions"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Task templates",
            "My Tasks view",
            "Simple hour timer",
            "Project status labels",
            "Drag-and-drop task ranking"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Interactive Gantt charts",
            "Advanced resource management",
            "Integrated issue tracking",
            "Project budgeting & financials",
            "Customizable project templates"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Clarifying who is doing what",
            "Preventing budget overruns",
            "Centralizing team communication",
            "Managing scope creep",
            "Preventing team burnout",
            "Tracking billable vs. non-billable hours",
            "Keeping clients informed",
            "Preventing bugs from getting lost",
            "Standardizing project setup",
            "Understanding project profitability"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered project risk prediction",
            "Smart task scheduling",
            "AI-driven task breakdown suggestions",
            "Predictive project completion dates",
            "Automated project status reporting",
            "AI anomaly detection in timesheets",
            "Intelligent bottleneck identification",
            "AI-powered task prioritization",
            "Natural language project queries",
            "Team morale sentiment analysis",
            "AI workflow improvement suggestions",
            "Automated meeting agendas",
            "Predictive budget overrun warnings",
            "AI-based task duration estimation",
            "Smart notifications for at-risk tasks",
            "AI-powered task assignment",
            "Automated issue categorization",
            "AI insights from past projects",
            "Predictive resource forecasting",
            "AI project support chatbot"
          ]
        }
      ]
    },