import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"QEngine": {
      sections: [
        {
          title: "Tests",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["All Tests", "Test Cases", "Test Scripts", "Manual Tests", "Automated Tests", "Test Templates"]
        },
        {
          title: "Test Suites",
          icon: <List className="w-4 h-4" />,
          items: ["All Suites", "Regression Suites", "Smoke Tests", "Integration Tests", "Performance Tests"]
        },
        {
          title: "Execution",
          icon: <PlayCircle className="w-4 h-4" />,
          items: ["Test Execution", "Test Runs", "Scheduled Runs", "Parallel Execution", "Test Results", "Execution History", "Cross-browser Testing", "Mobile Testing"]
        },
        {
          title: "Results",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Test Results", "Failed Tests", "Passed Tests", "Test History", "Result Analysis"]
        },
        {
          title: "Defects",
          icon: <AlertCircle className="w-4 h-4" />,
          items: ["All Defects", "Open Defects", "Defect Tracking", "Bug Reports", "Defect Analysis", "Bug Lifecycle", "Integration with Bug Tools"]
        },
        {
          title: "Reports",
          icon: <FileText className="w-4 h-4" />,
          items: ["Test Reports", "Coverage Reports", "Quality Reports", "Performance Reports", "Custom Reports", "Trend Analysis"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Test Configuration", "Environment Settings", "Integration Settings", "Team Settings", "Project Settings"]
        },
        {
          title: "Test Management",
          icon: <FolderOpen className="w-4 h-4" />,
          items: ["Test Suites", "Test Plans", "Test Environments", "Test Configurations", "Version Control"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Test case repository",
            "Organize tests into suites",
            "Execute test runs",
            "Capture screenshots",
            "Test run status dashboard"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Web application test automation",
            "CI/CD pipeline integration",
            "Bug tracker integration",
            "Cross-browser testing",
            "Advanced test reporting"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Reducing slow, manual testing",
            "Managing test cases in spreadsheets",
            "Gaining visibility into test progress",
            "Reporting bugs with sufficient detail",
            "Ensuring cross-browser compatibility",
            "Removing testing as a bottleneck",
            "Understanding application quality",
            "Onboarding new QA testers",
            "Improving developer-tester collaboration",
            "Reusing test cases effectively"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered 'self-healing' tests",
            "AI test case generation",
            "Smart 'impacted test' identification",
            "AI-powered visual testing",
            "Predictive 'flaky test' analysis",
            "AI analysis of test results",
            "Automated root cause analysis",
            "AI suggestions for test case design",
            "Natural language test script writing",
            "AI-powered test data generation",
            "Smart test execution optimization",
            "AI-based defect clustering",
            "Predictive release readiness analysis",
            "AI-powered exploratory testing",
            "Automated test summary reports",
            "AI-based risk-based testing",
            "Smart duplicate test case detection",
            "AI performance testing suggestions",
            "Automated accessibility testing",
            "AI-based test environment management"
          ]
        }
      ]
    },