import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"RPA": {
      sections: [
        {
          title: "Bots",
          icon: <Bot className="w-4 h-4" />,
          items: ["All Bots", "Active Bots", "Scheduled Bots", "Bot Templates", "Bot Library", "Failed Bots", "Bot Builder"]
        },
        {
          title: "Workflows",
          icon: <Zap className="w-4 h-4" />,
          items: ["All Workflows", "Workflow Builder", "Workflow Templates", "Automated Workflows", "Workflow History"]
        },
        {
          title: "Schedule",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Scheduled Tasks", "Recurring Jobs", "Job Calendar", "Schedule Management", "Time Triggers", "Task Queue", "Execution History", "Schedule Templates"]
        },
        {
          title: "Monitoring",
          icon: <Monitor className="w-4 h-4" />,
          items: ["Bot Performance", "Execution Logs", "Error Monitoring", "Real-time Status", "System Health"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Execution Analytics", "Performance Reports", "Success Rates", "Error Analysis", "Time Savings", "Execution Reports", "ROI Analysis", "Process Efficiency"]
        },
        {
          title: "Integration",
          icon: <Link2 className="w-4 h-4" />,
          items: ["API Integration", "Third-party Apps", "Database Connections", "Web Services", "Custom Connectors"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Bot Settings", "Security Settings", "Notification Settings", "Team Management", "License Management"]
        },
        {
          title: "Processes",
          icon: <GitBranch className="w-4 h-4" />,
          items: ["Business Processes", "Process Library", "Process Designer", "Process Recorder", "Process Analytics"]
        },
        {
          title: "Resources",
          icon: <Server className="w-4 h-4" />,
          items: ["Bot Runners", "Resource Pool", "License Management", "System Requirements", "Performance Monitor"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Visual workflow recorder",
            "Drag-and-drop builder",
            "Library of pre-built actions",
            "Scheduled bot runs",
            "Execution history dashboard"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Unattended bots",
            "Attended bots (digital assistants)",
            "API integration",
            "Advanced error handling",
            "Centralized bot management"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Automating repetitive data entry",
            "Connecting spreadsheets to legacy apps",
            "Automating invoice processing",
            "Generating daily reports automatically",
            "Migrating data without APIs",
            "Automating new employee setup",
            "Reducing human errors in processes",
            "Handling high-volume, rule-based tasks",
            "Automating tasks on your own desktop",
            "Auditing automated processes"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered process discovery",
            "Smart OCR for documents",
            "AI computer vision for UI automation",
            "Natural language bot building",
            "AI-powered adaptive error handling",
            "Predictive analytics on bot performance",
            "AI suggestions for workflow optimization",
            "Sentiment analysis for process triggers",
            "AI-powered 'self-healing' bots",
            "Automated process documentation",
            "AI-driven bot workload management",
            "Smart bot scheduling",
            "AI 'what-if' analysis for processes",
            "Automated exception categorization",
            "AI insights into automation ROI",
            "Predictive bot failure alerts",
            "AI chatbot for building bots",
            "Smart data validation in bots",
            "AI recommendations for automation candidates",
            "Automated test case generation for bots"
          ]
        }
      ]
    },