import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"SalesIQ": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Settings > Brands", "Channel Management", "Brand Configuration", "Department Access", "Dark/Light Theme"]
        },
        {
          title: "Live Chat",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["Chat Widget Customization", "Float vs Static Options", "Custom Branding", "Chat Window Themes", "Operator Profile Pictures", "24-Hour Idle Management"]
        },
        {
          title: "Multi-Channel",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["WhatsApp Integration", "Telegram Support", "Facebook Messenger", "Pre-chat Forms", "Canned Response Categories", "Hebrew RTL Support"]
        },
        {
          title: "Visitor Tracking",
          icon: <Eye className="w-4 h-4" />,
          items: ["Real-time Analytics", "Geographic Tracking", "Behavioral Insights", "Lead Scoring", "Mobile App Tracking", "Mobilisten SDK"]
        },
        {
          title: "Visitor Data",
          icon: <Database className="w-4 h-4" />,
          items: ["Demographics", "Engagement Metrics", "CRM Integration", "Email Campaign Tracking", "MailChimp Integration"]
        },
        {
          title: "Widgets",
          icon: <Code className="w-4 h-4" />,
          items: ["Custom Widget Development", "Deluge Scripting", "API Access", "Webhooks", "Platform Support"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Weekly Reports Dashboard", "Visitor Trends", "Real-time Notifications", "Automated Mailing Lists", "Google Analytics Sync"]
        },
        {
          title: "Integrations",
          icon: <Link2 className="w-4 h-4" />,
          items: ["Zoho Desk Integration", "TV Apps", "Android TV", "Apple TV", "Desktop Apps", "Mobile Alerts"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Customizable chat widgets",
            "Canned responses",
            "Pre-chat forms",
            "Desktop notifications",
            "Operator 'away' status"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Real-time visitor tracking",
            "Proactive chat invitations",
            "Lead scoring",
            "Codeless chatbot builder",
            "CRM & Help Desk integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Engaging website visitors",
            "Understanding visitor behavior",
            "Providing 24/7 support with chatbots",
            "Reducing website bounce rates",
            "Answering repetitive questions",
            "Qualifying leads effectively",
            "Creating a unified customer experience",
            "Measuring live chat ROI",
            "Supporting customers on multiple platforms",
            "Personalizing the website experience"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered Answer Bot",
            "Intelligent chat routing",
            "AI-driven lead scoring",
            "Chat sentiment analysis",
            "AI-generated agent responses",
            "Predictive visitor behavior analysis",
            "AI-powered proactive chat triggers",
            "Self-learning chatbot builder",
            "AI chat transcript summarization",
            "Automated real-time translation",
            "AI insights into customer pain points",
            "Advanced NLU for chatbots",
            "AI-driven upsell recommendations",
            "Automated chat categorization",
            "AI-based agent quality assurance",
            "Predictive chat volume forecasting",
            "AI-powered 'smart actions' in chat",
            "Voice-enabled chat interaction",
            "AI A/B testing for chat widgets",
            "Automated VIP customer identification"
          ]
        }
      ]
    },