import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"SalesInbox": {
      sections: [
        {
          title: "Deals",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["Active Deals", "Deal Pipeline", "Deal Communications", "Deal Progress", "Sales Opportunities"]
        },
        {
          title: "Leads",
          icon: <Users className="w-4 h-4" />,
          items: ["Prospective Customers", "Lead Communications", "Lead Conversion", "Follow-up Management"]
        },
        {
          title: "Contacts",
          icon: <Users className="w-4 h-4" />,
          items: ["Customer Correspondence", "Contact Timeline", "Interaction History", "Customer Engagement"]
        },
        {
          title: "Not in CRM",
          icon: <User className="w-4 h-4" />,
          items: ["Unknown Contacts", "New Prospects", "External Communications", "Lead Creation"]
        },
        {
          title: "Colleagues",
          icon: <Users className="w-4 h-4" />,
          items: ["Internal Communications", "Team Collaboration", "Internal Updates"]
        },
        {
          title: "Smart Features",
          icon: <Zap className="w-4 h-4" />,
          items: ["Auto-prioritization", "CRM Filtering", "Label System", "Drag-and-drop Actions", "Contact Suggestions"]
        },
        {
          title: "ResponseWatch",
          icon: <Clock className="w-4 h-4" />,
          items: ["Deadline Reminders", "Overdue Notifications", "VIP Customer Alerts", "Follow-up Automation"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Email Intelligence", "Open Tracking", "Template Performance", "Dashboard Reports", "A/B Testing Insights"]
        },
        {
          title: "Templates",
          icon: <FileText className="w-4 h-4" />,
          items: ["Sales Email Templates", "Email Scheduling", "Performance Tracking", "CRM-based Suggestions"]
        },
        {
          title: "Team Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Shared Contexts", "Team Handoffs", "New Hire Onboarding", "Role Change Continuity"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Email templates",
            "Email open and link tracking",
            "Send later scheduling",
            "Create CRM contact from email",
            "Set follow-up reminders"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automatic email prioritization",
            "Multi-column inbox view",
            "Deep CRM integration",
            "Reply tracking with ResponseWatch",
            "Team email sharing"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Organizing a cluttered sales inbox",
            "Remembering to follow up with leads",
            "Reducing context switching with CRM",
            "Knowing if a prospect saw your email",
            "Avoiding writing repetitive emails",
            "Responding faster to hot leads",
            "Onboarding new salespeople",
            "Ensuring consistent team messaging",
            "Prioritizing daily emails",
            "Automating CRM data entry"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI suggestions for best send time",
            "Email sentiment analysis",
            "AI-generated email drafts",
            "Predictive lead scoring",
            "Next Best Action recommendations",
            "AI insights on template performance",
            "Automated email thread summarization",
            "AI identification of upsell opportunities",
            "Smart alerts on prospect engagement",
            "AI grammar and tone analysis",
            "Automated contact data enrichment",
            "Predictive deal closing analysis",
            "AI-powered 'ghostwriting' for replies",
            "Automated meeting scheduling",
            "AI competitor mention alerts",
            "Intelligent email categorization",
            "AI-powered adaptive follow-up reminders",
            "Voice-to-text email and CRM logging",
            "AI analysis of team email performance",
            "Smart 'nudge' for cold leads"
          ]
        }
      ]
    },