import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Sheet": {
      sections: [
        {
          title: "Spreadsheets",
          icon: <Table className="w-4 h-4" />,
          items: ["My Spreadsheets", "Recent Sheets", "Shared Sheets", "Templates", "Drafts"]
        },
        {
          title: "Data",
          icon: <Database className="w-4 h-4" />,
          items: ["Data Import", "Data Validation", "Pivot Tables", "Charts & Graphs", "Data Analysis"]
        },
        {
          title: "Functions",
          icon: <Calculator className="w-4 h-4" />,
          items: ["Formula Builder", "Function Library", "Custom Functions", "Array Formulas"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Real-time Editing", "Comments", "Sheet Sharing", "Permission Management"]
        },
        {
          title: "Automation",
          icon: <Zap className="w-4 h-4" />,
          items: ["Macros", "Scripts", "Auto-fill", "Conditional Formatting", "Data Triggers"]
        },
        {
          title: "Export",
          icon: <Download className="w-4 h-4" />,
          items: ["Excel Export", "CSV Export", "PDF Export", "Chart Export", "Print Options"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Formula library",
            "Conditional formatting",
            "Data validation rules",
            "Chart creation",
            "Freeze panes"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Pivot tables",
            "Real-time collaboration",
            "Custom scripts & macros",
            "AI assistant (Zia)",
            "External data integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Analyzing large datasets",
            "Collaborating on budgets and plans",
            "Preventing incorrect data entry",
            "Automating repetitive spreadsheet tasks",
            "Finding hidden insights in data",
            "Creating professional charts easily",
            "Connecting to external data sources",
            "Combining data from multiple sheets",
            "Remembering complex formulas",
            "Tracking changes from collaborators"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "Zia: AI assistant",
            "AI-powered data cleansing",
            "Natural language querying",
            "AI formula suggestions",
            "Predictive data forecasting",
            "Automated anomaly detection",
            "AI-powered goal seeking",
            "Smart fill for data entry",
            "AI-generated data narratives",
            "Automated data validation suggestions",
            "AI recommendations for data joins",
            "Smart data clustering",
            "AI-powered 'what-if' analysis",
            "Text sentiment analysis",
            "AI suggestions for conditional formatting",
            "Automated dashboard creation",
            "AI-powered data enrichment",
            "Smart outlier detection",
            "AI assistance for custom scripts",
            "In-sheet predictive modeling"
          ]
        }
      ]
    }