import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Show": {
      sections: [
        {
          title: "Presentations",
          icon: <Monitor className="w-4 h-4" />,
          items: ["My Presentations", "Recent Presentations", "Shared Presentations", "Templates", "Drafts"]
        },
        {
          title: "Design",
          icon: <Palette className="w-4 h-4" />,
          items: ["Slide Layouts", "Themes", "Master Slides", "Animation Effects", "Transitions"]
        },
        {
          title: "Media",
          icon: <Image className="w-4 h-4" />,
          items: ["Images", "Videos", "Audio", "Charts", "Icons", "Stock Media"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Real-time Editing", "Comments", "Presenter Notes", "Review Mode", "Sharing"]
        },
        {
          title: "Present",
          icon: <PlayCircle className="w-4 h-4" />,
          items: ["Slideshow Mode", "Presenter View", "Remote Control", "Broadcast", "Record Presentation"]
        },
        {
          title: "Export",
          icon: <Download className="w-4 h-4" />,
          items: ["PDF Export", "PowerPoint Export", "Image Export", "Video Export", "Print"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Presentation templates",
            "Rich text & shape tools",
            "Transitions & animations",
            "Image & icon library",
            "Presenter view"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Real-time collaboration",
            "Live broadcast to remote audience",
            "Embed live charts",
            "Centralized brand library",
            "PowerPoint compatibility"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Avoiding unprofessional designs",
            "Collaborating on a team presentation",
            "Presenting to a remote audience",
            "Maintaining brand consistency",
            "Updating charts automatically",
            "Remembering key points while presenting",
            "Finding engaging visuals",
            "Sharing presentations after a meeting",
            "Making presentations interactive",
            "Avoiding starting from scratch"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI presentation generation",
            "AI-driven slide design suggestions",
            "Smart image recommendations",
            "AI suggestions for animations",
            "Automated element alignment",
            "AI-powered speaker notes",
            "Grammar and spelling checks",
            "AI recommendations for color/fonts",
            "Natural language editing commands",
            "AI 'design makeover' feature",
            "Automated presentation summary",
            "AI presentation practice coach",
            "Smart content summarization",
            "AI-powered cross-presentation search",
            "Automated chart creation",
            "AI suggestions for visuals over text",
            "Predictive engagement analysis",
            "AI-powered template autofill",
            "Automated branding compliance",
            "AI-generated poll questions"
          ]
        }
      ]
    }