import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

Sites": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Site Overview", "Traffic Analytics", "Performance Metrics", "Recent Updates"]
        },
        {
          title: "Sites",
          icon: <Globe className="w-4 h-4" />,
          items: ["All Sites", "Published Sites", "Draft Sites", "Site Templates", "Mobile Sites"]
        },
        {
          title: "Builder",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Page Builder", "Design Elements", "Layouts", "Widgets", "Custom Code"]
        },
        {
          title: "Content",
          icon: <FileText className="w-4 h-4" />,
          items: ["Pages", "Blog Posts", "Media Library", "Forms", "SEO Settings"]
        },
        {
          title: "E-commerce",
          icon: <Package className="w-4 h-4" />,
          items: ["Online Store", "Products", "Orders", "Payment Settings", "Inventory"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Traffic Reports", "Visitor Analytics", "Conversion Tracking", "SEO Performance"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Domain Settings", "SSL Certificates", "Backup", "Performance Optimization"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Website templates",
            "Drag-and-drop builder",
            "Stock image gallery",
            "Built-in contact forms",
            "Mobile-responsive designs"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Integrated blogging platform",
            "E-commerce capabilities",
            "Built-in SEO tools",
            "Password-protected pages",
            "CRM & marketing integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Building a website with no code",
            "Ensuring sites look good on mobile",
            "Ranking on search engines",
            "Adding a blog to a website",
            "Selling products simply online",
            "Capturing leads from a website",
            "Creating private member areas",
            "Finding quality images",
            "Understanding website traffic",
            "Ensuring a fast, reliable website"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered website generation",
            "AI design assistant",
            "Smart content suggestions",
            "AI-based SEO recommendations",
            "Automated image selection",
            "AI blog post idea generator",
            "AI-powered A/B testing",
            "AI website personalization",
            "Predictive conversion analysis",
            "Addable AI chatbot",
            "Automated accessibility checks",
            "AI-driven logo maker",
            "Smart template recommendations",
            "AI predictive heatmaps",
            "Automated meta description generation",
            "AI copy editing suggestions",
            "Natural language editing commands",
            "AI competitor website analysis",
            "Smart performance alerts",
            "AI-generated e-commerce descriptions"
          ]
        }
      ]
    }