import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Social": {
      sections: [
        {
          title: "Home",
          icon: <Home className="w-4 h-4" />,
          items: ["Brand Health Overview", "Performance Metrics", "Live Notifications", "Unified Activity Feed"]
        },
        {
          title: "Publish",
          icon: <Send className="w-4 h-4" />,
          items: ["New Post Composer", "Multi-platform Support", "Publishing Calendar", "Content Queue", "SmartQ Predictions", "Draft Management", "Team Approvals"]
        },
        {
          title: "Posts",
          icon: <FileText className="w-4 h-4" />,
          items: ["Published Posts", "Scheduled Posts", "Performance Tracking", "Failed Posts", "Post Analytics"]
        },
        {
          title: "Calendar",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Visual Content Planning", "Monthly/Weekly/Daily Views", "Drag-and-drop Scheduling", "Notes & Events", "Holiday View", "Time Zone Customization"]
        },
        {
          title: "Monitor",
          icon: <Search className="w-4 h-4" />,
          items: ["Real-time Social Listening", "Brand Mentions", "Keyword Monitoring", "Hashtag Performance", "Custom Columns", "Competitor Tracking"]
        },
        {
          title: "Messages",
          icon: <MessageCircle className="w-4 h-4" />,
          items: ["Unified Inbox", "WhatsApp Business", "Telegram Integration", "Saved Replies", "Conversation History", "Team Assignment"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Custom Analytics Dashboard", "Pre-built Templates", "Performance Metrics", "Automated Scheduling", "PDF/PNG Export", "White-label Options"]
        },
        {
          title: "Connections",
          icon: <Users className="w-4 h-4" />,
          items: ["Audience Profile Management", "Lead Identification", "CRM Integration", "Follower Organization", "Direct Engagement"]
        },
        {
          title: "Platforms",
          icon: <Grid className="w-4 h-4" />,
          items: ["Facebook", "Instagram", "X/Twitter", "LinkedIn", "YouTube", "TikTok", "Pinterest", "Threads", "Bluesky", "Mastodon"]
        },
        {
          title: "Team",
          icon: <Users className="w-4 h-4" />,
          items: ["Role-based Permissions", "Content Approval", "Team Chat", "Client Portal", "White-label Reporting"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Unified social inbox",
            "Content calendar",
            "Browser sharing extension",
            "URL shortener",
            "Simple graphics editor"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Advanced social listening",
            "SmartQ optimal post timing",
            "Comprehensive analytics",
            "Team collaboration workflows",
            "CRM integration for leads"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Managing multiple social accounts",
            "Generating content ideas",
            "Knowing the best time to post",
            "Missing customer comments",
            "Proving social media ROI",
            "Collaborating with a team",
            "Tracking brand mentions",
            "Handling social customer service",
            "Turning followers into leads",
            "Bulk scheduling content"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI content generation for posts",
            "AI hashtag suggestions",
            "Predictive post performance analytics",
            "Sentiment analysis of mentions",
            "AI recommendations for content formats",
            "Smart replies for social inquiries",
            "AI identification of brand influencers",
            "Automated user-generated content discovery",
            "AI-driven competitor analysis",
            "Predictive industry trend spotting",
            "AI social media crisis alerts",
            "Automated A/B testing for copy",
            "AI-driven audience segmentation",
            "Natural language post scheduling",
            "AI-generated performance summaries",
            "Smart comment moderation",
            "AI suggestions for re-sharing content",
            "Predictive lead scoring from social",
            "AI video content analysis",
            "Automated ad campaign optimization"
          ]
        }
      ]
    },