import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Subscriptions": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Revenue Overview", "Subscription Metrics", "Growth Analytics", "Churn Analysis"]
        },
        {
          title: "Subscriptions",
          icon: <RefreshCw className="w-4 h-4" />,
          items: ["All Subscriptions", "Active Subscriptions", "Paused Subscriptions", "Cancelled Subscriptions"]
        },
        {
          title: "Customers",
          icon: <Users className="w-4 h-4" />,
          items: ["All Customers", "Customer Portal", "Customer Communication", "Customer Segmentation"]
        },
        {
          title: "Plans",
          icon: <Package className="w-4 h-4" />,
          items: ["Subscription Plans", "Pricing Tiers", "Add-ons", "Plan Upgrades", "Plan Analytics"]
        },
        {
          title: "Billing",
          icon: <CreditCard className="w-4 h-4" />,
          items: ["Invoices", "Payment Methods", "Failed Payments", "Dunning Management", "Tax Settings"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Revenue Reports", "Subscription Analytics", "Cohort Analysis", "Lifetime Value"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Billing Settings", "Payment Gateways", "Email Templates", "Webhooks"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Subscription Pause/Resume",
            "Prorated Billing Calculator",
            "Dunning Email Templates",
            "One-Click Plan Upgrade",
            "Trial Expiration Reminders"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Usage-Based Billing Engine",
            "Revenue Recognition Automation",
            "Advanced Churn Prediction",
            "Multi-Currency & Tax Automation",
            "Cohort Analysis Dashboard"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Automated Dunning Management",
            "Self-Service Customer Portal",
            "Automated Prorated Invoicing",
            "Real-time Subscription Metrics",
            "Global Tax & Currency Support",
            "Automated Subscriber Notifications",
            "Seamless Onboarding Integration",
            "Flexible Billing Cycles",
            "PCI-Compliant Security",
            "Robust API & Integrations"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-Powered Pricing Optimization",
            "Predictive Churn Scoring",
            "Automated Upsell Recommendations",
            "Intelligent Dunning Customization",
            "AI-Generated Renewal Forecasts",
            "Subscription Fatigue Analysis",
            "Natural Language Analytics Query",
            "Automated Competitor Price Tracker",
            "AI-Assisted Plan Configuration",
            "Personalized Retention Offers",
            "AI-Powered Churn Prediction",
            "Automated Dunning Management",
            "Predictive LTV Analysis",
            "AI-driven Pricing Optimization",
            "Smart Subscription Recommendations",
            "AI-powered Revenue Forecasting",
            "Automated Failed Payment Recovery",
            "AI-based Customer Segmentation",
            "Intelligent Coupon Suggestions",
            "AI-driven Subscription Analytics"
          ]
        }
      ]
    },