import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Tasks": {
      sections: [
        {
          title: "My Tasks",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["All Tasks", "Today's Tasks", "This Week", "Overdue", "Completed", "Deleted"]
        },
        {
          title: "Projects",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Projects", "Active Projects", "My Projects", "Shared Projects", "Templates"]
        },
        {
          title: "Lists",
          icon: <List className="w-4 h-4" />,
          items: ["Task Lists", "Create List", "Shared Lists", "List Templates"]
        },
        {
          title: "Calendar",
          icon: <Calendar className="w-4 h-4" />,
          items: ["Task Calendar", "Timeline View", "Gantt View", "Due Dates"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Shared Tasks", "Team Tasks", "Comments", "Attachments", "Activity Feed"]
        },
        {
          title: "Reports",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Task Reports", "Progress Reports", "Time Tracking", "Productivity Analytics"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["General Settings", "Notification Settings", "Integration Settings", "Custom Fields"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Create to-do lists",
            "Set due dates & reminders",
            "Add sub-tasks",
            "Add notes & attachments",
            "Prioritize tasks"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Share & assign tasks",
            "Project-based management",
            "Recurring tasks",
            "Calendar view",
            "Task-from-email integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Forgetting what you need to do",
            "Breaking down overwhelming tasks",
            "Clarifying task ownership",
            "Juggling personal and team tasks",
            "Missing important deadlines",
            "Remembering to do routine tasks",
            "Consolidating task information",
            "Visualizing your weekly workload",
            "Losing action items from emails",
            "Tracking project progress"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered task breakdown",
            "Smart task scheduling",
            "AI-based task prioritization",
            "Natural language task creation",
            "AI task duration estimation",
            "Automated task assignment",
            "Predictive productivity analysis",
            "AI-based adaptive reminders",
            "Smart 'at-risk' task alerts",
            "AI suggestions for recurring tasks",
            "Automated 'daily digest' creation",
            "AI-powered 'focus mode'",
            "Smart dependency detection",
            "AI suggestions for task delegation",
            "Automated project status reports",
            "AI-powered 'undo' for completion",
            "Smart task parsing from notes",
            "AI insights on work-life balance",
            "Predictive goal completion",
            "AI-powered celebration messages"
          ]
        }
      ]
    },