import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"TeamInbox": {
      sections: [
        {
          title: "Inbox",
          icon: <Inbox className="w-4 h-4" />,
          items: ["Shared Inbox", "Unassigned", "My Messages", "High Priority", "Archived"]
        },
        {
          title: "Channels",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Email Channels", "Social Channels", "Chat Channels", "Custom Channels"]
        },
        {
          title: "Team Management",
          icon: <Users className="w-4 h-4" />,
          items: ["Team Members", "Assignment Rules", "Workload Distribution", "Performance Tracking"]
        },
        {
          title: "Templates",
          icon: <Copy className="w-4 h-4" />,
          items: ["Response Templates", "Email Templates", "Canned Responses", "Signature Templates"]
        },
        {
          title: "Automation",
          icon: <Zap className="w-4 h-4" />,
          items: ["Auto-assignment", "Auto-responses", "Workflow Rules", "Escalation Rules"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Response Time", "Team Performance", "Volume Analytics", "Customer Satisfaction"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Shared inboxes",
            "Assign conversations",
            "Internal comments",
            "Collision detection",
            "Snooze conversations"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Automated assignment rules",
            "Team performance analytics",
            "CRM & help desk integration",
            "SLA management",
            "Shared email drafts"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Preventing duplicate replies",
            "Ensuring no email is missed",
            "Discussing emails without leaving the inbox",
            "Understanding team performance",
            "Automating email sorting",
            "Answering common questions faster",
            "Meeting reply time goals (SLAs)",
            "Onboarding new team members",
            "Tracking who did what",
            "Collaborating on important replies"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered email assignment",
            "Email sentiment analysis",
            "AI-generated smart replies",
            "Automated conversation tagging",
            "AI-based thread summarization",
            "Predictive SLA breach analysis",
            "AI-powered spam filtering",
            "Natural language conversation search",
            "AI insights into team performance",
            "Smart duplicate conversation detection",
            "AI recommendations for new templates",
            "Automated key information extraction",
            "AI-powered communication tone checker",
            "Predictive escalation analysis",
            "AI-based language detection",
            "Smart @mention suggestions",
            "AI knowledge base assistant",
            "Automated follow-up reminders",
            "AI analysis of customer satisfaction",
            "Smart alerts for VIP emails"
          ]
        }
      ]
    },