import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Thrive": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Partner Overview", "Relationship Health", "Performance Metrics", "Recent Activities"]
        },
        {
          title: "Partners",
          icon: <Users className="w-4 h-4" />,
          items: ["All Partners", "Partner Profiles", "Partner Hierarchy", "Partner Onboarding"]
        },
        {
          title: "Opportunities",
          icon: <Target className="w-4 h-4" />,
          items: ["Deal Registration", "Partner Opportunities", "Pipeline Management", "Revenue Tracking"]
        },
        {
          title: "Programs",
          icon: <GraduationCap className="w-4 h-4" />,
          items: ["Partner Programs", "Certification Programs", "Training Materials", "Program Analytics"]
        },
        {
          title: "Marketing",
          icon: <MessageSquare className="w-4 h-4" />,
          items: ["Co-marketing", "Marketing Resources", "Campaign Management", "Brand Guidelines"]
        },
        {
          title: "Analytics",
          icon: <BarChart3 className="w-4 h-4" />,
          items: ["Partner Performance", "Revenue Analytics", "Program Effectiveness", "ROI Reports"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Partner directory",
            "Marketing content library",
            "Partner communication tools",
            "Lead submission form",
            "Activity dashboard"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Deal registration system",
            "Partner portal",
            "Commission management",
            "Joint business planning",
            "CRM integration"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Preventing channel conflict",
            "Onboarding new partners efficiently",
            "Providing partners with marketing assets",
            "Tracking partner-sourced leads",
            "Calculating partner commissions",
            "Measuring partner performance",
            "Keeping partners engaged",
            "Training partners on products",
            "Collaborating on co-marketing",
            "Fostering a partner community"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered partner recruitment",
            "Predictive partner performance analysis",
            "AI-based lead scoring",
            "Smart marketing content recommendations",
            "AI analysis of partner performance",
            "Automated channel conflict detection",
            "AI chatbot for partner FAQs",
            "Partner communication sentiment analysis",
            "AI-generated QBR presentations",
            "Natural language resource search",
            "Predictive partner churn analysis",
            "AI recommendations for incentives",
            "Smart alerts for high-value deals",
            "AI-driven training recommendations",
            "Automated partner newsletter generation",
            "AI-powered 'partner health' score",
            "Smart partner-to-market matching",
            "AI analysis of top partner habits",
            "Predictive channel sales forecasting",
            "AI-powered co-marketing suggestions"
          ]
        }
      ]
    }