import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";

"Vault": {
      sections: [
        {
          title: "Dashboard",
          icon: <Home className="w-4 h-4" />,
          items: ["Password Overview", "Security Score", "Recent Activities", "Alerts"]
        },
        {
          title: "Passwords",
          icon: <Key className="w-4 h-4" />,
          items: ["All Passwords", "Favorites", "Weak Passwords", "Duplicate Passwords", "Recently Used"]
        },
        {
          title: "Secure Notes",
          icon: <Lock className="w-4 h-4" />,
          items: ["Personal Notes", "Business Notes", "Credit Cards", "Bank Accounts", "Documents"]
        },
        {
          title: "Sharing",
          icon: <Share2 className="w-4 h-4" />,
          items: ["Shared Items", "Emergency Access", "Team Sharing", "Secure Sharing"]
        },
        {
          title: "Security",
          icon: <Shield className="w-4 h-4" />,
          items: ["Two-Factor Auth", "Security Audit", "Breach Monitoring", "Password Generator"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Account Settings", "Security Settings", "Backup & Sync", "Browser Extensions"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Password generator",
            "Browser autofill extensions",
            "Secure notes",
            "Folders for organization",
            "Mobile app access"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Secure password sharing",
            "Emergency access",
            "Security dashboard",
            "Data breach monitoring",
            "Two-factor authentication support"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Stopping use of weak passwords",
            "Ending the cycle of forgotten passwords",
            "Sharing passwords securely",
            "Planning for emergency access",
            "Discovering if passwords are breached",
            "Storing sensitive notes securely",
            "Accessing passwords on the go",
            "Assessing overall password health",
            "Preventing phishing attacks",
            "Managing passwords for a team"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI password strength analysis",
            "Smart phishing website alerts",
            "AI-driven password categorization",
            "Predictive password breach alerts",
            "AI-powered password importer",
            "Automated password changer",
            "AI-based personalized security tips",
            "Natural language password search",
            "AI detection of weak passwords",
            "Smart grouping of related accounts",
            "AI-driven security posture summary",
            "Automated email scanning for new accounts",
            "AI-based 2FA code organization",
            "Predictive analysis of critical accounts",
            "AI guidance for emergency access setup",
            "Smart public Wi-Fi warnings",
            "AI-generated secure security questions",
            "Automated compromised password checks",
            "AI-powered digital legacy planning",
            "Smart login anomaly detection"
          ]
        }
      ]
    },