import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react";
"Wiki": {
      sections: [
        {
          title: "Home",
          icon: <Home className="w-4 h-4" />,
          items: ["Wiki Home", "Recent Changes", "Popular Pages", "My Contributions", "Getting Started"]
        },
        {
          title: "Pages",
          icon: <FileText className="w-4 h-4" />,
          items: ["All Pages", "Create Page", "Page Templates", "Draft Pages", "My Pages", "Recently Viewed"]
        },
        {
          title: "Categories",
          icon: <Folder className="w-4 h-4" />,
          items: ["All Categories", "Create Category", "Category Tree", "Manage Categories"]
        },
        {
          title: "Search",
          icon: <Search className="w-4 h-4" />,
          items: ["Advanced Search", "Search Results", "Search History"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["User Contributions", "Page Comments", "Change History", "User Activity", "Team Wikis"]
        },
        {
          title: "Administration",
          icon: <Settings className="w-4 h-4" />,
          items: ["User Management", "Permissions", "Wiki Settings", "Templates", "Import/Export"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Simple page editor",
            "Page categories",
            "Search bar",
            "Internal page linking",
            "Version history"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Fine-grained permissions",
            "WYSIWYG editor",
            "Content embedding",
            "Page template system",
            "Team collaboration tools"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Centralizing scattered knowledge",
            "Standardizing employee onboarding",
            "Answering recurring questions",
            "Keeping documentation updated",
            "Finding the current version of a doc",
            "Restricting access to sensitive info",
            "Enabling non-technical users to contribute",
            "Organizing meeting minutes",
            "Standardizing document formats",
            "Fostering a knowledge-sharing culture"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "AI-powered natural language search",
            "AI suggestions for interlinking pages",
            "Automated content summarization",
            "AI recommendations for new articles",
            "Smart detection of stale content",
            "AI grammar and style checking",
            "Automated table of contents generation",
            "AI suggestions for page structure",
            "AI chatbot for answering questions",
            "Automated duplicate content detection",
            "AI-powered page translation",
            "Smart, automated page tagging",
            "AI-based expert finder",
            "Automated content generation",
            "AI 'knowledge graph' visualization",
            "Page comment sentiment analysis",
            "AI recommendations for related reading",
            "Automated broken link checker",
            "AI-assisted content migration",
            "Smart alerts for relevant content updates"
          ]
        }
      ]
    },
    
    