import {
  Home,
  Settings,
  BarChart3,
  Users,
  FileText,
  Calendar,
  MessageSquare,
  Phone,
  Mail,
  CreditCard,
  Package,
  Truck,
  Shield,
  Database,
  Code,
  Zap,
  Globe,
  Camera,
  Video,
  Headphones,
  Monitor,
  Smartphone,
  Cloud,
  Share2,
  Edit3,
  BookOpen,
  GraduationCap,
  Target,
  PieChart,
  TrendingUp,
  TrendingDown,
  Search,
  Filter,
  Upload,
  Download,
  Lock,
  Key,
  UserCheck,
  Wifi,
  Server,
  HardDrive,
  Layers,
  GitBranch,
  PlayCircle,
  PauseCircle,
  RotateCcw,
  RefreshCw,
  Eye,
  EyeOff,
  MousePointer,
  Palette,
  Brush,
  Image,
  FileImage,
  Music,
  FileMusic,
  Film,
  FileVideo,
  Mic,
  Volume2,
  Clock,
  Timer,
  MapPin,
  Map,
  Navigation,
  Compass,
  Star,
  Heart,
  ThumbsUp,
  MessageCircle,
  Send,
  Inbox,
  Archive,
  Tag,
  Bookmark,
  Flag,
  Bell,
  AlertCircle,
  CheckCircle,
  XCircle,
  Plus,
  Minus,
  X,
  Check,
  ArrowRight,
  ArrowLeft,
  ArrowUp,
  ArrowDown,
  ExternalLink,
  Paperclip,
  Scissors,
  Copy,
  Clipboard,
  Save,
  FolderOpen,
  Folder,
  Files,
  FileCheck,
  FilePlus,
  FileX,
  Grid,
  List,
  Table,
  Columns,
  Rows,
  MoreHorizontal,
  MoreVertical,
  Menu,
  Sidebar,
  Layout,
  Maximize2,
  Minimize2,
  Fullscreen,
  Crosshair,
  Move,
  RotateCw,
  FlipHorizontal,
  FlipVertical,
  Crop,
  ZoomIn,
  ZoomOut,
  Focus,
  Aperture,
  Sliders,
  ToggleLeft,
  ToggleRight,
  Power,
  PowerOff,
  Plug,
  Unplug,
  Battery,
  BatteryLow,
  Cpu,
  MemoryStick,
  HardDrive as Storage,
  Router,
  Bluetooth,
  Printer,
  Webcam,
  Gamepad2,
  Joystick,
  Keyboard,
  Mouse,
  Tablet,
  Laptop,
  Tv,
  Watch,
  Radio,
  Satellite,
  Bot,
  DollarSign,
  Building,
  Building2,
  Hash,
  Calculator,
  Link2,
  User,
  Wallet,
  Scale
} from "lucide-react"
"Writer": {
      sections: [
        {
          title: "Documents",
          icon: <FileText className="w-4 h-4" />,
          items: ["My Documents", "Recent Documents", "Shared Documents", "Templates", "Drafts"]
        },
        {
          title: "Collaboration",
          icon: <Users className="w-4 h-4" />,
          items: ["Real-time Editing", "Comments", "Suggestions", "Track Changes", "Document Sharing"]
        },
        {
          title: "Formatting",
          icon: <Edit3 className="w-4 h-4" />,
          items: ["Text Formatting", "Styles", "Headers & Footers", "Tables", "Images & Media"]
        },
        {
          title: "Review",
          icon: <CheckCircle className="w-4 h-4" />,
          items: ["Spell Check", "Grammar Check", "Document Review", "Version History", "Approval Workflow"]
        },
        {
          title: "Export",
          icon: <Download className="w-4 h-4" />,
          items: ["PDF Export", "Word Export", "HTML Export", "Print Options", "Batch Export"]
        },
        {
          title: "Settings",
          icon: <Settings className="w-4 h-4" />,
          items: ["Document Settings", "Sharing Permissions", "Auto-save Settings", "Language Settings"]
        },
        {
          title: "Small Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Document templates",
            "Rich text formatting",
            "Spell check & grammar",
            "Insert images & tables",
            "Download as PDF/DOCX"
          ]
        },
        {
          title: "Big Problem Solvers",
          icon: <Zap className="w-4 h-4" />,
          items: [
            "Real-time collaborative editing",
            "Track changes & commenting",
            "Integrated document signing",
            "Document merge feature",
            "AI-powered writing assistant"
          ]
        },
        {
          title: "Top Real-World Problems & Solutions",
          icon: <CheckCircle className="w-4 h-4" />,
          items: [
            "Solving document version control",
            "Streamlining document reviews",
            "Fixing spelling and grammar errors",
            "Getting documents legally signed",
            "Creating personalized bulk documents",
            "Improving document readability",
            "Preventing lost work with auto-save",
            "Automating form filling",
            "Working on documents from any device",
            "Finalizing and locking documents"
          ]
        },
        {
          title: "AI-Generated Ideas",
          icon: <Bot className="w-4 h-4" />,
          items: [
            "Zia: AI writing assistant",
            "AI-powered document summarization",
            "Smart compose & sentence completion",
            "AI-based tone analysis",
            "Automated content generation",
            "AI-powered research assistant",
            "Plagiarism checker",
            "AI suggestions for word choice",
            "Automated document translation",
            "Natural language editing commands",
            "AI 'ask your document' feature",
            "Smart template recommendations",
            "AI-based formatting suggestions",
            "Automated table of contents",
            "AI acronym & definition finder",
            "Predictive text that learns your style",
            "AI-driven internal linking suggestions",
            "Automated sensitive data masking",
            "AI analysis of document engagement",
            "Smart content repurposing"
          ]
        }
      ]
    }